#!/usr/bin/env python3
# Generated by Claudian.
"""JARVIS's autonomous learning loop.

    python3 brain/autonomous.py --status      # what it knows, what it's learned
    python3 brain/autonomous.py --cycle       # run one learning cycle now
    python3 brain/autonomous.py --daemon      # run forever, cycle every 6h

WHAT THIS ACTUALLY DOES
-----------------------
Every cycle:

  1. HARVEST   pull newly logged conversations out of SQLite and turn the
               trustworthy ones into labelled training data
  2. GATE      stop unless there is enough genuinely new material to matter
  3. TRAIN     fit a fresh intent classifier on everything collected so far
  4. EVALUATE  score the candidate on held-out phrasings it has never seen
  5. PROMOTE   replace the live model ONLY if the candidate is actually better

Step 5 is the part that makes this safe to leave running. A loop that always
promotes will happily walk itself downhill; every cycle would look like
progress while accuracy quietly rots. The previous model is kept and restored
on regression.

WHAT IT DELIBERATELY DOES NOT DO
--------------------------------
It does not train on its own predictions. `training/collect_feedback.py` only
accepts rows the *regex* tier decided, because those came from an explicit
pattern match and are effectively free ground truth. Rows the local model or
the LLM routed are excluded: training a model on its own output is
self-confirmation, and it would relabel its mistakes as correct and drift
further every cycle.

It also does not fine-tune the conversational LLM. That model lives on Groq's
servers. What learns here is the local intent router — which skill a phrase
maps to — and that is the part that governs whether JARVIS feels fast and
whether it understands *your* particular way of speaking.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

MODELS = ROOT / "data" / "models"
STATE_PATH = ROOT / "data" / "models" / "brain_state.json"
BACKUP = MODELS / "backup"

MODEL_FILES = ["intent_model.pt", "intent_vectorizer.pkl",
               "intent_labels.json", "intent_metrics.json"]

# Below this many genuinely new utterances a retrain is noise, not learning:
# a handful of extra rows shifts the validation split more than the weights.
MIN_NEW_UTTERANCES = 15

# A candidate has to clear the incumbent by more than run-to-run variance.
# Weight init and the train/val shuffle alone move accuracy ~1%.
PROMOTE_MARGIN = 0.005


# ── State ────────────────────────────────────────────────────────────────────

def load_state() -> dict:
    if STATE_PATH.exists():
        try:
            return json.loads(STATE_PATH.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return {"cycles": [], "last_utterance_count": 0, "promotions": 0,
            "rejections": 0}


def save_state(state: dict) -> None:
    try:
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        # Keep the log bounded — this runs unattended, potentially for months.
        state["cycles"] = state["cycles"][-60:]
        STATE_PATH.write_text(json.dumps(state, indent=2))
    except OSError as exc:
        print(f"  ! could not save brain state: {exc}", file=sys.stderr)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# ── Steps ────────────────────────────────────────────────────────────────────

def _run(args: list[str], timeout: int = 1800) -> tuple[int, str]:
    """Run a training script. Returns (exit code, combined output)."""
    try:
        p = subprocess.run(
            [sys.executable, *args], cwd=ROOT, capture_output=True,
            text=True, timeout=timeout,
        )
        return p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.TimeoutExpired:
        return 124, "timed out"
    except Exception as exc:  # noqa: BLE001 — a broken step must not kill the loop
        return 1, f"{type(exc).__name__}: {exc}"


def harvest() -> tuple[int, str]:
    """Turn logged conversations into labelled training data."""
    code, out = _run(["training/collect_feedback.py", "--write"])
    total = 0
    if FEEDBACK.exists():
        try:
            data = json.loads(FEEDBACK.read_text())
            total = sum(len(v) for v in data.values())
        except (json.JSONDecodeError, OSError):
            pass
    return total, out if code else ""


FEEDBACK = MODELS / "feedback_data.json"


def current_accuracy() -> float:
    try:
        return float(json.loads((MODELS / "intent_metrics.json").read_text())
                     .get("best_val_accuracy", 0.0))
    except Exception:
        return 0.0


def backup_model() -> bool:
    try:
        BACKUP.mkdir(parents=True, exist_ok=True)
        for name in MODEL_FILES:
            src = MODELS / name
            if src.exists():
                shutil.copy2(src, BACKUP / name)
        return True
    except OSError as exc:
        print(f"  ! backup failed: {exc}", file=sys.stderr)
        return False


def restore_model() -> bool:
    try:
        for name in MODEL_FILES:
            src = BACKUP / name
            if src.exists():
                shutil.copy2(src, MODELS / name)
        return True
    except OSError as exc:
        print(f"  ! restore failed: {exc}", file=sys.stderr)
        return False


# ── One cycle ────────────────────────────────────────────────────────────────

def cycle(force: bool = False, epochs: int = 100, quiet: bool = False) -> dict:
    log = (lambda *a: None) if quiet else print
    state = load_state()
    started = time.time()
    entry: dict = {"at": _now(), "outcome": "", "detail": ""}

    log("\n" + "=" * 62)
    log("  JARVIS learning cycle")
    log("=" * 62)

    # 1. Harvest ─────────────────────────────────────────────────────────
    total, err = harvest()
    if err:
        log(f"  harvest warning: {err.strip()[:160]}")
    previous = state.get("last_utterance_count", 0)
    new = total - previous
    log(f"  harvested        {total} utterances ({new:+d} since last cycle)")

    # 2. Gate ────────────────────────────────────────────────────────────
    if not force and new < MIN_NEW_UTTERANCES:
        log(f"  → skipping: needs {MIN_NEW_UTTERANCES} new to be worth a retrain")
        entry.update(outcome="skipped",
                     detail=f"{new} new (< {MIN_NEW_UTTERANCES})")
        state["cycles"].append(entry)
        state["last_utterance_count"] = total
        save_state(state)
        return entry

    before = current_accuracy()
    log(f"  incumbent        {before:.2%} validation accuracy")

    if not backup_model():
        entry.update(outcome="aborted", detail="could not back up incumbent")
        state["cycles"].append(entry); save_state(state)
        return entry

    # 3. Train ───────────────────────────────────────────────────────────
    log("  training…")
    code, out = _run(["training/train_intent_model.py", "--epochs", str(epochs)])
    if code != 0:
        log(f"  ✗ training failed — keeping incumbent\n{out.strip()[-400:]}")
        restore_model()
        entry.update(outcome="failed", detail=out.strip()[-200:])
        state["cycles"].append(entry); save_state(state)
        return entry

    after = current_accuracy()
    log(f"  candidate        {after:.2%} validation accuracy")

    # 4. Evaluate on genuinely unseen phrasings ──────────────────────────
    ev_code, ev_out = _run(["training/holdout_eval.py"], timeout=600)
    holdout = ""
    for line in ev_out.splitlines():
        if "accuracy" in line.lower():
            holdout = line.strip()
            break
    if holdout:
        log(f"  holdout          {holdout}")

    # 5. Promote or roll back ────────────────────────────────────────────
    if after >= before + PROMOTE_MARGIN:
        log(f"  ✓ PROMOTED  {before:.2%} → {after:.2%}")
        entry.update(outcome="promoted",
                     detail=f"{before:.4f} → {after:.4f}")
        state["promotions"] = state.get("promotions", 0) + 1
    else:
        log(f"  ↩ rejected: {after:.2%} is not clearly better than "
            f"{before:.2%} — restoring incumbent")
        restore_model()
        entry.update(outcome="rejected",
                     detail=f"{after:.4f} vs {before:.4f}")
        state["rejections"] = state.get("rejections", 0) + 1

    entry["before"] = round(before, 4)
    entry["after"] = round(after, 4)
    entry["utterances"] = total
    entry["holdout"] = holdout
    entry["seconds"] = round(time.time() - started, 1)

    state["cycles"].append(entry)
    state["last_utterance_count"] = total
    save_state(state)

    log(f"  done in {entry['seconds']}s")
    log("=" * 62 + "\n")
    return entry


# ── Status ───────────────────────────────────────────────────────────────────

def status() -> dict:
    state = load_state()
    metrics = {}
    try:
        metrics = json.loads((MODELS / "intent_metrics.json").read_text())
    except Exception:
        pass

    utterances = 0
    if FEEDBACK.exists():
        try:
            utterances = sum(len(v) for v in json.loads(FEEDBACK.read_text()).values())
        except Exception:
            pass

    # How much raw material is sitting in the log waiting to be harvested.
    logged = trainable = 0
    try:
        from memory.store import MemoryStore
        store = MemoryStore()
        logged = len(store.recent_events(limit=100_000))
        trainable = len(store.training_events(source="regex",
                                              min_confidence=0.85,
                                              limit=100_000))
    except Exception:
        pass

    cycles = state.get("cycles", [])
    return {
        "accuracy": metrics.get("best_val_accuracy", 0.0),
        "trained_at": metrics.get("trained_at", "never"),
        "train_size": metrics.get("train_size", 0),
        "n_classes": metrics.get("n_classes", 0),
        "utterances_collected": utterances,
        "conversations_logged": logged,
        "conversations_trainable": trainable,
        "pending": max(0, trainable - state.get("last_utterance_count", 0)),
        "cycles_run": len(cycles),
        "promotions": state.get("promotions", 0),
        "rejections": state.get("rejections", 0),
        "last_cycle": cycles[-1] if cycles else None,
        "min_new_to_train": MIN_NEW_UTTERANCES,
    }


def print_status() -> None:
    s = status()
    print("\n" + "=" * 62)
    print("  JARVIS brain")
    print("=" * 62)
    print(f"  intent accuracy     {s['accuracy']:.2%}")
    print(f"  trained on          {s['train_size']} samples, "
          f"{s['n_classes']} skills")
    print(f"  last trained        {s['trained_at']}")
    print()
    print(f"  conversations       {s['conversations_logged']} logged, "
          f"{s['conversations_trainable']} usable as labels")
    print(f"  harvested           {s['utterances_collected']} utterances")
    print(f"  pending             {s['pending']} new "
          f"(needs {s['min_new_to_train']} to trigger a retrain)")
    print()
    print(f"  cycles run          {s['cycles_run']} "
          f"({s['promotions']} promoted, {s['rejections']} rejected)")
    if s["last_cycle"]:
        c = s["last_cycle"]
        print(f"  last cycle          {c['at']} — {c['outcome']} {c.get('detail','')}")
    print("=" * 62 + "\n")


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description="JARVIS autonomous learning")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--cycle", action="store_true")
    ap.add_argument("--daemon", action="store_true")
    ap.add_argument("--force", action="store_true",
                    help="retrain even without enough new data")
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--interval", type=int, default=6 * 3600,
                    help="daemon cycle interval in seconds (default 6h)")
    args = ap.parse_args()

    if args.daemon:
        print(f"JARVIS brain daemon — cycling every {args.interval}s. Ctrl-C to stop.")
        while True:
            try:
                cycle(force=args.force, epochs=args.epochs)
            except KeyboardInterrupt:
                print("\nstopped.")
                return 0
            except Exception as exc:  # noqa: BLE001 — never die unattended
                print(f"  ! cycle crashed: {type(exc).__name__}: {exc}",
                      file=sys.stderr)
            time.sleep(args.interval)

    if args.cycle:
        cycle(force=args.force, epochs=args.epochs)
        return 0

    print_status()
    return 0


if __name__ == "__main__":
    sys.exit(main())
