#!/usr/bin/env python3
# Generated by Claudian.
"""JARVIS's knowledge base — what it has read, and how it recalls it.

    python3 brain/knowledge.py --add-url https://example.com/article
    python3 brain/knowledge.py --add-file notes.md
    python3 brain/knowledge.py --add-dir "/Users/ruthish/Downloads/Ruthish's AI Brain"
    python3 brain/knowledge.py --ask "what did I decide about the crop model"
    python3 brain/knowledge.py --explore "retrieval augmented generation"
    python3 brain/knowledge.py --stats

WHAT THIS IS
------------
Retrieval, not training. Documents are chunked, indexed, and searched; the
best-matching passages are handed to the model as context when you ask
something. JARVIS ends up *knowing your material* without a single weight
changing.

WHY NOT TRAIN ON IT
-------------------
Fine-tuning a language model on your notes needs a GPU cluster, and it is the
wrong tool regardless: the model would learn the *style* of your notes far
more reliably than their contents, and you could not correct a fact without
retraining. Retrieval updates the instant you add a file, cites what it used,
and forgets cleanly when you delete something.

HOW SEARCH WORKS
----------------
SQLite FTS5 with BM25 ranking. No embedding model, no vector database, no
extra dependency — which matters on an 8 GB machine where a sentence
transformer would compete with everything else for memory. BM25 on chunked
prose is a strong baseline; the ceiling is lower than embeddings but it works
offline, indexes instantly, and never needs a download.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sqlite3
import sys
import textwrap
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DB = ROOT / "data" / "memory_store" / "knowledge.db"

CHUNK_CHARS = 1100        # roughly a long paragraph — big enough to answer
CHUNK_OVERLAP = 160       # carry context across boundaries
UA = "JarvisKnowledge/1.0 (personal assistant; +local)"

TEXT_SUFFIXES = {".md", ".txt", ".py", ".js", ".ts", ".json", ".yaml", ".yml",
                 ".html", ".css", ".rst", ".csv", ".sh", ".toml", ".ini"}

SKIP_DIRS = {"node_modules", ".git", "venv", ".venv", "__pycache__",
             "build", "dist", ".obsidian", "vendor", "site-packages"}


# ── Schema ───────────────────────────────────────────────────────────────────

def connect() -> sqlite3.Connection:
    DB.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS sources (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            uri        TEXT NOT NULL UNIQUE,
            title      TEXT NOT NULL DEFAULT '',
            kind       TEXT NOT NULL DEFAULT 'file',
            digest     TEXT NOT NULL DEFAULT '',
            added_at   TEXT NOT NULL,
            chunks     INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS chunks (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            source_id  INTEGER NOT NULL,
            ord        INTEGER NOT NULL,
            text       TEXT NOT NULL,
            FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE CASCADE
        );
        CREATE VIRTUAL TABLE IF NOT EXISTS chunks_fts
            USING fts5(text, content='chunks', content_rowid='id');

        CREATE TRIGGER IF NOT EXISTS chunks_ai AFTER INSERT ON chunks BEGIN
            INSERT INTO chunks_fts(rowid, text) VALUES (new.id, new.text);
        END;
        CREATE TRIGGER IF NOT EXISTS chunks_ad AFTER DELETE ON chunks BEGIN
            INSERT INTO chunks_fts(chunks_fts, rowid, text)
                VALUES('delete', old.id, old.text);
        END;
    """)
    return conn


# ── Ingest ───────────────────────────────────────────────────────────────────

def chunk(text: str) -> list[str]:
    """Split on paragraphs, then pack to roughly CHUNK_CHARS with overlap.

    Splitting mid-sentence is what makes retrieval feel stupid — the passage
    that answers the question gets cut in half and neither piece scores.
    """
    text = re.sub(r"\n{3,}", "\n\n", text.strip())
    if not text:
        return []

    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    out: list[str] = []
    buf = ""

    for p in paras:
        if len(buf) + len(p) + 2 <= CHUNK_CHARS:
            buf = f"{buf}\n\n{p}" if buf else p
            continue
        if buf:
            out.append(buf)
            tail = buf[-CHUNK_OVERLAP:]
            buf = f"{tail}\n\n{p}" if len(p) < CHUNK_CHARS else p
        else:
            # One paragraph longer than a chunk — split on sentences.
            for i in range(0, len(p), CHUNK_CHARS - CHUNK_OVERLAP):
                out.append(p[i:i + CHUNK_CHARS])
            buf = ""
    if buf:
        out.append(buf)
    return [c for c in out if len(c.strip()) > 40]


def strip_html(html: str) -> tuple[str, str]:
    """Crude but dependency-free extraction. Returns (title, text)."""
    title = ""
    m = re.search(r"<title[^>]*>(.*?)</title>", html, re.S | re.I)
    if m:
        title = re.sub(r"\s+", " ", m.group(1)).strip()

    # Drop the parts that are never prose.
    for tag in ("script", "style", "nav", "header", "footer", "svg", "noscript"):
        html = re.sub(rf"<{tag}\b.*?</{tag}>", " ", html, flags=re.S | re.I)

    html = re.sub(r"<(p|div|li|h[1-6]|br|tr)\b[^>]*>", "\n", html, flags=re.I)
    text = re.sub(r"<[^>]+>", " ", html)
    text = (text.replace("&nbsp;", " ").replace("&amp;", "&")
                .replace("&lt;", "<").replace("&gt;", ">")
                .replace("&quot;", '"').replace("&#39;", "'"))
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n\s*", "\n\n", text)
    return title, text.strip()


def fetch_url(url: str, timeout: int = 25) -> tuple[str, str]:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        ctype = resp.headers.get("Content-Type", "")
        raw = resp.read(4_000_000)          # cap: don't swallow a 200MB file
    body = raw.decode("utf-8", errors="replace")
    if "html" in ctype.lower() or body.lstrip()[:200].lower().startswith(("<!do", "<htm")):
        return strip_html(body)
    return "", body


def add_source(conn: sqlite3.Connection, uri: str, title: str, text: str,
               kind: str) -> dict:
    """Insert or replace a source and its chunks. Skips unchanged content."""
    digest = hashlib.sha256(text.encode("utf-8", "ignore")).hexdigest()[:32]

    row = conn.execute("SELECT id, digest FROM sources WHERE uri = ?",
                       (uri,)).fetchone()
    if row and row["digest"] == digest:
        return {"uri": uri, "status": "unchanged", "chunks": 0}

    pieces = chunk(text)
    if not pieces:
        return {"uri": uri, "status": "empty", "chunks": 0}

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    with conn:
        if row:
            conn.execute("DELETE FROM chunks WHERE source_id = ?", (row["id"],))
            conn.execute(
                "UPDATE sources SET title=?, digest=?, added_at=?, chunks=? WHERE id=?",
                (title or uri, digest, now, len(pieces), row["id"]))
            sid = row["id"]
        else:
            cur = conn.execute(
                "INSERT INTO sources (uri,title,kind,digest,added_at,chunks) "
                "VALUES (?,?,?,?,?,?)",
                (uri, title or uri, kind, digest, now, len(pieces)))
            sid = cur.lastrowid

        conn.executemany(
            "INSERT INTO chunks (source_id, ord, text) VALUES (?,?,?)",
            [(sid, i, c) for i, c in enumerate(pieces)])

    return {"uri": uri, "status": "updated" if row else "added",
            "chunks": len(pieces), "title": title or uri}


def add_file(conn: sqlite3.Connection, path: Path) -> dict:
    if path.suffix.lower() == ".pdf":
        return add_pdf(conn, path)
    if path.suffix.lower() not in TEXT_SUFFIXES:
        return {"uri": str(path), "status": "skipped (unsupported type)", "chunks": 0}
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return {"uri": str(path), "status": f"error: {exc}", "chunks": 0}
    return add_source(conn, str(path), path.name, text, "file")


def add_pdf(conn: sqlite3.Connection, path: Path) -> dict:
    try:
        from pypdf import PdfReader
    except ImportError:
        try:
            from PyPDF2 import PdfReader   # older name
        except ImportError:
            return {"uri": str(path),
                    "status": "skipped (pip install pypdf for PDFs)",
                    "chunks": 0}
    try:
        reader = PdfReader(str(path))
        text = "\n\n".join((pg.extract_text() or "") for pg in reader.pages)
    except Exception as exc:  # noqa: BLE001
        return {"uri": str(path), "status": f"error: {exc}", "chunks": 0}
    return add_source(conn, str(path), path.name, text, "pdf")


def add_dir(conn: sqlite3.Connection, root: Path, limit: int = 2000) -> list[dict]:
    results = []
    for p in sorted(root.rglob("*")):
        if len(results) >= limit:
            break
        if not p.is_file():
            continue
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        if p.suffix.lower() not in TEXT_SUFFIXES and p.suffix.lower() != ".pdf":
            continue
        if p.stat().st_size > 3_000_000:
            continue
        r = add_file(conn, p)
        if r["chunks"]:
            results.append(r)
    return results


# ── Retrieve ─────────────────────────────────────────────────────────────────

# Spoken questions are mostly scaffolding. "what is my crop disease detection
# project about" is 4 content words wrapped in 5 function words, and OR-ing
# them all lets documents win on "what/is/my/about" alone — which is exactly
# how a query about the crop project returned a note on project structure.
STOPWORDS = {
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "am", "do", "does", "did", "have", "has", "had", "can", "could",
    "will", "would", "shall", "should", "may", "might", "must",
    "i", "me", "my", "mine", "you", "your", "yours", "he", "she", "it",
    "we", "us", "our", "they", "them", "their", "this", "that", "these",
    "those", "what", "which", "who", "whom", "whose", "when", "where",
    "why", "how", "and", "or", "but", "if", "then", "than", "so", "as",
    "of", "in", "on", "at", "to", "for", "with", "about", "from", "by",
    "into", "over", "after", "before", "up", "down", "out", "off",
    "again", "just", "any", "some", "all", "no", "not", "only", "own",
    "same", "too", "very", "s", "t", "don", "now", "tell", "say", "said",
    "get", "got", "know", "like", "want", "give", "make", "please",
    "jarvis", "hey", "ok", "okay", "thing", "stuff",
}


def _fts_query(raw: str) -> str:
    """Build an FTS5 expression from a spoken question.

    Every token is quoted so a bare AND/OR is treated as a literal rather
    than an operator. Stop words are dropped so scoring reflects the terms
    that actually carry the question.
    """
    safe = "".join(c if (c.isalnum() or c.isspace()) else " " for c in raw)
    tokens = [t for t in safe.lower().split() if len(t) > 2]
    content = [t for t in tokens if t not in STOPWORDS]

    # If stripping leaves nothing, the question really was all scaffolding —
    # fall back rather than returning zero results.
    chosen = content or tokens
    return " OR ".join(f'"{t}"' for t in chosen)


def _terms(query: str) -> list[str]:
    safe = "".join(c if (c.isalnum() or c.isspace()) else " " for c in query)
    toks = [t for t in safe.lower().split() if len(t) > 2]
    return [t for t in toks if t not in STOPWORDS] or toks


def search(conn: sqlite3.Connection, query: str, limit: int = 6) -> list[dict]:
    """Retrieve passages, ranked by how much of the question they cover.

    BM25 alone is not enough here. With OR matching, a document that repeats
    one common query word many times outranks one that matches every word
    once — asking about the "crop disease detection project" returned a note
    on project structure, because it said "project" more often.

    So: over-fetch on BM25, then re-rank primarily by how many DISTINCT query
    terms a passage contains. Matching four of four beats matching one of four
    loudly, which is what a person means by relevance.
    """
    expr = _fts_query(query)
    if not expr:
        return []

    terms = _terms(query)
    try:
        rows = conn.execute("""
            SELECT c.text, s.title, s.uri, bm25(chunks_fts) AS score
            FROM chunks_fts
            JOIN chunks c ON c.id = chunks_fts.rowid
            JOIN sources s ON s.id = c.source_id
            WHERE chunks_fts MATCH ?
            ORDER BY score
            LIMIT ?
        """, (expr, max(limit * 6, 40))).fetchall()
    except sqlite3.OperationalError:
        return []

    scored = []
    for r in rows:
        hay = (r["text"] + " " + r["title"]).lower()
        covered = sum(1 for t in terms if t in hay)
        # Title matches are a strong signal — a note *named* for the topic is
        # usually the one you meant.
        title_hits = sum(1 for t in terms if t in r["title"].lower())
        scored.append({
            "text": r["text"], "title": r["title"], "uri": r["uri"],
            "score": round(r["score"], 3),
            "covered": covered,
            "_rank": (-(covered + title_hits * 0.5), r["score"]),
        })

    scored.sort(key=lambda x: x["_rank"])
    for s in scored:
        s.pop("_rank", None)
    return scored[:limit]


def build_context(hits: list[dict], budget: int = 3200) -> str:
    """Pack hits into a prompt block, newest-relevant first, within budget."""
    parts, used = [], 0
    for h in hits:
        block = f"[{h['title']}]\n{h['text'].strip()}"
        if used + len(block) > budget:
            break
        parts.append(block)
        used += len(block)
    return "\n\n---\n\n".join(parts)


# ── Explore: learn from the internet on its own ──────────────────────────────

def explore(conn: sqlite3.Connection, topic: str, depth: int = 4) -> list[dict]:
    """Read about a topic from the open web and remember what it finds.

    Wikipedia's REST API is used deliberately rather than a search engine:
    it is stable, permissively licensed, returns clean prose instead of
    markup, and does not need a key or scraping that would break weekly.
    """
    results = []
    base = "https://en.wikipedia.org/w/api.php"

    params = urllib.parse.urlencode({
        "action": "query", "list": "search", "srsearch": topic,
        "srlimit": depth, "format": "json",
    })
    try:
        req = urllib.request.Request(f"{base}?{params}", headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=25) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as exc:  # noqa: BLE001
        return [{"uri": topic, "status": f"search failed: {exc}", "chunks": 0}]

    for item in data.get("query", {}).get("search", []):
        title = item.get("title", "")
        if not title:
            continue
        p = urllib.parse.urlencode({
            "action": "query", "prop": "extracts", "explaintext": 1,
            "titles": title, "format": "json", "redirects": 1,
        })
        try:
            req = urllib.request.Request(f"{base}?{p}", headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=25) as resp:
                pdata = json.loads(resp.read().decode("utf-8"))
            pages = pdata.get("query", {}).get("pages", {})
            extract = next(iter(pages.values()), {}).get("extract", "")
        except Exception as exc:  # noqa: BLE001
            results.append({"uri": title, "status": f"error: {exc}", "chunks": 0})
            continue

        if len(extract) < 400:
            continue
        url = "https://en.wikipedia.org/wiki/" + urllib.parse.quote(title.replace(" ", "_"))
        results.append(add_source(conn, url, title, extract, "web"))
    return results


# ── Stats ────────────────────────────────────────────────────────────────────

def stats(conn: sqlite3.Connection) -> dict:
    s = conn.execute("SELECT COUNT(*) n, COALESCE(SUM(chunks),0) c FROM sources").fetchone()
    kinds = {r["kind"]: r["n"] for r in conn.execute(
        "SELECT kind, COUNT(*) n FROM sources GROUP BY kind")}
    recent = [dict(r) for r in conn.execute(
        "SELECT title, uri, kind, chunks, added_at FROM sources "
        "ORDER BY id DESC LIMIT 10")]
    return {"sources": s["n"], "chunks": s["c"], "by_kind": kinds,
            "recent": recent, "db": str(DB),
            "size_kb": round(DB.stat().st_size / 1024) if DB.exists() else 0}


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description="JARVIS knowledge base")
    ap.add_argument("--add-url", action="append", default=[])
    ap.add_argument("--add-file", action="append", default=[])
    ap.add_argument("--add-dir")
    ap.add_argument("--explore")
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--ask")
    ap.add_argument("--stats", action="store_true")
    args = ap.parse_args()

    conn = connect()
    did = False

    for url in args.add_url:
        did = True
        try:
            title, text = fetch_url(url)
            r = add_source(conn, url, title or url, text, "web")
        except Exception as exc:  # noqa: BLE001
            r = {"uri": url, "status": f"error: {exc}", "chunks": 0}
        print(f"  {r['status']:<12} {r.get('title', r['uri'])[:60]}  ({r['chunks']} chunks)")

    for f in args.add_file:
        did = True
        r = add_file(conn, Path(f).expanduser())
        print(f"  {r['status']:<12} {Path(f).name}  ({r['chunks']} chunks)")

    if args.add_dir:
        did = True
        rs = add_dir(conn, Path(args.add_dir).expanduser())
        total = sum(r["chunks"] for r in rs)
        print(f"  indexed {len(rs)} files, {total} chunks")
        for r in rs[:10]:
            print(f"    {r['status']:<10} {Path(r['uri']).name[:56]}")
        if len(rs) > 10:
            print(f"    … and {len(rs) - 10} more")

    if args.explore:
        did = True
        print(f"  reading about {args.explore!r}…")
        for r in explore(conn, args.explore, args.depth):
            print(f"    {r['status']:<12} {r.get('title', r['uri'])[:56]}  ({r['chunks']} chunks)")

    if args.ask:
        did = True
        hits = search(conn, args.ask)
        if not hits:
            print("  nothing indexed matches that.")
        for h in hits:
            print(f"\n  ── {h['title']}  (score {h['score']})")
            print(textwrap.indent(textwrap.fill(h["text"][:420], 76), "     "))

    if args.stats or not did:
        s = stats(conn)
        print("\n" + "=" * 62)
        print("  JARVIS knowledge base")
        print("=" * 62)
        print(f"  sources    {s['sources']}")
        print(f"  passages   {s['chunks']}")
        print(f"  by kind    {s['by_kind'] or '—'}")
        print(f"  size       {s['size_kb']} KB")
        if s["recent"]:
            print("\n  most recent:")
            for r in s["recent"][:6]:
                print(f"    {r['kind']:<5} {r['title'][:48]:<48} {r['chunks']:>4} chunks")
        print("=" * 62 + "\n")

    conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
