#!/usr/bin/env python3
# Generated by Claudian.
"""Rotate the Groq API key safely.

    python3 set_groq_key.py

Prompts for the key with echo off, validates it against Groq *before* writing
anything, backs up .env, then writes the new value.

Why a script instead of just editing .env:
  - getpass means the key never appears on screen, in your shell history,
    or in a chat transcript.
  - It validates first. Writing an invalid key and only finding out when
    JARVIS says "having trouble reaching Groq" is how the last one went
    unnoticed — it was well-formed, just revoked.
  - It backs up .env, so a typo can't cost you your other settings.
"""

from __future__ import annotations

import getpass
import shutil
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV = ROOT / ".env"


def validate(key: str) -> tuple[bool, str]:
    """Ask Groq whether the key works. Returns (ok, message)."""
    try:
        from openai import OpenAI
    except ImportError:
        return False, "the `openai` package is not installed"

    try:
        client = OpenAI(api_key=key, base_url="https://api.groq.com/openai/v1",
                        timeout=20)
        models = client.models.list()
        names = [m.id for m in models.data][:4]
        return True, f"{len(models.data)} models available (e.g. {', '.join(names)})"
    except Exception as exc:
        msg = str(exc)
        if "401" in msg or "invalid_api_key" in msg:
            return False, "Groq rejected it (401 Invalid API Key)"
        if "403" in msg:
            return False, "Groq returned 403 — key valid but not permitted"
        return False, f"{type(exc).__name__}: {msg[:150]}"


def write_key(key: str) -> bool:
    """Replace GROQ_API_KEY in .env, preserving everything else."""
    try:
        if ENV.exists():
            # `.env` has no stem, so Path(".env").with_suffix(".env.bak.N")
            # produced ".env.env.bak.N". Build the name explicitly instead.
            backup = ENV.parent / f".env.bak.{int(time.time())}"
            shutil.copy2(ENV, backup)
            print(f"  backed up .env → {backup.name}")
            lines = ENV.read_text().splitlines()
        else:
            lines = []

        out, replaced = [], False
        for line in lines:
            if line.strip().startswith("GROQ_API_KEY="):
                out.append(f"GROQ_API_KEY={key}")
                replaced = True
            else:
                out.append(line)
        if not replaced:
            out.append(f"GROQ_API_KEY={key}")

        ENV.write_text("\n".join(out) + "\n")
        ENV.chmod(0o600)   # the file now holds a live credential
        return True
    except OSError as exc:
        print(f"  ✗ could not write .env: {exc}", file=sys.stderr)
        return False


def main() -> int:
    print("\n" + "=" * 62)
    print("  Rotate the Groq API key")
    print("=" * 62)
    print("\n  1. Open  https://console.groq.com/keys")
    print("  2. Delete the old key, then 'Create API Key'")
    print("  3. Copy it — Groq shows it exactly once")
    print("  4. Paste below (nothing will appear as you type)\n")

    try:
        key = getpass.getpass("  Paste key: ").strip()
    except (KeyboardInterrupt, EOFError):
        print("\n  cancelled.")
        return 1

    if not key:
        print("  ✗ nothing entered.")
        return 1
    if not key.startswith("gsk_"):
        print(f"  ⚠ that doesn't start with 'gsk_' (got '{key[:4]}…').")
        if input("    Continue anyway? [y/N] ").strip().lower() != "y":
            return 1

    print("\n  checking with Groq…")
    ok, msg = validate(key)
    if not ok:
        print(f"  ✗ {msg}")
        print("    Nothing was written. Your existing .env is untouched.")
        return 1

    print(f"  ✓ key works — {msg}")

    if not write_key(key):
        return 1

    print("  ✓ written to .env (permissions set to 600)\n")
    print("  Next:")
    print("    pkill -f 'web/server.py' && python3 web/server.py")
    print("    python3 bench_latency.py --no-tts    # real latency numbers")
    print("=" * 62 + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
