#!/usr/bin/env python3
# Generated by Claudian.
"""Stop Jarvis completely.

    python3 stop.py

Kills more than the Python process, because two things outlive it:

  * `say` subprocesses. The system voice is spawned with subprocess.Popen,
    so it is a separate process. Killing Jarvis does not stop it — it keeps
    speaking whatever was queued, which sounds exactly like Jarvis talking
    after being shut down.

  * Detached instances. The desktop app's Initialize button spawns with
    detached=True, so that copy is not a child of any terminal and survives
    closing the window it was started from.
"""

from __future__ import annotations

import os
import signal
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


def _pids(pattern: str) -> list[int]:
    try:
        out = subprocess.run(["pgrep", "-f", pattern],
                             capture_output=True, text=True, timeout=10)
        return [int(x) for x in out.stdout.split() if x.strip().isdigit()]
    except Exception:
        return []


def _stop(pids: list[int], label: str) -> int:
    stopped = 0
    for pid in pids:
        if pid == os.getpid():
            continue
        try:
            os.kill(pid, signal.SIGTERM)
            stopped += 1
            print(f"  stopped {label} (pid {pid})")
        except ProcessLookupError:
            pass
        except Exception as e:
            print(f"  could not stop pid {pid}: {e}")
    return stopped


def main() -> int:
    print("Stopping Jarvis...")

    total = 0
    total += _stop(_pids(r"python.*run\.py"), "assistant")

    # Give the assistant a moment to shut down cleanly before killing the
    # speech it may still be flushing.
    if total:
        time.sleep(1.0)

    # The system voice runs as its own process and would otherwise keep
    # talking after everything else has gone.
    total += _stop(_pids(r"^say |/usr/bin/say"), "speech")

    # Anything still alive after SIGTERM.
    time.sleep(0.5)
    stubborn = _pids(r"python.*run\.py")
    for pid in stubborn:
        try:
            os.kill(pid, signal.SIGKILL)
            print(f"  force-killed pid {pid}")
        except Exception:
            pass

    try:
        from core.single_instance import LOCK_PATH, release
        release()
        if LOCK_PATH.exists():
            LOCK_PATH.unlink()
    except Exception:
        pass

    # Leave the visualiser showing 'offline' rather than frozen mid-speech.
    try:
        from core import voice_state
        voice_state.clear()
        from voice import audio_level
        audio_level.reset()
    except Exception:
        pass

    print()
    if total:
        print(f"Stopped {total} process(es).")
    else:
        print("Nothing was running.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
