# Generated by Claudian.
"""Memory module — persistent personal context for Jarvis.

Backed by a local SQLite database at
`data/memory_store/jarvis_memory.db` with three tables:

  facts      — things Jarvis remembers about Ruthish ("Aki = my girlfriend")
  events     — log of commands + replies, useful for end-of-day summaries
  summaries  — daily summaries produced by the end_of_day agent

Full-text search is done via SQLite's built-in FTS5 virtual table — no
sentence-transformers or vector DB required.  Everything lives on-disk,
in-process, zero network calls.

Public API (don't import from store.py directly):

    from memory import get_memory
    m = get_memory()
    m.remember("my girlfriend is called Aki", tags=["people"])
    m.recall("who is aki")                 -> list[Fact]
    m.log_event(user_text, reply_text)
    m.today_events()                       -> list[Event]
    m.save_daily_summary(text)
"""

from memory.store import Event, Fact, MemoryStore, Summary, get_memory

__all__ = ["MemoryStore", "Fact", "Event", "Summary", "get_memory"]
