# Generated by Claudian.
"""SQLite-backed memory store with FTS5 full-text search.

Design:
  • Three tables: facts, events, summaries.
  • Each `facts` row has a matching `facts_fts` FTS5 row for keyword recall.
  • One shared connection per process (SQLite is fine with serialized access
    from a single thread; we guard with a lock for the rare multi-thread case
    — the scheduler thread + main loop both write).
  • Schema is created on first call — no migrations yet.

Why not embeddings?  sentence-transformers is ~100 MB of torch + heavy
cold-start.  FTS5 handles "jarvis what did i say about aki" perfectly well
for Ruthish's scale (hundreds-to-thousands of facts/events).  We can swap
in embeddings later without changing the public API.
"""

from __future__ import annotations

import re
import sqlite3
import threading
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from utils.logger import get_logger

logger = get_logger(__name__)


def _utc_now_iso() -> str:
    """Current UTC time as a naive ISO string.

    `datetime.utcnow()` is deprecated (and scheduled for removal) as of
    Python 3.12; this project runs on 3.14 where it already warns.  We build
    the timestamp from an aware object but strip the tzinfo before storing,
    so the on-disk format stays byte-identical to existing rows and
    lexicographic comparison in SQL keeps working.
    """
    return datetime.now(timezone.utc).replace(tzinfo=None).isoformat()


def _fts_query(raw: str) -> str:
    """Turn user text into a safe FTS5 MATCH expression.

    Every token is wrapped in double quotes so FTS5 treats it as a literal
    string.  Without this, a query containing a bare uppercase AND / OR / NOT
    is parsed as an operator and raises `fts5: syntax error`.  That is
    reachable in practice: the LLM intent classifier returns extracted
    entities verbatim, without the lower-casing that STT applies.
    """
    safe = "".join(c if (c.isalnum() or c.isspace()) else " " for c in raw)
    tokens = [t for t in safe.split() if t]
    if not tokens:
        return ""
    # Escape embedded quotes by doubling, per FTS5 string-literal rules.
    return " OR ".join('"' + t.replace('"', '""') + '"' for t in tokens)


# ── Data classes ─────────────────────────────────────────────────────────────

@dataclass
class Fact:
    id: int
    text: str
    tags: str          # comma-separated
    created_at: str    # ISO format


@dataclass
class Event:
    id: int
    user_text: str
    reply_text: str
    skill: str
    created_at: str


@dataclass
class Summary:
    id: int
    day: str           # YYYY-MM-DD
    text: str
    created_at: str


# ── Schema ───────────────────────────────────────────────────────────────────

_SCHEMA = """
CREATE TABLE IF NOT EXISTS facts (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    text        TEXT NOT NULL,
    tags        TEXT NOT NULL DEFAULT '',
    created_at  TEXT NOT NULL
);

CREATE VIRTUAL TABLE IF NOT EXISTS facts_fts USING fts5(
    text, tags, content='facts', content_rowid='id'
);

CREATE TRIGGER IF NOT EXISTS facts_ai AFTER INSERT ON facts BEGIN
    INSERT INTO facts_fts(rowid, text, tags) VALUES (new.id, new.text, new.tags);
END;

CREATE TRIGGER IF NOT EXISTS facts_ad AFTER DELETE ON facts BEGIN
    INSERT INTO facts_fts(facts_fts, rowid, text, tags)
        VALUES('delete', old.id, old.text, old.tags);
END;

CREATE TABLE IF NOT EXISTS events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_text   TEXT NOT NULL,
    reply_text  TEXT NOT NULL,
    skill       TEXT NOT NULL DEFAULT '',
    created_at  TEXT NOT NULL,
    -- Which routing tier produced `skill`, and how sure it was.
    -- Only 'regex' rows are trustworthy enough to train on: the registry
    -- matches by explicit pattern, so a high-confidence hit is effectively
    -- a free ground-truth label. 'local' and 'llm' rows are predictions and
    -- would teach the model its own mistakes.
    source      TEXT NOT NULL DEFAULT '',
    confidence  REAL NOT NULL DEFAULT 0.0
);
CREATE INDEX IF NOT EXISTS events_created_idx ON events(created_at);

CREATE TABLE IF NOT EXISTS summaries (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    day         TEXT NOT NULL UNIQUE,
    text        TEXT NOT NULL,
    created_at  TEXT NOT NULL
);
"""


# ── Store ────────────────────────────────────────────────────────────────────

class MemoryStore:
    def __init__(self, db_path: Optional[str] = None):
        if db_path is None:
            # Default: `<project>/data/memory_store/jarvis_memory.db`
            base = Path(__file__).parent.parent / "data" / "memory_store"
            base.mkdir(parents=True, exist_ok=True)
            db_path = str(base / "jarvis_memory.db")
        self._path = db_path
        self._lock = threading.Lock()
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        with self._lock:
            self._conn.executescript(_SCHEMA)
            self._migrate()
            self._conn.commit()
        logger.info(f"Memory store ready at {db_path}")

    def _migrate(self) -> None:
        """Add columns that post-date the original schema.

        `CREATE TABLE IF NOT EXISTS` is a no-op on an existing table, so new
        columns never appear on databases created before they were added.
        Caller already holds the lock.
        """
        existing = {
            row["name"]
            for row in self._conn.execute("PRAGMA table_info(events)").fetchall()
        }
        for column, ddl in (
            ("source", "ALTER TABLE events ADD COLUMN source TEXT NOT NULL DEFAULT ''"),
            ("confidence", "ALTER TABLE events ADD COLUMN confidence REAL NOT NULL DEFAULT 0.0"),
        ):
            if column not in existing:
                self._conn.execute(ddl)
                logger.info(f"Memory store migrated: added events.{column}")

    # ── Facts ────────────────────────────────────────────────────────────────

    def remember(self, text: str, tags: Optional[list[str]] = None) -> int:
        """Store a fact.  Returns the new row id."""
        text = text.strip()
        if not text:
            raise ValueError("fact text cannot be empty")
        tags_csv = ",".join(t.strip() for t in (tags or []) if t.strip())
        now = _utc_now_iso()
        with self._lock:
            cur = self._conn.execute(
                "INSERT INTO facts (text, tags, created_at) VALUES (?, ?, ?)",
                (text, tags_csv, now),
            )
            self._conn.commit()
            return cur.lastrowid

    def recall(self, query: str, limit: int = 5) -> list[Fact]:
        """Full-text search over facts.  Ranks by relevance."""
        query = query.strip()
        if not query:
            return []
        match = _fts_query(query)
        if not match:
            return []
        with self._lock:
            rows = self._conn.execute(
                """
                SELECT f.id, f.text, f.tags, f.created_at
                FROM facts_fts
                JOIN facts f ON f.id = facts_fts.rowid
                WHERE facts_fts MATCH ?
                ORDER BY rank
                LIMIT ?
                """,
                (match, limit),
            ).fetchall()
        return [Fact(id=r["id"], text=r["text"], tags=r["tags"], created_at=r["created_at"]) for r in rows]

    def all_facts(self, limit: int = 100) -> list[Fact]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT id, text, tags, created_at FROM facts ORDER BY id DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [Fact(r["id"], r["text"], r["tags"], r["created_at"]) for r in rows]

    def forget_fact(self, fact_id: int) -> bool:
        with self._lock:
            cur = self._conn.execute("DELETE FROM facts WHERE id = ?", (fact_id,))
            self._conn.commit()
            return cur.rowcount > 0

    # ── Events ───────────────────────────────────────────────────────────────

    def log_event(
        self,
        user_text: str,
        reply_text: str,
        skill: str = "",
        source: str = "",
        confidence: float = 0.0,
    ) -> int:
        """Record a handled command.

        `source` is the routing tier ('regex' | 'local' | 'llm') and
        `confidence` its score. Both are recorded so the training pipeline
        can select only trustworthy labels — see training/collect_feedback.py.
        """
        now = _utc_now_iso()
        with self._lock:
            cur = self._conn.execute(
                "INSERT INTO events (user_text, reply_text, skill, created_at, "
                "source, confidence) VALUES (?, ?, ?, ?, ?, ?)",
                (user_text, reply_text, skill, now, source, float(confidence)),
            )
            self._conn.commit()
            return cur.lastrowid

    def training_events(self, source: str = "regex", min_confidence: float = 0.85,
                        limit: int = 10000) -> list[tuple[str, str]]:
        """Return (utterance, skill) pairs trustworthy enough to train on."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT user_text, skill FROM events "
                "WHERE source = ? AND confidence >= ? AND skill != '' "
                "ORDER BY id DESC LIMIT ?",
                (source, min_confidence, limit),
            ).fetchall()
        return [(r["user_text"], r["skill"]) for r in rows]

    def today_events(self) -> list[Event]:
        """Events since LOCAL midnight.

        Rows are stored in UTC, so we take local midnight and convert it to
        the equivalent UTC instant.  Comparing against UTC midnight directly
        (the previous behaviour) was wrong for every non-UTC timezone: at
        UTC+5:30 it treated 05:30 local as the start of the day, so anything
        said between midnight and 05:30 was attributed to the day before —
        silently corrupting the end-of-day recap.
        """
        local_midnight = (
            datetime.now()
            .astimezone()
            .replace(hour=0, minute=0, second=0, microsecond=0)
        )
        since = local_midnight.astimezone(timezone.utc).replace(tzinfo=None).isoformat()
        with self._lock:
            rows = self._conn.execute(
                "SELECT id, user_text, reply_text, skill, created_at "
                "FROM events WHERE created_at >= ? ORDER BY id ASC",
                (since,),
            ).fetchall()
        return [
            Event(
                id=r["id"],
                user_text=r["user_text"],
                reply_text=r["reply_text"],
                skill=r["skill"],
                created_at=r["created_at"],
            )
            for r in rows
        ]

    def search_events(self, query: str, limit: int = 10) -> list[tuple[str, str]]:
        """Find past exchanges matching `query`.

        Used to pull aged-out conversation turns back into context. The
        events table has no FTS index (only `facts` does), so this is a LIKE
        scan over the most recent rows — bounded, and fast enough at this
        scale. Tokens are matched individually so word order does not matter.
        """
        tokens = [t for t in re.findall(r"[a-z0-9']+", query.lower()) if len(t) > 2]
        if not tokens:
            return []

        # Ignore words too common to discriminate — they would match nearly
        # every row and drown out the useful hits.
        stop = {"the", "and", "you", "what", "was", "did", "have", "for",
                "that", "this", "with", "about", "your", "can", "how", "are"}
        # If every token is a stopword the query carries no signal, so return
        # nothing rather than falling back and matching arbitrary rows —
        # injecting irrelevant "earlier context" is worse than injecting none.
        tokens = [t for t in tokens if t not in stop]
        if not tokens:
            return []

        where = " OR ".join(["LOWER(user_text) LIKE ?"] * len(tokens))
        params = [f"%{t}%" for t in tokens]

        with self._lock:
            rows = self._conn.execute(
                f"SELECT user_text, reply_text FROM events "
                f"WHERE ({where}) AND skill != 'conversation' "
                f"ORDER BY id DESC LIMIT ?",
                (*params, limit),
            ).fetchall()

        # Rank by how many query tokens each row actually contains, so a row
        # matching three terms outranks one scraping a single common word.
        scored = []
        for r in rows:
            text = (r["user_text"] or "").lower()
            scored.append((sum(1 for t in tokens if t in text), r))
        scored.sort(key=lambda x: -x[0])
        return [(r["user_text"], r["reply_text"]) for _, r in scored]

    def recent_events(self, limit: int = 20) -> list[Event]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT id, user_text, reply_text, skill, created_at FROM events "
                "ORDER BY id DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [
            Event(r["id"], r["user_text"], r["reply_text"], r["skill"], r["created_at"])
            for r in rows
        ]

    # ── Summaries ────────────────────────────────────────────────────────────

    def save_daily_summary(self, text: str, day: Optional[str] = None) -> int:
        if day is None:
            day = datetime.now().strftime("%Y-%m-%d")
        now = _utc_now_iso()
        with self._lock:
            cur = self._conn.execute(
                "INSERT INTO summaries (day, text, created_at) VALUES (?, ?, ?) "
                "ON CONFLICT(day) DO UPDATE SET text = excluded.text, created_at = excluded.created_at",
                (day, text, now),
            )
            self._conn.commit()
            return cur.lastrowid

    def latest_summary(self) -> Optional[Summary]:
        with self._lock:
            row = self._conn.execute(
                "SELECT id, day, text, created_at FROM summaries "
                "ORDER BY day DESC LIMIT 1"
            ).fetchone()
        if not row:
            return None
        return Summary(row["id"], row["day"], row["text"], row["created_at"])

    # ── Housekeeping ─────────────────────────────────────────────────────────

    def close(self):
        with self._lock:
            self._conn.close()


# ── Singleton accessor ───────────────────────────────────────────────────────

_singleton: Optional[MemoryStore] = None


def get_memory() -> MemoryStore:
    global _singleton
    if _singleton is None:
        _singleton = MemoryStore()
    return _singleton


def reset_memory_for_tests():
    """Testing helper."""
    global _singleton
    if _singleton is not None:
        _singleton.close()
    _singleton = None
