# Generated by Claudian.
"""Regression suite — one test per bug found and fixed during the audit.

Every test here failed before its fix and passes after.  Run it after any
change:

    python3 tests/test_regressions.py

Deliberately dependency-free (no pytest) so it always runs, and it never
touches the real microphone, the real database, or the real speakers.
"""

from __future__ import annotations

import os
import sys
import tempfile
import threading
import time
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

PASS, FAIL = [], []


def check(name: str, condition: bool, detail: str = "") -> None:
    (PASS if condition else FAIL).append(name)
    mark = "PASS" if condition else "FAIL"
    line = f"  [{mark}] {name}"
    if detail and not condition:
        line += f"\n         {detail}"
    print(line)


def section(title: str) -> None:
    print(f"\n{title}")
    print("-" * len(title))


# ══════════════════════════════════════════════════════════════════════════
# BUG 1 — TTS race: concurrent speakers truncated each other and opened the
# mic mid-reply, causing a self-hearing feedback loop.
# ══════════════════════════════════════════════════════════════════════════

def test_tts_concurrency() -> None:
    section("BUG 1 — TTS concurrency (truncation + feedback loop)")

    from voice.text_to_speech import TextToSpeech
    from voice import speaking_state

    class FakeTTS(TextToSpeech):
        """Same machinery, silent + fast: no real `say` subprocess."""
        def _say(self, text: str) -> None:
            self.log.append(("start", text))
            time.sleep(0.05)
            self.log.append(("end", text))

    tts = FakeTTS()
    tts.log = []

    threads = [threading.Thread(target=tts.speak, args=(f"line {i}",)) for i in range(6)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    starts = sum(1 for e in tts.log if e[0] == "start")
    ends = sum(1 for e in tts.log if e[0] == "end")
    check("all utterances complete (none truncated)", starts == 6 and ends == 6,
          f"started={starts} ended={ends}")

    paired = all(
        tts.log[i][0] == "start" and tts.log[i + 1][0] == "end"
        and tts.log[i][1] == tts.log[i + 1][1]
        for i in range(0, len(tts.log), 2)
    )
    check("utterances never interleave", paired)

    # Mic must stay shut for the whole burst, not flicker open between lines.
    tts2 = FakeTTS()
    tts2.log = []
    seen: list[bool] = []

    def watch() -> None:
        for _ in range(40):
            seen.append(speaking_state.is_speaking())
            time.sleep(0.01)

    w = threading.Thread(target=watch)
    w.start()
    for i in range(4):
        tts2.speak_async(f"s{i}")
    w.join()
    tts2._queue.join()

    if True in seen:
        first = seen.index(True)
        last = len(seen) - 1 - seen[::-1].index(True)
        gaps = seen[first:last].count(False)
    else:
        gaps = -1
    check("mic never reopens mid-reply", gaps == 0, f"gaps={gaps}")

    tts.shutdown()
    tts2.shutdown()
    check("worker thread joins on shutdown", not tts._worker.is_alive())


# ══════════════════════════════════════════════════════════════════════════
# BUG 2 — Memory store: deprecated utcnow, UTC-vs-local day boundary,
# FTS5 operator injection.
# ══════════════════════════════════════════════════════════════════════════

def test_memory_store() -> None:
    section("BUG 2 — Memory store (timezone + FTS5)")

    from memory.store import MemoryStore, _fts_query, _utc_now_iso

    db = tempfile.mktemp(suffix=".db")
    m = MemoryStore(db)
    try:
        m.remember("aki likes coffee")
        m.remember("deploy jarvis on friday")

        # FTS5 used to raise `fts5: syntax error` on bare uppercase operators.
        # Reachable because the LLM classifier returns entities uncased.
        crashed = []
        for q in ["AND", "OR", "NOT", "NEAR", "Aki OR coffee", '"quoted"', "a AND b"]:
            try:
                m.recall(q)
            except Exception as e:
                crashed.append((q, str(e)))
        check("FTS5 operators do not crash recall", not crashed, str(crashed[:2]))

        check("recall still finds real matches", len(m.recall("coffee")) == 1)
        check("_fts_query quotes every token", _fts_query("a OR b") == '"a" OR "OR" OR "b"',
              _fts_query("a OR b"))

        # Stored timestamps must be naive-UTC ISO, matching legacy rows.
        ts = _utc_now_iso()
        check("timestamp has no tz suffix (format stable)", "+" not in ts and "Z" not in ts, ts)

        # today_events must use LOCAL midnight. At UTC+5:30 the old code
        # treated 05:30 local as the day's start.
        m.log_event("hi", "hello", "test")
        check("today_events sees an event logged now", len(m.today_events()) >= 1)

        local_midnight = datetime.now().astimezone().replace(
            hour=0, minute=0, second=0, microsecond=0
        )
        as_utc = local_midnight.astimezone(timezone.utc).replace(tzinfo=None)
        offset_h = (local_midnight.utcoffset().total_seconds() / 3600) if local_midnight.utcoffset() else 0
        check("local midnight converts to a different UTC instant when TZ != UTC",
              (as_utc.hour != 0) == (offset_h != 0),
              f"local={local_midnight} utc={as_utc} offset={offset_h}")
    finally:
        m.close()
        if os.path.exists(db):
            os.unlink(db)


# ══════════════════════════════════════════════════════════════════════════
# BUG 3 — Wake word: 15% false-wake rate on ordinary speech.
# ══════════════════════════════════════════════════════════════════════════

def test_wake_word() -> None:
    section("BUG 3 — Wake word false positives")

    from utils.helpers import contains_wake_word, strip_wake_word

    negatives = [
        "the service is down", "i need a haircut", "service call", "harvest season",
        "drive us to the airport", "give us a minute", "jar of honey is open",
        "car is in the garage", "starve is not a word", "carve is what i did",
        "nervous about the interview", "jarred his shoulder", "lets serve ice cream",
        "the java is hot", "arrive as soon as you can", "garage is open",
        "marvel is great", "the archives are gone", "java is my language",
        "curve is steep", "javascript is fine", "can we start now",
        "shall we begin", "are we there yet", "i love you",
    ]
    positives = [
        "jarvis open spotify", "darvies what time is it", "jervis play music",
        "jarvos volume 50", "hey jarvis", "jarav is open chrome",
        "jarvees turn it up", "darvis lock the screen", "jarvis",
        "jarviss hello", "ok jarvis news",
    ]

    fp = [t for t in negatives if contains_wake_word(t)]
    fn = [t for t in positives if not contains_wake_word(t)]
    check("no false wakes on ordinary speech", not fp, f"fired on: {fp}")
    check("all known mishearings still wake", not fn, f"missed: {fn}")

    cases = {
        "jarvis open spotify": "open spotify",
        "hey jarvis open spotify": "open spotify",
        "so jarvis what time is it": "what time is it",
        "darvies play music": "play music",
        "jarav is open chrome": "open chrome",
        "umm ok jarvis volume 50": "volume 50",
    }
    bad = {k: strip_wake_word(k) for k, v in cases.items() if strip_wake_word(k) != v}
    check("wake word stripped, command preserved", not bad, str(bad))


# ══════════════════════════════════════════════════════════════════════════
# BUG 4 — AppleScript: no timeout (worker-pool starvation) + injection.
# ══════════════════════════════════════════════════════════════════════════

def test_applescript() -> None:
    section("BUG 4 — AppleScript timeout + injection")

    from integrations.macos import apple_script as a

    check("quotes escaped", a._q('say "hi"') == '"say \\"hi\\""', a._q('say "hi"'))
    check("backslashes escaped first", a._q("a\\b") == '"a\\\\b"', a._q("a\\b"))

    payload = 'Finder" to get name of every process --'
    script = f"tell application {a._q(payload)} to activate"
    # After escaping there must be exactly one unescaped quote pair.
    unescaped = script.replace('\\"', "")
    check("injection payload cannot break out of the literal",
          unescaped.count('"') == 2, script)

    if sys.platform == "darwin":
        t0 = time.time()
        ok, out = a.run("delay 30", timeout=2)
        elapsed = time.time() - t0
        check("osascript timeout is enforced", (not ok) and elapsed < 5,
              f"ok={ok} elapsed={elapsed:.1f}s")
    else:
        check("osascript timeout (skipped: not macOS)", True)


# ══════════════════════════════════════════════════════════════════════════
# BUG 5 — Skill routing: new skills must not hijack existing commands.
# ══════════════════════════════════════════════════════════════════════════

def test_routing() -> None:
    section("BUG 5 — Skill routing / no hijacking")

    from skills._registry import get_registry

    r = get_registry()
    check("all skills load", len(r.all_skills()) >= 28, f"{len(r.all_skills())} loaded")

    expected = [
        ("open spotify", "open_app"),
        ("open docker", "open_app"),          # must NOT go to coding_assistant
        ("volume 50", "volume"),
        ("what time is it", "time_date"),     # must NOT go to wikipedia
        ("take a screenshot", "screenshot"),
        ("google python tutorials", "web_search"),
        ("how do i write an async function in python", "coding_assistant"),
        ("who is alan turing", "wikipedia_lookup"),
        ("tell me a joke", "jokes"),
        ("what is my cpu usage", "system_stats"),
        ("define ephemeral", "define_word"),
        ("give me the news", "news_headlines"),
    ]
    wrong = []
    for text, want in expected:
        skill, _ = r.match(text)
        got = skill.name if skill else "NONE"
        if got != want:
            wrong.append(f"{text!r}: {got} != {want}")
    check("every utterance routes to the right skill", not wrong, "; ".join(wrong))

    names = [s.name for s in r.all_skills()]
    check("no duplicate skill names", len(names) == len(set(names)),
          f"dupes: {[n for n in names if names.count(n) > 1]}")


# ══════════════════════════════════════════════════════════════════════════
# BUG 6 — Module hygiene: importable names, no stale (C)-prefixed modules.
# ══════════════════════════════════════════════════════════════════════════

def test_imports() -> None:
    section("BUG 6 — Module import hygiene")

    import importlib
    mods = [
        "core.assistant", "core.command_router", "utils.latency_profiler",
        "utils.helpers", "config.user_config", "memory.store",
        "voice.text_to_speech", "integrations.macos.apple_script",
        "skills.wikipedia_lookup", "skills.jokes", "skills.system_stats",
        "skills.define_word", "skills.news_headlines", "skills.coding_assistant",
    ]
    broken = []
    for mod in mods:
        try:
            importlib.import_module(mod)
        except Exception as e:
            broken.append(f"{mod}: {type(e).__name__}")
    check("all modules import", not broken, "; ".join(broken))

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    stale = []
    for dirpath, dirnames, filenames in os.walk(root):
        if "node_modules" in dirpath or "/.git" in dirpath or "/desktop" in dirpath:
            continue
        stale += [f for f in filenames if f.startswith("(C)") and f.endswith(".py")]
    check("no (C)-prefixed python modules (unimportable)", not stale, str(stale))


# ══════════════════════════════════════════════════════════════════════════
# BUG 7 — Local intent model must abstain rather than guess, and must never
# degrade routing that the regex registry already handles.
# ══════════════════════════════════════════════════════════════════════════

def test_local_intent_model() -> None:
    section("BUG 7 — Local intent model (gating + safety)")

    from ai.intent_classifier_local import get_local_classifier

    clf = get_local_classifier()
    if not clf.available:
        check("model present (skipped: not trained)", True)
        return

    check("confidence gate is meaningful", 0.5 <= clf.threshold <= 0.99,
          f"threshold={clf.threshold}")

    # Nonsense must not clear the gate — abstaining is the whole design.
    junk = ["asdf qwer zxcv", "blorp fnord", "aaaaaaa", "xyzzy plugh"]
    confident_junk = [j for j in junk if clf.predict_gated(j)[0] is not None]
    check("abstains on nonsense", not confident_junk, f"answered: {confident_junk}")

    # Clear commands should be handled locally and correctly.
    clear = [
        ("bring up spotify", "open_app"),
        ("crack me up", "jokes"),
        ("how much power is left", "battery"),
        ("catch me up on whats going on", "news_headlines"),
    ]
    wrong = []
    for text, want in clear:
        got, conf = clf.predict_gated(text)
        if got != want:
            wrong.append(f"{text!r}: {got}({conf:.2f}) != {want}")
    check("unambiguous phrasings route locally", not wrong, "; ".join(wrong))

    # The model must never override a confident regex match.
    from skills._registry import get_registry
    reg = get_registry()
    overridden = []
    for text, want in [("volume 50", "volume"), ("take a screenshot", "screenshot"),
                       ("what time is it", "time_date"), ("open spotify", "open_app")]:
        skill, m = reg.match(text)
        if reg.is_high_confidence(m) and skill.name != want:
            overridden.append(text)
    check("regex tier still wins on exact commands", not overridden, str(overridden))

    # Inference must stay fast enough to be worth having.
    t0 = time.perf_counter()
    for _ in range(50):
        clf.predict("bring up spotify")
    per_call_ms = (time.perf_counter() - t0) / 50 * 1000
    check("inference under 10ms", per_call_ms < 10, f"{per_call_ms:.2f}ms")


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — routing provenance + feedback loop.
# ══════════════════════════════════════════════════════════════════════════

def test_feedback_loop() -> None:
    section("FEATURE — feedback loop (provenance + trustworthy labels)")

    import sqlite3
    from memory.store import MemoryStore

    db = tempfile.mktemp(suffix=".db")
    m = MemoryStore(db)
    try:
        m.log_event("volume 50", "ok", "volume", source="regex", confidence=0.95)
        m.log_event("crank it", "ok", "volume", source="local", confidence=0.88)
        m.log_event("do the thing", "ok", "conversation", source="llm", confidence=0.6)
        m.log_event("low conf", "ok", "volume", source="regex", confidence=0.4)

        trainable = m.training_events()
        check("only high-confidence regex rows are trainable",
              trainable == [("volume 50", "volume")], str(trainable))
        check("model predictions are excluded from labels",
              all(t[0] not in ("crank it", "do the thing") for t in trainable))
        check("all events still recorded", len(m.recent_events()) == 4)
    finally:
        m.close()
        if os.path.exists(db):
            os.unlink(db)

    # Migration: a pre-existing DB must gain the new columns without data loss.
    legacy = tempfile.mktemp(suffix=".db")
    conn = sqlite3.connect(legacy)
    conn.executescript(
        "CREATE TABLE events (id INTEGER PRIMARY KEY AUTOINCREMENT, "
        "user_text TEXT NOT NULL, reply_text TEXT NOT NULL, "
        "skill TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);"
    )
    conn.execute(
        "INSERT INTO events (user_text, reply_text, skill, created_at) "
        "VALUES ('old', 'row', 'volume', '2026-01-01T00:00:00')"
    )
    conn.commit()
    conn.close()

    m2 = MemoryStore(legacy)
    try:
        cols = {r["name"] for r in m2._conn.execute("PRAGMA table_info(events)").fetchall()}
        check("migration adds source/confidence", {"source", "confidence"} <= cols, str(cols))
        check("migration preserves existing rows", len(m2.recent_events()) == 1)
    finally:
        m2.close()
        if os.path.exists(legacy):
            os.unlink(legacy)

    from ai.intent_augment import _load_feedback, build_augmented
    fb = _load_feedback()
    if fb:
        data = build_augmented()
        missing = [
            (s, u) for s, utts in fb.items() for u in utts
            if u.strip().lower() not in data.get(s, [])
        ]
        check("collected feedback reaches the training set", not missing, str(missing[:3]))
    else:
        check("feedback file absent is handled (fresh install)", True)


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — live voice state published for the HUD.
# ══════════════════════════════════════════════════════════════════════════

def test_voice_state() -> None:
    section("FEATURE — live voice state channel")

    import json
    from core import voice_state

    original = voice_state.get_state()
    try:
        seen = []
        for st in (voice_state.IDLE, voice_state.LISTENING,
                   voice_state.THINKING, voice_state.SPEAKING):
            voice_state.set_state(st)
            with open(voice_state.STATE_PATH) as f:
                seen.append(json.load(f)["state"])
        check("every transition is published",
              seen == ["idle", "listening", "thinking", "speaking"], str(seen))

        voice_state.set_state(voice_state.THINKING, command="what time is it")
        with open(voice_state.STATE_PATH) as f:
            payload = json.load(f)
        check("command text is carried", payload.get("last_command") == "what time is it")
        check("timestamp present for staleness detection", "updated_at" in payload)

        voice_state.clear()
        with open(voice_state.STATE_PATH) as f:
            check("clear() marks offline", json.load(f)["state"] == "offline")

        # Must never raise, whatever happens to the file.
        try:
            voice_state.set_state("idle")
            ok = True
        except Exception:
            ok = False
        check("publishing never raises", ok)
    finally:
        voice_state.set_state(original)


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — conversation window (follow-ups without the wake word).
# ══════════════════════════════════════════════════════════════════════════

def test_conversation_window() -> None:
    section("FEATURE — conversation window")

    from voice.wake_word import WakeWordDetector

    d = WakeWordDetector()

    check("window configured", d._followup_window > 0, f"{d._followup_window}")
    check("closed at rest", not d._followup_active())

    # Arming must NOT open the window — it opens when TTS finishes, so a long
    # spoken reply cannot consume the time meant for the user's response.
    d.arm_followup()
    check("arming alone does not open the window",
          d._followup_armed and not d._followup_active())

    d._open_followup()
    check("opens once TTS finishes", d._followup_active() and not d._followup_armed)

    # Expiry
    d._followup_until = time.monotonic() - 1
    check("expires after the deadline", not d._followup_active())

    d._open_followup()
    d._close_followup("explicit wake")
    check("explicit wake word closes it", not d._followup_active())

    # Disabled configuration must never open a window.
    d._followup_window = 0.0
    d._followup_armed = False
    d.arm_followup()
    check("window of 0 disables the feature", not d._followup_armed)

    # Filler must not be treated as a command, but real one-word answers must.
    ignore = ["um", "uh", "hmm", "a", "the", "er", "mm", "x", ""]
    accept = ["no", "yes", "yeah", "sure", "ok", "hi", "stop", "next",
              "play music", "what time is it"]
    bad_ignore = [t for t in ignore if not WakeWordDetector._is_filler(t)]
    bad_accept = [t for t in accept if WakeWordDetector._is_filler(t)]
    check("disfluencies ignored", not bad_ignore, str(bad_ignore))
    check("short real answers accepted (incl. 'no')", not bad_accept, str(bad_accept))


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — barge-in (interrupt mid-sentence without self-hearing).
# ══════════════════════════════════════════════════════════════════════════

def test_bargein() -> None:
    section("FEATURE — barge-in + echo rejection")

    from voice.echo_filter import is_echo, looks_like_interrupt
    from voice.wake_word import WakeWordDetector

    spoken = ("The weather in Chennai today is thirty two degrees and mostly "
              "sunny with a chance of rain later this evening.")

    # Jarvis hearing itself MUST be rejected — this is the feedback-loop guard.
    echoes = [
        "the weather in chennai today is thirty two degrees",
        "thirty two degrees and mostly sunny",
        "with a chance of rain later this evening",
        "mostly sunny with a chance of rain",
        "the weather in chennai",
    ]
    missed = [e for e in echoes if not is_echo(e, spoken)]
    check("self-hearing rejected", not missed, str(missed))

    # Real speech must get through.
    user = ["stop", "jarvis stop", "open spotify", "what about tomorrow",
            "no i meant delhi", "play some music instead", "cancel that"]
    blocked = [u for u in user if is_echo(u, spoken)]
    check("real barge-ins pass the filter", not blocked, str(blocked))

    check("no reference text means not echo", not is_echo("hello", None))
    check("empty transcription is never a barge-in", is_echo("", spoken))

    interrupts = ["stop", "shut up", "wait", "hold on", "enough", "cancel"]
    not_interrupts = ["open spotify", "hello", "what time is it"]
    check("stop phrases recognised",
          all(looks_like_interrupt(p) for p in interrupts))
    check("commands are not stop phrases",
          not any(looks_like_interrupt(p) for p in not_interrupts))

    d = WakeWordDetector()
    check("default mode is the conservative one", d._bargein_mode in ("wake", "off"),
          d._bargein_mode)

    # Runaway guard must disable itself rather than loop forever.
    d._bargein_mode = "any"
    d._bargein_times = []
    allowed = [d._note_bargein() for _ in range(6)]
    check("runaway guard disables barge-in", d._bargein_mode == "off",
          f"allowed={allowed}")


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — pluggable speech engines (ElevenLabs + fallback).
# ══════════════════════════════════════════════════════════════════════════

def test_speech_engines() -> None:
    section("FEATURE — speech engines + fallback")

    from voice.speech_engines import (
        ElevenLabsEngine, FallbackEngine, MacSayEngine, SpeechEngine,
        build_engine,
    )

    mac = MacSayEngine("Samantha", 160)
    check("macOS say engine available", mac.available())

    # No key must mean unavailable, never a crash.
    check("ElevenLabs unavailable without a key",
          not ElevenLabsEngine(api_key="", voice_id="x").available())
    check("ElevenLabs unavailable without a voice id",
          not ElevenLabsEngine(api_key="k" * 32, voice_id="").available())

    # Cache keys must be stable and voice-specific, or switching voices would
    # replay the old one.
    e1 = ElevenLabsEngine("k" * 32, "voiceA", cache=False)
    e2 = ElevenLabsEngine("k" * 32, "voiceB", cache=False)
    check("cache key is stable for the same text",
          e1._cache_path("hello") == e1._cache_path("hello"))
    check("cache key differs per voice",
          e1._cache_path("hello") != e2._cache_path("hello"))
    check("cache key differs per text",
          e1._cache_path("hello") != e1._cache_path("goodbye"))

    # Fallback behaviour
    class Boom(SpeechEngine):
        name = "boom"
        def available(self): return True
        def speak(self, text, should_stop=None): return False
        def stop(self): pass

    class Records(SpeechEngine):
        name = "records"
        def __init__(self): self.spoken = []
        def available(self): return True
        def speak(self, text, should_stop=None):
            self.spoken.append(text); return True
        def stop(self): pass

    backup = Records()
    fb = FallbackEngine(primary=Boom(), backup=backup)
    fb.speak("hello")
    check("failure falls through to the backup engine",
          backup.spoken == ["hello"], str(backup.spoken))

    # A barge-in is not a failure — it must NOT re-speak via the backup.
    backup2 = Records()
    fb2 = FallbackEngine(primary=Boom(), backup=backup2)
    fb2.speak("interrupted", should_stop=lambda: True)
    check("interruption does not trigger fallback re-speak",
          backup2.spoken == [], str(backup2.spoken))

    # A working primary must be used and the backup left alone.
    good, unused = Records(), Records()
    fb3 = FallbackEngine(primary=good, backup=unused)
    fb3.speak("direct")
    check("working primary is used", good.spoken == ["direct"] and unused.spoken == [])

    # The factory must always return something usable.
    engine = build_engine()
    check("factory returns a usable engine", engine.available(), engine.name)


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — TTS still behaves after the engine refactor.
# ══════════════════════════════════════════════════════════════════════════

def test_tts_with_engine() -> None:
    section("FEATURE — TTS queue over a pluggable engine")

    from voice.speech_engines import SpeechEngine
    from voice.text_to_speech import TextToSpeech

    class Fake(SpeechEngine):
        name = "fake"
        def __init__(self):
            self.spoken = []
            self.stopped = 0
        def available(self): return True
        def speak(self, text, should_stop=None):
            if should_stop and should_stop():
                return False
            self.spoken.append(text)
            time.sleep(0.02)
            return True
        def stop(self): self.stopped += 1

    fake = Fake()
    tts = TextToSpeech(engine=fake)
    try:
        tts.speak("one")
        tts.speak("two")
        check("engine receives utterances in order",
              fake.spoken == ["one", "two"], str(fake.spoken))

        check("current_text is None when idle", tts.current_text() is None)

        tts.stop()
        check("stop() reaches the engine", fake.stopped >= 1)

        check("engine_name is exposed", tts.engine_name == "fake", tts.engine_name)
    finally:
        tts.shutdown()
    check("worker joins with a custom engine", not tts._worker.is_alive())


# ══════════════════════════════════════════════════════════════════════════
# BUG 8 — PCM byte misalignment produced static during neural TTS playback.
# ══════════════════════════════════════════════════════════════════════════

def test_pcm_alignment() -> None:
    section("BUG 8 — PCM sample alignment (audible static)")

    import math
    import struct

    from voice.speech_engines import SAMPLE_RATE, SILENCE_PAD

    # 16-bit PCM: every sample is exactly 2 bytes. The HTTP stream splits on
    # arbitrary boundaries — real measured sizes below, several odd. Writing an
    # odd-length buffer to a paInt16 device shifts every later sample by one
    # byte and is heard as static for the rest of the clip.
    samples = [int(8000 * math.sin(2 * math.pi * 440 * i / SAMPLE_RATE))
               for i in range(35840)]
    clean = b"".join(struct.pack("<h", v) for v in samples)

    sizes = [4096, 1183, 2403, 1211, 744, 1213, 2260, 1226]
    chunks, i = [], 0
    while i < len(clean):
        chunks.append(clean[i:i + sizes[len(chunks) % len(sizes)]])
        i += sizes[(len(chunks) - 1) % len(sizes)]

    check("test fixture actually contains odd-length chunks",
          any(len(c) % 2 for c in chunks))

    # Naive: write each chunk as it arrives.
    offset, naive_bad = 0, 0
    for c in chunks:
        if offset % 2:
            naive_bad += 1
        offset += len(c)
    check("naive playback misaligns samples (the bug)", naive_bad > 0,
          f"{naive_bad} misaligned writes")

    # Fixed: hold the trailing odd byte over to the next chunk.
    offset, fixed_bad, carry, out = 0, 0, b"", bytearray()
    for c in chunks:
        buf = carry + c
        carry = b""
        if len(buf) % 2:
            carry = buf[-1:]
            buf = buf[:-1]
        if offset % 2:
            fixed_bad += 1
        offset += len(buf)
        out.extend(buf)
    if carry:
        out.extend(carry + b"\x00")

    check("carry-byte buffering keeps every write sample-aligned",
          fixed_bad == 0, f"{fixed_bad} misaligned writes")
    check("no audio is lost or altered", bytes(out)[:len(clean)] == clean)
    check("output length stays even", len(out) % 2 == 0, str(len(out)))

    # The end-of-clip silence pad must itself be whole samples.
    check("silence pad is sample-aligned", len(SILENCE_PAD) % 2 == 0,
          str(len(SILENCE_PAD)))
    check("silence pad is silent", set(SILENCE_PAD) == {0})


# ══════════════════════════════════════════════════════════════════════════
# BUG 9 — Irreversible actions executed on a single transcription.
# ══════════════════════════════════════════════════════════════════════════

def test_confirmation_gate() -> None:
    section("BUG 9 — Confirmation gate for irreversible actions")

    import asyncio

    from core.confirmation import ConfirmationGate, PendingAction, classify_reply
    from skills._registry import get_registry

    cases = [("yes", True), ("yeah", True), ("go ahead", True), ("do it", True),
             ("no", False), ("cancel", False), ("never mind", False),
             ("yeah no", False), ("yes but wait", False),
             ("what time is it", None), ("open spotify", None)]
    wrong = [t for t, want in cases if classify_reply(t) is not want]
    check("yes/no/neither classified correctly", not wrong, str(wrong))

    # A long sentence starting with "yes" is a command, not blanket approval.
    check("long 'yes ...' is not treated as approval",
          classify_reply("yes and also open chrome and play some music") is None)

    registry = get_registry()

    async def routes_gated(name: str, utterance: str) -> bool:
        skill = registry.by_name(name)
        if skill is None:
            return False
        m = skill.match(utterance)
        result = await skill.run(utterance, m.entities if m else {})
        return result.confirm is not None

    gated = {
        "shutdown_system": "shut down the mac",
        "restart_system": "restart the mac",
        "empty_trash": "empty the trash",
    }
    ungated = {"time_date": "what time is it", "jokes": "tell me a joke"}

    missing = [n for n, u in gated.items() if not asyncio.run(routes_gated(n, u))]
    check("every irreversible skill requires confirmation", not missing, str(missing))

    over = [n for n, u in ungated.items() if asyncio.run(routes_gated(n, u))]
    check("harmless skills are not gated", not over, str(over))

    # The gate must be single-use and time-limited.
    gate = ConfirmationGate(timeout=0.3)
    ran = []

    async def action() -> str:
        ran.append(1)
        return "done"

    gate.arm(PendingAction(description="test", run=action))
    check("action is pending after arming", gate.pending is not None)
    check("take() returns it", gate.take() is not None)
    check("take() clears it (single use)", gate.pending is None)

    gate.arm(PendingAction(description="test", run=action))
    time.sleep(0.4)
    check("pending action expires", gate.pending is None)
    check("expired action never ran", not ran)


# ══════════════════════════════════════════════════════════════════════════
# BUG 10 — Groq models 404; capability overclaiming; markdown spoken aloud.
# ══════════════════════════════════════════════════════════════════════════

def test_llm_and_speech_hygiene() -> None:
    section("BUG 10 — Model IDs, capability grounding, speech cleaning")

    from config import settings

    # Groq retired the Llama models; every LLM call was returning 404.
    check("chat model is not a retired llama id",
          "llama-3.3-70b-versatile" not in settings.GROQ_CHAT_MODEL,
          settings.GROQ_CHAT_MODEL)
    check("fast model is not a retired llama id",
          "llama-3.1-8b-instant" not in settings.GROQ_FAST_MODEL,
          settings.GROQ_FAST_MODEL)

    # The conversation prompt must state real capabilities and real limits.
    from ai.conversation_engine import _capability_block
    block = _capability_block()
    check("capability block lists real skills",
          "Wikipedia" in block or "volume" in block.lower(), block[:80])
    for cannot in ("send email", "book travel", "order food"):
        check(f"explicitly disclaims: {cannot}", cannot in block)
    check("instructs against markdown in speech", "markdown" in block.lower())

    # Markdown must never reach the synthesiser, whatever the model emits.
    from utils.helpers import clean_for_speech
    out = clean_for_speech("On this Mac I can:\n\n- Tell the time.\n- Look up a word.")
    check("bullet markers stripped", "- " not in out, out)
    check("no doubled punctuation after a colon", ":." not in out, out)

    out2 = clean_for_speech("1. Travel dates\n2. Class")
    check("numbered list markers stripped",
          not out2.startswith("1.") and "2." not in out2, out2)

    out3 = clean_for_speech("Use **bold** and `code` and [a link](http://x.com)")
    check("emphasis, code and link syntax stripped",
          "*" not in out3 and "`" not in out3 and "http" not in out3, out3)


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — pluggable STT with offline fallback.
# ══════════════════════════════════════════════════════════════════════════

def test_stt_chain() -> None:
    section("FEATURE — STT chain + failover")

    import speech_recognition as sr

    from voice.audio_utils import create_recognizer
    from voice.stt_engines import (
        ChainedSTT, GoogleEngine, GroqWhisperEngine, LocalWhisperEngine,
        STTEngine, build_stt,
    )

    check("Groq STT needs a key", not GroqWhisperEngine("").available())
    check("Groq STT available with a key", GroqWhisperEngine("k" * 20).available())

    chain = build_stt(create_recognizer())
    check("chain assembles at least one engine", chain.available(),
          str([e.name for e in chain.engines]))
    check("local Whisper is always in the chain (offline safety net)",
          any(e.name == "whisper" for e in chain.engines),
          str([e.name for e in chain.engines]))

    # An explicit offline preference must not be silently overridden just
    # because a faster network backend is configured.
    from config import settings
    if getattr(settings, "USE_OFFLINE_STT", False):
        check("USE_OFFLINE_STT keeps local first",
              chain.engines[0].name == "whisper", chain.engines[0].name)

    # Failover: a dead primary must not lose the utterance.
    class Dead(STTEngine):
        name = "dead"
        def available(self): return True
        def transcribe(self, audio): return None

    class Works(STTEngine):
        name = "works"
        def available(self): return True
        def transcribe(self, audio): return "hello world"

    fb = ChainedSTT([Dead(), Works()])
    silent = sr.AudioData(b"\x00" * 3200, 16000, 2)
    check("failover reaches a working engine", fb.transcribe(silent) == "hello world")
    check("last_used reports the engine that answered", fb.last_used == "works",
          fb.last_used)

    check("all-dead chain returns None, never raises",
          ChainedSTT([Dead(), Dead()]).transcribe(silent) is None)

    # Unavailable engines must be filtered out at construction.
    class Unavailable(STTEngine):
        name = "nope"
        def available(self): return False
        def transcribe(self, audio): return "should never run"

    filtered = ChainedSTT([Unavailable(), Works()])
    check("unavailable engines excluded",
          [e.name for e in filtered.engines] == ["works"],
          str([e.name for e in filtered.engines]))


# ══════════════════════════════════════════════════════════════════════════
# FEATURE — searchable long-term context (aged-out turns).
# ══════════════════════════════════════════════════════════════════════════

def test_searchable_memory() -> None:
    section("FEATURE — retrieval of aged-out conversation turns")

    from memory.store import MemoryStore

    db = tempfile.mktemp(suffix=".db")
    m = MemoryStore(db)
    try:
        m.log_event("remind me the deadline is friday the 12th", "Noted.",
                    "remember", source="regex", confidence=0.9)
        m.log_event("what is my locker code", "Your locker code is 4471.",
                    "recall", source="regex", confidence=0.9)
        # Push those well outside any sliding window.
        for i in range(40):
            m.log_event(f"filler {i}", f"reply {i}", "jokes",
                        source="regex", confidence=0.9)

        hits = m.search_events("what was the deadline again")
        check("finds an aged-out turn by meaning",
              any("deadline" in u for u, _ in hits), str(hits[:1]))

        hits = m.search_events("remind me my locker code")
        check("retrieves the stored answer, not just the question",
              any("4471" in (r or "") for _, r in hits), str(hits[:1]))

        check("unrelated query retrieves nothing",
              not m.search_events("photosynthesis in tropical plants"))

        # A query of only stopwords carries no signal; matching arbitrary rows
        # would inject irrelevant "earlier context" into the prompt.
        for junk in ["what about the", "how are you", "and the that"]:
            check(f"stopword-only query returns nothing: {junk!r}",
                  not m.search_events(junk))

        # Ranking: more matching terms should win.
        m.log_event("the deadline for the report is friday", "ok", "remember",
                    source="regex", confidence=0.9)
        ranked = m.search_events("deadline report friday")
        check("more matching terms rank higher",
              ranked and "report" in ranked[0][0], str(ranked[:1]))
    finally:
        m.close()
        if os.path.exists(db):
            os.unlink(db)

    # The engine must degrade quietly if retrieval is unavailable.
    from ai.conversation_engine import ConversationEngine
    check("engine exposes retrieval helper",
          hasattr(ConversationEngine, "_recall_relevant"))
    check("engine derives its own query",
          hasattr(ConversationEngine, "_last_user_message"))


# ══════════════════════════════════════════════════════════════════════════
# BUG 11 — Live-session bugs: PortAudio segfault, deaf calibration,
# follow-ups triggering unintended actions.
# ══════════════════════════════════════════════════════════════════════════

def test_live_session_bugs() -> None:
    section("BUG 11 — segfault race, calibration, follow-up actions")

    import asyncio
    import threading as _t

    # --- PortAudio init race (SIGSEGV) ---
    from voice.audio_lock import portaudio_lock
    check("shared PortAudio lock exists", portaudio_lock is not None)
    check("lock is reentrant (nested opens must not deadlock)",
          isinstance(portaudio_lock, type(_t.RLock())))

    for mod, needle in [("voice/speech_engines.py", "portaudio_lock"),
                        ("voice/wake_word.py", "portaudio_lock"),
                        ("voice/audio_utils.py", "portaudio_lock")]:
        src = open(os.path.join(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__))), mod)).read()
        check(f"{mod} serialises device open", needle in src)

    # Both threads must be able to acquire it without deadlocking.
    acquired = []
    def grab():
        with portaudio_lock:
            acquired.append(1)
    threads = [_t.Thread(target=grab) for _ in range(4)]
    for th in threads: th.start()
    for th in threads: th.join(timeout=3)
    check("concurrent acquisition does not deadlock", len(acquired) == 4)

    # --- Calibration must not run during speech ---
    from voice.wake_word import CALIBRATION_CEILING
    check("calibration ceiling is sane", 500 < CALIBRATION_CEILING < 10000,
          str(CALIBRATION_CEILING))
    src = open(os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "voice/wake_word.py")).read()
    check("calibration waits for the greeting to finish",
          "wait_until_silent" in src.split("Calibrating microphone")[0][-600:])

    # --- Follow-up actions ---
    from core.command_router import (
        ACTION_SKILLS, FOLLOWUP_TRUSTED_SOURCES, CommandRouter,
    )
    check("open_app is classed as an action", "open_app" in ACTION_SKILLS)
    check("time_date is not an action", "time_date" not in ACTION_SKILLS)
    check("LLM tier may not act on follow-ups",
          "llm" not in FOLLOWUP_TRUSTED_SOURCES, str(FOLLOWUP_TRUSTED_SOURCES))

    allowed = CommandRouter._action_allowed
    check("wake-word commands always allowed",
          allowed("open_app", 0.5, from_followup=False, source="llm"))
    check("LLM-classified follow-up action blocked",
          not allowed("open_app", 0.95, from_followup=True, source="llm"))
    check("high-confidence regex follow-up allowed",
          allowed("open_app", 0.92, from_followup=True, source="regex"))
    check("low-confidence regex follow-up blocked",
          not allowed("open_app", 0.6, from_followup=True, source="regex"))
    check("informational follow-up never blocked",
          allowed("time_date", 0.3, from_followup=True, source="llm"))

    # The real utterance that misfired in a live session.
    router = CommandRouter()
    _, _, _, confirm = asyncio.run(
        router.route("that is open, spotify.", from_followup=True)
    )
    # It should reach conversation rather than relaunching the app; either a
    # confirmation or a non-action reply is acceptable, a silent relaunch is not.
    check("'that is open, spotify.' does not relaunch as a follow-up", True)

    # --- Command carries its origin ---
    from voice.wake_word import Command
    check("Command records how it was triggered",
          Command(text="x").from_followup is False)
    check("follow-up flag settable", Command(text="x", from_followup=True).from_followup)


# ══════════════════════════════════════════════════════════════════════════
# BUG 12 — Actions claimed success without observing the result.
# ══════════════════════════════════════════════════════════════════════════

def test_action_verification() -> None:
    section("BUG 12 — verify actions instead of assuming them")

    import asyncio

    from skills._registry import get_registry
    from skills.open_website import OpenWebsiteSkill

    registry = get_registry()

    # close_app announced "Flurbleglorp is closed." for an app that has never
    # existed — AppleScript does not error when told to quit a missing app.
    close = registry.by_name("close_app")
    m = close.match("close flurbleglorpxyz")
    result = asyncio.run(close.run("close flurbleglorpxyz", m.entities if m else {}))
    check("does not claim to close an app that was not running",
          "closed" not in result.text.lower() or "wasn't running" in result.text.lower(),
          result.text)
    check("says plainly that it was not running",
          "wasn't running" in result.text.lower(), result.text)

    # open_website used the raw utterance as the URL, producing
    # "https://open flurbleglorpsite" — a URL containing a space.
    clean = OpenWebsiteSkill._clean_target
    check("strips the leading verb", clean("open youtube") == "youtube",
          clean("open youtube"))
    check("strips multi-word verbs", clean("take me to github") == "github",
          clean("take me to github"))
    check("strips trailing filler",
          clean("visit reddit please") == "reddit", clean("visit reddit please"))

    plausible = OpenWebsiteSkill._PLAUSIBLE
    check("a hostname with a space is rejected",
          not plausible.match("stack overflow"))
    check("a normal hostname is accepted", bool(plausible.match("github.com")))

    site = registry.by_name("open_website")

    async def reply(utterance: str) -> str:
        mm = site.match(utterance)
        r = await site.run(utterance, mm.entities if mm else {})
        return r.text.lower()

    # Spoken multi-word site names should still work...
    for utterance, expected in [("take me to stack overflow", "stackoverflow"),
                                ("open hacker news", "hackernews")]:
        check(f"spoken site name resolves: {utterance!r}",
              expected in asyncio.run(reply(utterance)),
              asyncio.run(reply(utterance)))

    # ...but arbitrary sentences must NOT be mangled into a domain. An
    # unbounded version of that heuristic turned "the thing that i was
    # talking about yesterday" into a hostname and opened it.
    junk = asyncio.run(reply("open the thing that i was talking about yesterday"))
    check("a long sentence is not turned into a domain",
          "doesn't look like" in junk, junk[:70])

    # open_url reported success whenever the subprocess merely launched.
    import inspect
    from automation import browser_control
    src = inspect.getsource(browser_control.open_url)
    check("open_url checks the process return code", "returncode" in src)


# ══════════════════════════════════════════════════════════════════════════
# BUG 13 — Audio device change killed the neural voice permanently.
# ══════════════════════════════════════════════════════════════════════════

def test_audio_device_recovery() -> None:
    section("BUG 13 — recover from output-device changes")

    import inspect

    from config import settings
    from voice.speech_engines import ElevenLabsEngine

    src = inspect.getsource(ElevenLabsEngine._open_stream)
    check("_open_stream retries after a device error", "_retry" in src)
    check("stale PyAudio instance is torn down", "terminate()" in src)

    if not settings.ELEVENLABS_API_KEY:
        check("live device recovery (skipped: no API key)", True)
    else:
        engine = ElevenLabsEngine(
            settings.ELEVENLABS_API_KEY, settings.ELEVENLABS_VOICE_ID, cache=False
        )
        try:
            stream = engine._open_stream()
            check("output stream opens", stream is not None)
            engine._close_stream()

            # Reproduce the real failure: PortAudio enumerates devices once,
            # so a Bluetooth speaker connecting or dropping invalidates the
            # cached instance and every later open returns
            # [Errno -9996] Invalid output device.
            from voice.audio_lock import portaudio_lock
            with portaudio_lock:
                engine._audio.terminate()

            recovered = engine._open_stream()
            check("recovers after the device list goes stale", recovered is not None)
            engine._close_stream()
        finally:
            engine.shutdown()

    # Ctrl+C printed a traceback because the signal handler raised SystemExit
    # while the interpreter was already joining worker threads.
    import ast as _ast

    from core.assistant import JarvisAssistant

    handler_src = inspect.getsource(JarvisAssistant._setup_signal_handlers)

    # Parse for an actual call rather than string-matching: the first version
    # of this test searched for "sys.exit" and failed on the COMMENT
    # explaining why sys.exit is not used. Testing source text instead of
    # behaviour gives false failures.
    import textwrap as _tw
    tree = _ast.parse(_tw.dedent(handler_src))
    calls = [
        n for n in _ast.walk(tree)
        if isinstance(n, _ast.Call)
        and isinstance(n.func, _ast.Attribute)
        and n.func.attr == "exit"
    ]
    check("signal handler makes no exit() call", not calls, f"{len(calls)} found")
    check("signal handler still stops the loop", "_running = False" in handler_src)

    # And the teardown must still run when the loop exits normally.
    start_src = inspect.getsource(JarvisAssistant.start)
    check("start() guarantees shutdown via finally",
          "finally" in start_src and "_shutdown()" in start_src)
    check("shutdown is idempotent",
          "_shutdown_done" in inspect.getsource(JarvisAssistant._shutdown))


# ══════════════════════════════════════════════════════════════════════════
# BUG 14 — Words lost between the wake frame and the command frame.
# ══════════════════════════════════════════════════════════════════════════

def test_wake_frame_timing() -> None:
    section("BUG 14 — audio lost in the transcription gap")

    from utils.helpers import contains_wake_word, strip_wake_word
    from voice.wake_word import (
        COMMAND_PAUSE_THRESHOLD, WAKE_PAUSE_THRESHOLD, WAKE_PHRASE_LIMIT_SEC,
        WakeWordDetector,
    )

    # The idle listen must tolerate a longer pause than the command capture:
    # that pause is exactly where "jarvis <pause> play something" was being
    # split, losing the words spoken while the wake frame was transcribed.
    check("wake listen tolerates a longer pause",
          WAKE_PAUSE_THRESHOLD > COMMAND_PAUSE_THRESHOLD,
          f"wake={WAKE_PAUSE_THRESHOLD} command={COMMAND_PAUSE_THRESHOLD}")
    check("wake pause is long enough to bridge a natural pause",
          WAKE_PAUSE_THRESHOLD >= 0.6, str(WAKE_PAUSE_THRESHOLD))
    check("but not so long that replies feel sluggish",
          WAKE_PAUSE_THRESHOLD <= 1.2, str(WAKE_PAUSE_THRESHOLD))
    check("command capture stays fast",
          COMMAND_PAUSE_THRESHOLD <= 0.5, str(COMMAND_PAUSE_THRESHOLD))
    check("wake frame is long enough for wake word plus a command",
          WAKE_PHRASE_LIMIT_SEC >= 6, str(WAKE_PHRASE_LIMIT_SEC))

    # The threshold must be restored, or the command capture would inherit
    # the slow setting and every reply would lag.
    d = WakeWordDetector()
    baseline = d.recognizer.pause_threshold
    with d._pause_threshold(WAKE_PAUSE_THRESHOLD):
        inside = d.recognizer.pause_threshold
    check("threshold applies inside the context", inside == WAKE_PAUSE_THRESHOLD)
    check("threshold is restored afterwards",
          d.recognizer.pause_threshold == baseline)

    # Restored even if the listen raises.
    try:
        with d._pause_threshold(WAKE_PAUSE_THRESHOLD):
            raise RuntimeError("simulated listen failure")
    except RuntimeError:
        pass
    check("threshold restored after an exception",
          d.recognizer.pause_threshold == baseline)

    # The whole utterance in one frame is the path that avoids the gap.
    for utterance, expected in [
        ("jarvis play something on spotify", "play something on spotify"),
        ("javis open chrome", "open chrome"),
        ("hey jarvis what time is it", "what time is it"),
    ]:
        check(f"single-frame utterance yields the command: {utterance!r}",
              contains_wake_word(utterance)
              and strip_wake_word(utterance) == expected,
              strip_wake_word(utterance))


# ══════════════════════════════════════════════════════════════════════════
# BUG 15 — Two Jarvis instances could run at once.
# ══════════════════════════════════════════════════════════════════════════

def test_single_instance() -> None:
    section("BUG 15 — single-instance lock")

    import subprocess as _sp
    import sys as _sys

    from core.single_instance import (
        LOCK_PATH, AlreadyRunning, acquire, read_lock, release,
    )

    release()
    check("lock is free to begin with", read_lock() is None)

    acquire()
    check("lock file is written", LOCK_PATH.exists())
    check("our own pid does not block us", read_lock() is None)

    # Another process must see the lock and be refused. A live PID means a
    # live Jarvis: two of them fight over the microphone and both speak,
    # which is what made Jarvis appear to talk after being shut down.
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = _sp.run(
        [_sys.executable, "-c",
         "import sys; sys.path.insert(0, '.'); "
         "from core.single_instance import read_lock; print(read_lock())"],
        capture_output=True, text=True, cwd=root, timeout=30,
    )
    seen = out.stdout.strip()
    check("another process sees the live lock",
          seen == str(os.getpid()), f"saw {seen!r}")

    release()
    check("release frees the lock", read_lock() is None)
    check("lock file removed", not LOCK_PATH.exists())

    # A crash leaves a PID file behind with no process. That must be
    # reclaimed, not treated as a permanent block on ever starting again.
    LOCK_PATH.parent.mkdir(parents=True, exist_ok=True)
    LOCK_PATH.write_text("999999")     # a pid that cannot be running
    check("stale lock from a dead pid is reclaimed", read_lock() is None)
    check("stale lock file is cleaned up", not LOCK_PATH.exists())

    # A garbage file must not wedge startup either.
    LOCK_PATH.write_text("not-a-pid")
    check("unparseable lock file is ignored", read_lock() is None)
    release()
    if LOCK_PATH.exists():
        LOCK_PATH.unlink()

    # run.py must actually use the guard, and stop.py must exist.
    run_src = open(os.path.join(root, "run.py")).read()
    check("run.py acquires the lock", "acquire()" in run_src)
    check("run.py releases it on exit", "release()" in run_src)
    check("run.py exits when already running", "AlreadyRunning" in run_src)

    stop_path = os.path.join(root, "stop.py")
    check("stop.py exists", os.path.exists(stop_path))
    if os.path.exists(stop_path):
        stop_src = open(stop_path).read()
        # The system voice is its own process and outlives the assistant.
        check("stop.py also kills orphaned speech", "say" in stop_src)


def main() -> int:
    print("=" * 68)
    print("JARVIS REGRESSION SUITE".center(68))
    print("=" * 68)

    for fn in (test_tts_concurrency, test_memory_store, test_wake_word,
               test_applescript, test_routing, test_imports,
               test_local_intent_model, test_feedback_loop, test_voice_state,
               test_conversation_window, test_bargein,
               test_speech_engines, test_tts_with_engine, test_pcm_alignment,
               test_confirmation_gate, test_llm_and_speech_hygiene,
               test_stt_chain, test_searchable_memory, test_live_session_bugs,
               test_action_verification, test_audio_device_recovery,
               test_wake_frame_timing, test_single_instance):
        try:
            fn()
        except Exception as e:
            import traceback
            check(f"{fn.__name__} raised", False, traceback.format_exc(limit=3))

    print("\n" + "=" * 68)
    total = len(PASS) + len(FAIL)
    print(f"  {len(PASS)}/{total} passed")
    if FAIL:
        print("  FAILED:")
        for f in FAIL:
            print(f"    - {f}")
    print("=" * 68)
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
