# Generated by Claudian.
"""Is this URL safe to open in Ruthish's real browser?

WHY THIS EXISTS, AND WHY IT IS NOT IN THE RESEARCH PATH
-------------------------------------------------------
The research pipeline reads pages with plain HTTP, extracts `<p>` and `<li>`
text, and hands it to an LLM. It has no credentials, fills no forms, downloads
nothing, executes nothing. A pixel-perfect fake bank login is, to that code,
some text that gets summarised and discarded. Phishing needs a human.

`open_website` is the one place JARVIS puts a URL in front of a human who has
credentials. That is where a phishing check belongs, and nowhere else.

WHAT THIS IS NOT
----------------
Not a proof. "Is this site legitimate?" is an empirical question about the
world, not a theorem — there is no axiom set from which malice follows. This
gathers evidence and reports suspicion. It will have false positives, so a
flagged URL is routed to the confirmation gate rather than blocked: JARVIS
asks, Ruthish decides. Blocking outright on a heuristic would be worse than
useless the first time it refused a real site.

TWO TIERS
---------
1. Local heuristics. No key, no network, no latency. Catches the structural
   tricks phishing URLs actually use — credentials in the authority, IP
   literals, punycode homoglyphs, brand names buried in a subdomain.
2. Google Safe Browsing, only if GOOGLE_SAFE_BROWSING_API_KEY is set. This is
   the same reputation data Chrome itself uses. Absent a key the module stays
   fully functional on tier 1 alone — that is the default, deliberately, so
   this needs no setup to be useful.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from urllib.parse import urlparse

from utils.logger import get_logger

logger = get_logger(__name__)

SAFE_BROWSING_TIMEOUT = 3.0

# Brands worth impersonating. A phishing URL rarely invents a name — it borrows
# one you already trust and moves it somewhere it does not belong.
_BRANDS = (
    "paypal", "apple", "icloud", "google", "gmail", "microsoft", "outlook",
    "office365", "amazon", "netflix", "facebook", "instagram", "whatsapp",
    "linkedin", "github", "dropbox", "coinbase", "binance", "metamask",
    "chase", "wellsfargo", "hdfc", "icici", "sbi", "axisbank", "paytm",
    "phonepe", "aadhaar", "irctc",
)

# TLDs that are cheap, bulk-registered, and wildly over-represented in abuse
# feeds. Presence alone is weak evidence, so it never flags on its own.
_RISKY_TLDS = {
    "zip", "mov", "xyz", "top", "click", "link", "gq", "cf", "ml", "tk", "ga",
    "work", "fit", "rest", "country", "kim", "loan", "download", "review",
}

_IPV4 = re.compile(r"^\d{1,3}(?:\.\d{1,3}){3}$")

# Digit-for-letter swaps: paypa1, g00gle, micr0soft.
_LEETS = str.maketrans({"0": "o", "1": "l", "3": "e", "4": "a", "5": "s", "7": "t"})


@dataclass
class Verdict:
    """`suspicious` drives behaviour; `reasons` is spoken back to the user."""

    suspicious: bool
    reasons: list[str]
    checked_reputation: bool = False

    @property
    def summary(self) -> str:
        return "; ".join(self.reasons)


def _registrable(host: str) -> str:
    """Rough eTLD+1. Good enough to ask 'is the brand in the real domain or
    merely somewhere in the name', which is the only question asked of it."""
    parts = host.split(".")
    return ".".join(parts[-2:]) if len(parts) >= 2 else host


def _heuristics(url: str) -> list[str]:
    reasons: list[str] = []
    parsed = urlparse(url if "://" in url else f"https://{url}")
    host = (parsed.hostname or "").lower().strip(".")
    if not host:
        return ["that address has no hostname"]

    # Credentials in the authority. "https://apple.com@evil.ru/" reads as Apple
    # to a human and resolves to evil.ru. There is no honest use of this.
    if "@" in (parsed.netloc or ""):
        reasons.append("the address hides its real destination behind an @ sign")

    # A raw IP for a consumer site. Legitimate brands use names.
    if _IPV4.match(host) or ":" in host:
        reasons.append("it points at a raw IP address instead of a domain name")

    # Punycode. Renders as Cyrillic/Greek lookalikes: аpple.com is not apple.com.
    if "xn--" in host:
        reasons.append("the domain uses lookalike foreign characters")

    labels = host.split(".")
    registrable = _registrable(host)
    deleeted = host.translate(_LEETS)

    for brand in _BRANDS:
        in_real_domain = brand in registrable
        if in_real_domain:
            break
        # Brand present, but not in the part that decides where you actually go.
        if brand in host:
            reasons.append(
                f"it puts '{brand}' in the subdomain while the real site is "
                f"'{registrable}'")
            break
        if brand in deleeted and brand not in host:
            reasons.append(
                f"the domain looks like '{brand}' with digits swapped in")
            break

    if len(labels) >= 5:
        reasons.append("the address is buried under an unusual number of subdomains")

    tld = labels[-1] if len(labels) > 1 else ""
    # Never on its own — plenty of harmless sites use these.
    if tld in _RISKY_TLDS and reasons:
        reasons.append(f"and it sits on a '.{tld}' domain")

    if parsed.scheme == "http" and any(
            w in url.lower() for w in ("login", "signin", "verify", "account",
                                       "password", "secure", "update")):
        reasons.append("it asks for sign-in details over an unencrypted connection")

    return reasons


def _safe_browsing(url: str) -> tuple[bool, bool]:
    """(flagged, actually_checked). Never raises — a reputation service being
    down must not stop Ruthish opening a website."""
    key = os.getenv("GOOGLE_SAFE_BROWSING_API_KEY", "").strip()
    if not key:
        return False, False
    try:
        import requests

        r = requests.post(
            "https://safebrowsing.googleapis.com/v4/threatMatches:find",
            params={"key": key},
            json={
                "client": {"clientId": "jarvis", "clientVersion": "1.0"},
                "threatInfo": {
                    "threatTypes": ["MALWARE", "SOCIAL_ENGINEERING",
                                    "UNWANTED_SOFTWARE", "POTENTIALLY_HARMFUL_APPLICATION"],
                    "platformTypes": ["ANY_PLATFORM"],
                    "threatEntryTypes": ["URL"],
                    "threatEntries": [{"url": url}],
                },
            },
            timeout=SAFE_BROWSING_TIMEOUT,
        )
        if r.status_code != 200:
            logger.debug(f"Safe Browsing returned {r.status_code}")
            return False, False
        return bool(r.json().get("matches")), True
    except Exception as e:
        logger.debug(f"Safe Browsing check skipped: {e}")
        return False, False


def check(url: str) -> Verdict:
    """Evidence, not proof. Suspicion routes to confirmation, never to a block."""
    reasons = _heuristics(url)
    flagged, checked = _safe_browsing(url)
    if flagged:
        # Reputation data beats every heuristic here, so it leads.
        reasons.insert(0, "Google Safe Browsing lists this site as dangerous")
    if reasons:
        logger.warning(f"Suspicious URL {url!r}: {'; '.join(reasons)}")
    return Verdict(suspicious=bool(reasons), reasons=reasons,
                   checked_reputation=checked)
