# Generated by Claudian.
"""Jarvis CLI — talk to Jarvis without saying anything out loud.

Run via:
    python3 -m cli ask "what time is it"
    python3 -m cli status
    python3 -m cli skills
    python3 -m cli memory list
    python3 -m cli memory add "my birthday is October 12"
    python3 -m cli memory recall "birthday"
    python3 -m cli doctor

Or with the bundled wrapper script:
    ./scripts/jarvis ask "what time is it"

The CLI re-uses the SAME skills + memory + router as the voice loop, so
"jarvis ask 'what's my battery'" goes through the exact pipeline as if
you'd said it out loud — minus the wake word / TTS.
"""
