# Generated by Claudian.
"""Prevents more than one Jarvis running at a time.

WHY
---
Nothing stopped `python3 run.py` being started twice, and it happened
routinely — a terminal launch plus the desktop app's Initialize button, which
spawns detached. A session log showed two starts five seconds apart, then
`focus_guardian` firing in pairs 2-3 seconds apart for the rest of the
session: two schedulers, two microphone listeners competing for the same
device, two TTS engines both speaking.

The visible symptom was Jarvis still talking after being shut down. It was
not a ghost — killing one process left the other running, and the survivor
kept firing its proactive agents.

HOW
---
A PID file. On startup, if it names a process that is still alive, refuse to
start. Stale files — left by a crash or a SIGKILL, where no cleanup could
run — are detected by checking whether that PID actually exists, and are
reclaimed rather than blocking startup forever.

`os.kill(pid, 0)` sends no signal; it only tests whether the process exists
and is signalable. That is the standard liveness check and costs nothing.
"""

from __future__ import annotations

import os
from pathlib import Path

from utils.logger import get_logger

logger = get_logger(__name__)

LOCK_PATH = Path(__file__).parent.parent / "data" / "jarvis.pid"


class AlreadyRunning(RuntimeError):
    """Raised when another Jarvis instance holds the lock."""

    def __init__(self, pid: int):
        self.pid = pid
        super().__init__(f"Jarvis is already running (pid {pid})")


def _process_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        # Exists but owned by another user — still counts as alive.
        return True
    except Exception:
        return False
    return True


def read_lock() -> int | None:
    """PID of the running instance, or None if free/stale."""
    try:
        if not LOCK_PATH.exists():
            return None
        pid = int(LOCK_PATH.read_text().strip())
    except Exception:
        return None

    if pid == os.getpid():
        return None
    if not _process_alive(pid):
        # The owner is provably gone, so remove the file outright.
        # release() deliberately refuses to delete a lock it does not own —
        # that guard exists so a new instance's lock is never deleted by an
        # older one shutting down — but it is the wrong rule here, where we
        # have just established there is no owner.
        logger.info(f"Removing stale lock from pid {pid}")
        _force_remove()
        return None
    return pid


def _force_remove() -> None:
    """Delete the lock file regardless of who wrote it."""
    try:
        LOCK_PATH.unlink(missing_ok=True)
    except Exception as e:
        logger.debug(f"could not remove lock: {e}")


def acquire() -> None:
    """Claim the lock, or raise AlreadyRunning."""
    existing = read_lock()
    if existing is not None:
        raise AlreadyRunning(existing)

    LOCK_PATH.parent.mkdir(parents=True, exist_ok=True)
    LOCK_PATH.write_text(str(os.getpid()))
    logger.info(f"Instance lock acquired (pid {os.getpid()})")


def release() -> None:
    """Drop the lock. Safe to call when not held."""
    try:
        if LOCK_PATH.exists():
            # Only remove our own lock — a crashed predecessor's file may
            # already have been reclaimed by a newer instance.
            try:
                owner = int(LOCK_PATH.read_text().strip())
            except Exception:
                owner = os.getpid()
            if owner in (os.getpid(), 0):
                LOCK_PATH.unlink()
    except Exception as e:
        logger.debug(f"lock release failed: {e}")
