# Generated by Claudian.
"""Publishes what Jarvis is doing right now, for the desktop HUD.

The arc reactor in the Electron app previously only knew whether the process
was alive — so it sat in the same idle animation whether you were mid-sentence
or nothing was happening. This gives it the real state.

TRANSPORT
---------
A single small JSON file, polled by the Electron main process. Deliberately
not a socket or HTTP server: the assistant must never fail to start, or hang
on shutdown, because a UI that may not even be running couldn't be reached.
A file has no connection lifecycle, no port conflicts, and if the UI is
closed the writes are simply ignored.

Writes are atomic (temp file + os.replace) so the UI can never observe a
half-written file and crash its JSON parse.

Publishing is best-effort: any failure is swallowed and logged at debug.
Nothing about the voice pipeline should break because a status file couldn't
be written.
"""

from __future__ import annotations

import json
import os
import tempfile
import threading
import time
from pathlib import Path

from utils.logger import get_logger

logger = get_logger(__name__)

STATE_PATH = Path(__file__).parent.parent / "data" / "state.json"

# Recognised states, in rough pipeline order.
OFFLINE = "offline"      # process not running (written by the UI, not here)
IDLE = "idle"            # up, waiting for the wake word
LISTENING = "listening"  # wake word heard, capturing the command
THINKING = "thinking"    # routing / executing
SPEAKING = "speaking"    # TTS playing
ERROR = "error"

_lock = threading.Lock()
_current = IDLE
_last_command = ""
_last_reply = ""


def _write(payload: dict) -> None:
    try:
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        # Write to a sibling temp file then atomically replace, so a reader
        # never sees a partial document.
        fd, tmp = tempfile.mkstemp(dir=str(STATE_PATH.parent), suffix=".tmp")
        try:
            with os.fdopen(fd, "w") as f:
                json.dump(payload, f)
            os.replace(tmp, STATE_PATH)
        except Exception:
            if os.path.exists(tmp):
                os.unlink(tmp)
            raise
    except Exception as e:
        logger.debug(f"voice_state write failed: {e}")


def set_state(state: str, command: str | None = None,
              reply: str | None = None) -> None:
    """Publish the current state. Safe to call from any thread."""
    global _current, _last_command, _last_reply
    with _lock:
        _current = state
        if command is not None:
            _last_command = command
        if reply is not None:
            _last_reply = reply
        payload = {
            "state": _current,
            "last_command": _last_command,
            "last_reply": _last_reply[:200],
            "updated_at": time.time(),
        }
    _write(payload)


def get_state() -> str:
    with _lock:
        return _current


def clear() -> None:
    """Mark the assistant as stopped. Called on shutdown."""
    set_state(OFFLINE)
