# Generated by Claudian.
"""Skills package — one capability per file, auto-registered at import time.

Each skill subclasses `Skill` (see `skills/_base.py`) and provides:
  • a `name`          — unique identifier, used by the LLM fallback to address it
  • a `priority`      — lower number = checked first; specific skills before generic
  • a `match(text)`   — returns a `SkillMatch(confidence, entities)` or None
  • a `run(text, entities)` — coroutine that returns a `SkillResult`

The `SkillRegistry` (see `_registry.py`) auto-discovers every non-underscore-
prefixed .py file in this directory and instantiates the single `Skill`
subclass it finds.  Adding a new capability = drop a new file in here.
"""
