# Generated by Claudian.
"""Skill auto-discovery + matching.

On first access, the registry walks `skills/*.py` (excluding underscore-
prefixed files), imports each module, finds the single `Skill` subclass
inside, and instantiates it.  The result is a priority-sorted list
(`priority` ascending).

Public API:

    registry = get_registry()
    registry.match(text)     -> (skill | None, SkillMatch | None)
    registry.by_name(name)   -> skill | None
    registry.all_skills()    -> list[Skill]
    registry.describe_for_llm() -> str   (for the LLM fallback prompt)
"""

from __future__ import annotations

import importlib
import pkgutil
from typing import Optional

import skills  # the package itself — used for walk_packages
from skills._base import HIGH_CONFIDENCE_THRESHOLD, Skill, SkillMatch
from utils.logger import get_logger

logger = get_logger(__name__)


class SkillRegistry:
    def __init__(self, skills_list: list[Skill]):
        # Sort so lower-priority (= more specific) skills run first
        self._skills = sorted(skills_list, key=lambda s: s.priority)
        self._by_name = {s.name: s for s in self._skills}

    # ── Lookup ───────────────────────────────────────────────────────────────

    def by_name(self, name: str) -> Optional[Skill]:
        return self._by_name.get(name)

    def all_skills(self) -> list[Skill]:
        return list(self._skills)

    # ── Matching ─────────────────────────────────────────────────────────────

    def match(self, text: str) -> tuple[Optional[Skill], Optional[SkillMatch]]:
        """Run every skill's `.match()` and return the highest-confidence
        winner.  On ties, the lower-priority skill wins (already sorted)."""
        best_skill: Optional[Skill] = None
        best_match: Optional[SkillMatch] = None
        for skill in self._skills:
            try:
                result = skill.match(text)
            except Exception as e:
                logger.error(f"Skill {skill.name} match() raised: {e}")
                continue
            if result is None:
                continue
            if best_match is None or result.confidence > best_match.confidence:
                best_skill = skill
                best_match = result
                # Short-circuit on certain wins — no need to keep scanning
                if result.confidence >= 0.99:
                    break
        return best_skill, best_match

    # ── Utilities ────────────────────────────────────────────────────────────

    def is_high_confidence(self, match: Optional[SkillMatch]) -> bool:
        return match is not None and match.confidence >= HIGH_CONFIDENCE_THRESHOLD

    def describe_for_llm(self) -> str:
        """List of `name: description` lines — fed to the LLM fallback
        classifier so it knows which skill names are valid."""
        return "\n".join(f"- {s.describe_for_llm()}" for s in self._skills)


# ── Auto-discovery ───────────────────────────────────────────────────────────

_singleton: Optional[SkillRegistry] = None


def _discover_skills() -> list[Skill]:
    """Import every non-underscore module in `skills/` and collect the single
    `Skill` subclass from each."""
    found: list[Skill] = []
    for _, mod_name, is_pkg in pkgutil.iter_modules(skills.__path__):
        if is_pkg or mod_name.startswith("_"):
            continue
        full = f"skills.{mod_name}"
        try:
            module = importlib.import_module(full)
        except Exception as e:
            logger.error(f"Skill import failed — {full}: {e}")
            continue

        skill_classes = [
            obj for obj in vars(module).values()
            if isinstance(obj, type)
            and issubclass(obj, Skill)
            and obj is not Skill
            and obj.__module__ == full   # ignore re-imports
        ]
        if not skill_classes:
            logger.warning(f"{full} has no Skill subclass — ignored")
            continue
        if len(skill_classes) > 1:
            logger.warning(
                f"{full} declares {len(skill_classes)} Skill subclasses — using "
                f"{skill_classes[0].__name__}"
            )
        try:
            found.append(skill_classes[0]())
        except Exception as e:
            logger.error(f"Skill instantiation failed — {full}: {e}")
    return found


def get_registry() -> SkillRegistry:
    global _singleton
    if _singleton is None:
        loaded = _discover_skills()
        logger.info(
            f"Skills loaded: {len(loaded)} "
            f"({', '.join(s.name for s in sorted(loaded, key=lambda x: x.priority))})"
        )
        _singleton = SkillRegistry(loaded)
    return _singleton


def reset_registry_for_tests():
    """Testing helper — force re-discovery on next `get_registry()` call."""
    global _singleton
    _singleton = None
