# Generated by Claudian.
"""Skill: report battery percentage + charging state."""

import re

from ai.response_generator import ResponseGenerator
from automation.system_control import get_battery
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

_PATTERN = re.compile(r"battery|charge\s+level|how\s+much\s+(battery|charge)")


class BatterySkill(Skill):
    name = "battery"
    description = "Report battery percentage and charging state"
    priority = 15

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        if _PATTERN.search(text.lower()):
            return SkillMatch(confidence=0.95)
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        info = await run_in_thread(get_battery)
        return SkillResult(
            text=self._responses.battery_response(info["percent"], info["charging"])
        )
