# Generated by Claudian.
"""Skill: change screen brightness (level or up/down)."""

import re

from ai.response_generator import ResponseGenerator
from automation.system_control import set_brightness
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult


def _clamp(v: int) -> int:
    return max(0, min(100, v))


class BrightnessSkill(Skill):
    name = "brightness"
    description = "Change screen brightness (to a specific level, or up/down)"
    priority = 15

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()
        if "brightness" not in low and "dim" not in low:
            return None

        m = re.search(r"brightness\s+(?:to\s+)?(\d{1,3})", low)
        if m:
            return SkillMatch(confidence=0.95, entities={"level": _clamp(int(m.group(1)))})

        if re.search(
            r"(brightness)\s+(up|higher|brighter)"
            r"|(raise|increase|turn\s+up)\s+(the\s+)?brightness",
            low,
        ):
            return SkillMatch(confidence=0.9, entities={"action": "up"})
        if re.search(
            r"(brightness)\s+(down|lower|dimmer)"
            r"|(lower|decrease|dim|turn\s+down)\s+(the\s+)?brightness",
            low,
        ):
            return SkillMatch(confidence=0.9, entities={"action": "down"})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        level = entities.get("level")
        action = entities.get("action")
        if level is None and action is None:
            action = "up" if any(w in text.lower() for w in ["up", "increase", "brighter"]) else "down"
        ok, result = await run_in_thread(set_brightness, level, action)
        if ok:
            return SkillResult(text=f"Brightness {result}.")
        return SkillResult(text=self._responses.action_failed("adjust brightness"))
