# Generated by Claudian.
"""Skill: expert programming help, powered by Groq Llama 3.3.

Answers coding questions across any language — explains concepts, writes
snippets, debugs errors, suggests best practices.

Matching is deliberately conservative.  A bare keyword like "docker" or
"git" is NOT enough; the utterance must also look like a *question* or a
*request to produce/fix code*.  This keeps commands such as
"open docker" routing to `open_app` instead of being hijacked here.
"""

from __future__ import annotations

import re

from config import settings
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)


LANGUAGES = (
    r"python|javascript|typescript|java|kotlin|swift|golang|go\b|rust|ruby|php|"
    r"c\+\+|cpp|c#|csharp|scala|haskell|lua|perl|bash|shell|sql|html|css|r\b"
)

FRAMEWORKS = (
    r"react|vue|angular|svelte|django|flask|fastapi|node|express|rails|spring|"
    r"pytorch|tensorflow|numpy|pandas|sklearn|docker|kubernetes|git\b|postgres|"
    r"mongodb|redis|graphql"
)

CONCEPTS = (
    r"async|await|promise|callback|closure|decorator|generator|lambda|recursion|"
    r"pointer|thread|mutex|regex|api|endpoint|middleware|dependency injection|"
    r"time complexity|big o|data structure|algorithm|design pattern"
)

# ── Strong signals: unambiguous coding requests (skip the LLM tie-breaker) ──
_STRONG = [
    # "how do i <verb> ... in python"
    re.compile(rf"how (?:do|would|can) (?:i|you)\b.*\b(?:{LANGUAGES}|{FRAMEWORKS})"),
    # "write/create/generate me a function|class|script|component ..."
    re.compile(
        r"(?:write|create|generate|build|show me)\s+(?:me\s+)?(?:a|an|some)?\s*"
        r"(?:function|method|class|script|snippet|component|query|regex|program)"
    ),
    # "explain closures / what is a decorator"
    re.compile(rf"(?:explain|what(?:'s| is| are))\b.*\b(?:{CONCEPTS})"),
    # debugging
    re.compile(r"(?:debug|fix|why (?:does|is|am i getting))\b.*\b(?:error|exception|bug|crash|traceback|stack trace)"),
    re.compile(r"\b(?:syntaxerror|typeerror|valueerror|nullpointer|segfault|undefined is not)"),
    # code review / refactor
    re.compile(r"(?:refactor|optimi[sz]e|review)\s+(?:this|my)\s+(?:code|function|script)"),
]

# ── Weak signals: probably coding, but let the LLM arbitrate ──
_QUESTION = re.compile(r"^(?:how|what|why|when|which|can|should|is|are|does|do)\b")
_TOPIC = re.compile(rf"\b(?:{LANGUAGES}|{FRAMEWORKS}|{CONCEPTS}|code|coding|programming|function|syntax)\b")


_SYSTEM_PROMPT = (
    "You are an expert programming assistant speaking OUT LOUD through a voice "
    "assistant. You know Python, JavaScript, TypeScript, Go, Rust, Java, C++, "
    "C#, Ruby, PHP, Swift, Kotlin and their major frameworks deeply.\n\n"
    "Because your answer is SPOKEN, not displayed:\n"
    "- Keep it under 80 words unless the question genuinely needs more.\n"
    "- Describe code in prose rather than reciting punctuation and indentation.\n"
    "- Lead with the direct answer, then one sentence of why.\n"
    "- Never use markdown, code fences, bullet points, or emoji.\n"
    "- If the user needs to see actual code, give the shape of it verbally and "
    "offer to write it to a file."
)


class CodingAssistantSkill(Skill):
    name = "coding_assistant"
    description = (
        "Answer programming questions in any language — explain concepts, "
        "write code, debug errors, suggest best practices"
    )
    # Higher than concrete system commands (so "open docker" still opens the
    # app) but lower than the conversation catch-all.
    priority = 60

    def __init__(self):
        self._groq = None  # lazy — don't pay import cost at startup

    # ── Matching ─────────────────────────────────────────────────────────────

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower().strip()

        for pat in _STRONG:
            if pat.search(low):
                return SkillMatch(confidence=0.9, entities={"question": text})

        # Question-shaped AND mentions a coding topic → likely, but let the
        # LLM tie-breaker confirm (confidence sits below the 0.85 threshold).
        if _QUESTION.search(low) and _TOPIC.search(low):
            return SkillMatch(confidence=0.8, entities={"question": text})

        return None

    # ── Execution ────────────────────────────────────────────────────────────

    async def run(self, text: str, entities: dict) -> SkillResult:
        question = entities.get("question") or text

        if not settings.has_ai():
            return SkillResult(
                "I can't reach the language model right now. "
                "Check that your Groq API key is set."
            )

        try:
            answer = await run_in_thread(self._ask, question)
        except Exception as e:
            logger.error(f"coding_assistant failed: {e}")
            return SkillResult(
                "I hit an error working that out. Try asking again, "
                "or narrow it to a specific language."
            )

        return SkillResult(text=answer)

    def _ask(self, question: str) -> str:
        """Blocking Groq call — always invoked via run_in_thread."""
        client = self._get_groq()
        response = client.chat.completions.create(
            model=settings.GROQ_CHAT_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": question},
            ],
            max_tokens=320,
            temperature=0.4,
            timeout=15.0,
        )
        answer = (response.choices[0].message.content or "").strip()
        return answer or "I couldn't come up with an answer for that one."

    def _get_groq(self):
        if self._groq is None:
            from groq import Groq
            self._groq = Groq(api_key=settings.GROQ_API_KEY)
        return self._groq
