# Generated by Claudian.
"""Skill: general conversation / Q&A fallback.

Runs when no other skill confidently matches — delegates to the Groq LLM
via `ai.conversation_engine.ConversationEngine`.  Uses the lowest priority
so every specific skill gets first crack at the utterance.
"""

from ai.conversation_engine import ConversationEngine
from ai.memory import ConversationMemory
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from voice.text_to_speech import get_tts


class ConversationSkill(Skill):
    name = "conversation"
    description = "Free-form conversation / questions / anything else"
    priority = 999  # dead last

    def __init__(self):
        # Shared with other callers of ConversationEngine — they can look
        # this instance up via `get_registry().by_name("conversation").engine`
        # if they need the same memory (e.g. the WhatsApp skill asking a
        # clarifying question).
        self._memory = ConversationMemory()
        self.engine = ConversationEngine(self._memory)
        self._tts = get_tts()

    def match(self, text: str) -> SkillMatch | None:
        # Always match, but at minimal confidence — acts as the catch-all.
        if not text.strip():
            return None
        return SkillMatch(confidence=0.05)

    async def run(self, text: str, entities: dict) -> SkillResult:
        # Stream Groq tokens → TTS sentence-by-sentence.  Time-to-first-word
        # drops from "wait for full reply" to "wait for first sentence".
        def stream_to_tts() -> str:
            return self.engine.chat_stream(text, on_sentence=self._tts.speak)

        full_reply = await run_in_thread(stream_to_tts)
        return SkillResult(text=full_reply, already_spoken=True)
