# Generated by Claudian.
"""Skill: define a word.

Ported from GauravSingh9356/J.A.R.V.I.S `diction.py`, which shipped a 4MB
local `data.json` and fuzzy-matched against it with difflib.  That approach
is frozen in time and can't define anything added to English since the file
was built, so this version calls dictionaryapi.dev instead — free, no API
key, always current — and keeps a difflib-free graceful failure path.
"""

from __future__ import annotations

import re

import requests

from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

API = "https://api.dictionaryapi.dev/api/v2/entries/en/{word}"

_PATTERNS = [
    re.compile(r"(?:what(?:'s| is) the )?(?:definition|meaning) of\s+(?:the word\s+)?([a-z\-']+)"),
    re.compile(r"define\s+(?:the word\s+)?([a-z\-']+)"),
    re.compile(r"what does\s+([a-z\-']+)\s+mean"),
    re.compile(r"(?:look up|spell out)\s+([a-z\-']+)\s+in the dictionary"),
]


class DefineWordSkill(Skill):
    name = "define_word"
    description = "Give the dictionary definition of an English word"
    # Below wikipedia_lookup so "what is a transformer" prefers Wikipedia,
    # but "define transformer" lands here.
    priority = 24

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower().strip(" ?.!")
        for pat in _PATTERNS:
            m = pat.search(low)
            if m:
                word = m.group(1).strip()
                if len(word) > 1:
                    return SkillMatch(confidence=0.94, entities={"word": word})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        word = entities.get("word", "").strip()
        if not word:
            return SkillResult("Which word should I define?")

        try:
            return SkillResult(await run_in_thread(self._define, word))
        except requests.Timeout:
            return SkillResult("The dictionary service didn't respond in time.")
        except Exception as e:
            logger.error(f"define_word failed for {word!r}: {e}")
            return SkillResult(f"I couldn't look up {word}.")

    def _define(self, word: str) -> str:
        resp = requests.get(API.format(word=word), timeout=8)

        if resp.status_code == 404:
            return f"I couldn't find a definition for {word}."
        resp.raise_for_status()

        data = resp.json()
        if not isinstance(data, list) or not data:
            return f"I couldn't find a definition for {word}."

        entry = data[0]
        meanings = entry.get("meanings") or []
        if not meanings:
            return f"I found {word}, but no definition was listed."

        first = meanings[0]
        part = first.get("partOfSpeech", "")
        defs = first.get("definitions") or []
        if not defs:
            return f"I found {word}, but no definition was listed."

        definition = defs[0].get("definition", "").strip()
        lead = f"{word}, {part}." if part else f"{word}."
        out = f"{lead} {definition}"

        example = defs[0].get("example")
        if example:
            out += f" For example: {example}"

        return out
