# Generated by Claudian.
"""Skill: tell a programming joke.

Ported from GauravSingh9356/J.A.R.V.I.S (`pyjokes.get_joke()`).  Adds a
short memory of recently-told jokes so you don't hear the same one twice
in a session, and degrades gracefully if pyjokes isn't installed.
"""

from __future__ import annotations

import random
import re
from collections import deque

from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

_PATTERNS = [
    re.compile(r"\b(?:tell|say|got|know|hit me with)\b.*\bjokes?\b"),
    re.compile(r"^jokes?$"),
    re.compile(r"\bmake me laugh\b"),
    re.compile(r"\bsomething funny\b"),
    re.compile(r"\banother one\b"),
]

_FALLBACKS = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "There are two hard things in computer science: cache invalidation, "
    "naming things, and off-by-one errors.",
    "A SQL query walks into a bar, approaches two tables, and asks: may I join you?",
]


class JokesSkill(Skill):
    name = "jokes"
    description = "Tell a programming joke"
    priority = 30

    # Remember the last few so we don't repeat within a session.
    _recent: deque[str] = deque(maxlen=12)

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower().strip()
        for pat in _PATTERNS:
            if pat.search(low):
                return SkillMatch(confidence=0.94)
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        return SkillResult(self._get_joke())

    def _get_joke(self) -> str:
        try:
            import pyjokes
        except ImportError:
            logger.warning("pyjokes not installed — using built-in fallbacks")
            return random.choice(_FALLBACKS)

        # Try a handful of times to land one we haven't told recently.
        for _ in range(8):
            joke = pyjokes.get_joke(language="en", category="neutral")
            if joke not in self._recent:
                self._recent.append(joke)
                return joke

        # Pool exhausted or unlucky — just return whatever we got.
        return pyjokes.get_joke(language="en", category="neutral")
