# Generated by Claudian.
"""Skill: lock the screen (Cmd+Ctrl+Q)."""

import re

from ai.response_generator import ResponseGenerator
from automation.system_control import lock_mac
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

_PATTERN = re.compile(r"lock\s+(the\s+)?(screen|mac|computer|laptop|display)")


class LockScreenSkill(Skill):
    name = "lock_screen"
    description = "Lock the Mac screen"
    priority = 15

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        if _PATTERN.search(text.lower()):
            return SkillMatch(confidence=0.95)
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        ok = await run_in_thread(lock_mac)
        if ok:
            return SkillResult(text="Screen locked.")
        return SkillResult(text=self._responses.action_failed("lock screen"))
