# Generated by Claudian.
"""Skill: play / pause / resume / skip music on Spotify."""

import re

from skills._base import Skill, SkillMatch, SkillResult
from multitasking.async_executor import run_in_thread


class MusicSkill(Skill):
    name = "music"
    description = "Play, pause, skip or resume music on Spotify"
    priority = 20

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()
        if not any(w in low for w in ["play", "music", "song", "track", "playlist", "pause", "next", "previous", "skip"]):
            return None

        # Playback controls
        if "pause" in low and any(w in low for w in ["music", "song", "track", "spotify"]):
            return SkillMatch(confidence=0.93, entities={"action": "pause"})
        if "resume" in low and any(w in low for w in ["music", "song", "track", "spotify"]):
            return SkillMatch(confidence=0.93, entities={"action": "resume"})
        if re.search(r"\b(next|skip)\b.*(song|track|music)", low) or re.search(
            r"(next|skip)\s+(song|track)", low
        ):
            return SkillMatch(confidence=0.93, entities={"action": "next"})
        if re.search(r"previous\s+(song|track)|last\s+song", low):
            return SkillMatch(confidence=0.93, entities={"action": "previous"})

        m = re.search(
            r"play\s+(?:some\s+)?(?:music\s+by\s+|song\s+)?(.+?)"
            r"(?:\s+(?:on|in)\s+(?:spotify|music|apple\s+music))?$",
            low,
        )
        if m:
            item = m.group(1).strip()
            if item in {"music", "some music", "something", "a song", "songs"}:
                return SkillMatch(confidence=0.9, entities={})
            return SkillMatch(confidence=0.85, entities={"song": item})

        if "play" in low:
            return SkillMatch(confidence=0.75, entities={})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        # Import here so we don't load AppleScript helpers unless needed
        from automation.music_control import (
            next_track,
            pause_spotify,
            play_spotify,
            previous_track,
            resume_spotify,
        )

        action = entities.get("action")
        if action == "pause":
            ok = await run_in_thread(pause_spotify)
            return SkillResult(text="Music paused." if ok else "Failed to pause.")
        if action == "resume":
            ok = await run_in_thread(resume_spotify)
            return SkillResult(text="Music resumed." if ok else "Failed to resume.")
        if action == "next":
            ok = await run_in_thread(next_track)
            return SkillResult(text="Skipping to next track." if ok else "Failed to skip.")
        if action == "previous":
            ok = await run_in_thread(previous_track)
            return SkillResult(text="Going to previous track." if ok else "Failed.")

        song = entities.get("song") or entities.get("artist") or ""
        ok, result = await run_in_thread(play_spotify, song)
        if ok:
            if result:
                return SkillResult(text=f"Playing {result} on Spotify.")
            return SkillResult(text="Playing music on Spotify.")
        return SkillResult(text="Failed to play music.")
