# Generated by Claudian.
"""Skill: read out the current top news headlines.

Ported from GauravSingh9356/J.A.R.V.I.S `news.py`, which hit NewsAPI with a
hardcoded `apiKey=yourapikey` placeholder — meaning it never actually worked
for anyone who cloned it, and NewsAPI's free tier is localhost-only anyway.

This version reads Google News RSS: no API key, no signup, no rate limit,
and it supports topic queries ("news about AI") for free.  Parsed with the
stdlib XML parser so we add zero new dependencies.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from urllib.parse import quote_plus

import requests

from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

TOP_URL = "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"
TOPIC_URL = "https://news.google.com/rss/search?q={q}&hl=en-IN&gl=IN&ceid=IN:en"

HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}

_TOPIC = re.compile(r"news\s+(?:about|on|regarding|for)\s+(.+)")
_GENERAL = re.compile(
    r"\b(?:news|headlines|what's happening|whats happening|"
    r"current affairs|top stories)\b"
)

# Google News titles arrive as "Headline - Publisher"; strip the publisher
# so it reads naturally out loud.
_PUBLISHER = re.compile(r"\s+-\s+[^-]{2,40}$")

MAX_HEADLINES = 5


class NewsHeadlinesSkill(Skill):
    name = "news_headlines"
    description = "Read the latest news headlines, optionally about a specific topic"
    priority = 22

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower().strip(" ?.!")

        m = _TOPIC.search(low)
        if m:
            topic = m.group(1).strip()
            if topic:
                return SkillMatch(confidence=0.94, entities={"topic": topic})

        if _GENERAL.search(low):
            return SkillMatch(confidence=0.92, entities={})

        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        topic = (entities.get("topic") or "").strip()
        try:
            headlines = await run_in_thread(self._fetch, topic)
        except requests.Timeout:
            return SkillResult("The news feed didn't respond in time.")
        except Exception as e:
            logger.error(f"news fetch failed: {e}")
            return SkillResult("I couldn't reach the news feed right now.")

        if not headlines:
            what = f" about {topic}" if topic else ""
            return SkillResult(f"I couldn't find any headlines{what}.")

        intro = f"Top headlines about {topic}." if topic else "Here are the top headlines."
        body = " ".join(f"{i}. {h}." for i, h in enumerate(headlines, 1))
        return SkillResult(f"{intro} {body}")

    def _fetch(self, topic: str) -> list[str]:
        url = TOPIC_URL.format(q=quote_plus(topic)) if topic else TOP_URL

        resp = requests.get(url, headers=HEADERS, timeout=10)
        resp.raise_for_status()

        root = ET.fromstring(resp.content)

        headlines: list[str] = []
        for item in root.iterfind(".//item"):
            title_el = item.find("title")
            if title_el is None or not title_el.text:
                continue
            title = _PUBLISHER.sub("", title_el.text).strip()
            if title:
                headlines.append(title)
            if len(headlines) >= MAX_HEADLINES:
                break

        return headlines
