# Generated by Claudian.
"""Skill: open a website in the default browser.

Priority higher (= runs earlier) than `open_app` so that "go to youtube"
opens the site rather than trying to launch a nonexistent app.
"""

import re

from utils.logger import get_logger

from automation.browser_control import open_url
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

# Explicit URL match — a literal domain or path
_URL_RE = re.compile(
    r"(?:open|go\s+to|visit|browse|navigate\s+to)\s+"
    r"((?:https?://)?(?:www\.)?[\w\-]+\.\w{2,}(?:/\S*)?)"
)

# Well-known sites — only "go to / visit / browse / navigate to" match.
# "open youtube" deliberately goes to open_app (the app) — that matches iOS/macOS UX.
_WELL_KNOWN_SITES = [
    "youtube", "netflix", "github", "gmail", "google",
    "facebook", "twitter", "instagram", "linkedin", "reddit", "twitch",
]


logger = get_logger(__name__)


def _safety_check(url: str):
    """Never let the check itself stop a website opening. If url_safety is
    broken or missing, the skill must behave exactly as it did before it
    existed — a security add-on that takes the feature down with it when it
    fails is a worse bug than the one it prevents."""
    try:
        from security.url_safety import check

        return check(url)
    except Exception as e:
        logger.debug(f"URL safety check unavailable: {e}")
        return None


class OpenWebsiteSkill(Skill):
    name = "open_website"
    description = "Open a website in the default browser"
    priority = 25  # before open_app (30)

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()
        m = _URL_RE.search(low)
        if m:
            return SkillMatch(confidence=0.95, entities={"url": m.group(1)})
        for site in _WELL_KNOWN_SITES:
            if re.search(rf"(?:go\s+to|visit|browse|navigate\s+to)\s+{site}", low):
                return SkillMatch(
                    confidence=0.93,
                    entities={"url": f"https://www.{site}.com", "site_name": site},
                )
        return None

    # Words that precede a site name but are not part of it. Without this the
    # raw utterance was used as the URL: "open flurbleglorpsite" became
    # "https://open flurbleglorpsite" — a space inside a URL — and Jarvis
    # still announced success.
    _VERB_PREFIX = re.compile(
        r"^\s*(?:please\s+)?(?:can you\s+)?"
        r"(?:open|go to|goto|visit|browse to|pull up|take me to|load|navigate to|"
        r"launch|show me)\s+", re.I
    )
    _TRAILING = re.compile(r"\s+(?:in the browser|please|for me|now)\s*$", re.I)

    # A bare word is only a plausible host if it has no spaces.
    _PLAUSIBLE = re.compile(r"^[a-z0-9][a-z0-9._~\-]*(?:\.[a-z]{2,})?(?:/\S*)?$", re.I)

    @classmethod
    def _clean_target(cls, raw: str) -> str:
        target = cls._TRAILING.sub("", cls._VERB_PREFIX.sub("", raw or "")).strip()
        return target.strip(" .,?!")

    async def run(self, text: str, entities: dict) -> SkillResult:
        raw = entities.get("url") or entities.get("site_name") or text
        target = self._clean_target(raw)

        if not target:
            return SkillResult(text="Which site would you like me to open?")

        # A complete URL (from the well-known-site map) is already valid;
        # the bare-hostname pattern below would reject it on the "://".
        already_a_url = target.lower().startswith(("http://", "https://"))

        # Speech puts spaces where domains have none: "stack overflow" is
        # said aloud but written stackoverflow.com. Collapse and retry before
        # declining, otherwise every multi-word site name gets refused.
        if not already_a_url and not self._PLAUSIBLE.match(target):
            words = target.split()
            collapsed = "".join(words)
            # Bounded deliberately. Unbounded collapsing turned "the thing
            # that i was talking about yesterday" into a domain name and
            # cheerfully opened it. Real site names spoken aloud are short:
            # "stack overflow", "hacker news", "product hunt".
            if (len(words) <= 3 and len(collapsed) <= 30
                    and self._PLAUSIBLE.match(collapsed)):
                logger.debug(f"Collapsed spoken site name {target!r} -> {collapsed!r}")
                target = collapsed

        # Verify BEFORE acting. Opening a malformed URL fails silently in the
        # browser, and announcing success for it is worse than declining.
        if not already_a_url and not self._PLAUSIBLE.match(target):
            return SkillResult(
                text=f"\"{target}\" doesn't look like a website address. "
                     "Want me to search for it instead?"
            )

        label = entities.get("site_name") or target

        async def _do() -> str:
            ok = await run_in_thread(open_url, target)
            return (f"I couldn't open {label}." if ok is False
                    else f"Opening {label}.")

        # This is the only place JARVIS puts a URL in front of a human who has
        # credentials, so it is the only place a phishing check belongs. The
        # research path reads pages with no credentials and no browser, and is
        # deliberately left alone.
        #
        # Suspicion asks rather than blocks. These are heuristics, not proof —
        # the first time a false positive refuses a real site outright, the
        # check stops being worth having.
        verdict = await run_in_thread(_safety_check, target)
        if verdict is not None and verdict.suspicious:
            from core.confirmation import PendingAction

            return SkillResult(
                text=f"That link looks unsafe — {verdict.summary}. "
                     "Open it anyway?",
                confirm=PendingAction(description=f"open {label}", run=_do),
            )

        return SkillResult(text=await _do())
