# Generated by Claudian.
"""Skill: open a macOS application by name or alias.

Handles voice-input quirks: trailing punctuation, filler words
("just open spotify for fuck sake"), and Whisper misspellings.  The heavy
cleanup lives in `automation/app_control._resolve_app_name` — here we just
extract the captured name and hand it off.
"""

import re

from ai.response_generator import ResponseGenerator
from automation.app_control import open_app
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

# "go to X" / "switch to X" / "take me to X" are how people actually ask for an
# app that is already running — and none of them matched. "go to the Obsidian
# app" fell through to the conversation engine, which announced "Opening
# Obsidian... Obsidian's up and running" without opening anything.
#
# open_website (priority 25) gets first refusal on "go to", but it only claims
# things that look like domains, so "go to obsidian" reaches here.
_PATTERN = re.compile(
    r"(?:open(?:\s+up)?|launch|start|run|go\s+to|goto|switch\s+to"
    r"|take\s+me\s+to|bring\s+up|pull\s+up|show\s+me)\s+(?:the\s+)?(.+)")

# Shared filler set — mirrors `ai.local_intent_classifier._clean_captured_app`.
# Kept in-skill so each skill file is self-contained.
_FILLER_PHRASES = [
    "for fuck sake", "for fucks sake", "for fuck's sake",
    "for god sake", "for god's sake",
    "right now", "real quick", "for me", "please",
]
_FILLER_WORDS = {"just", "please", "quickly", "now", "asap", "the", "a", "an", "my"}


def _clean_captured_app(raw: str) -> str:
    s = raw.lower().strip()
    s = re.sub(r"[\s\.\!\?\,\;\:]+$", "", s)
    for phrase in _FILLER_PHRASES:
        s = s.replace(phrase, " ")
    tokens = [t for t in re.split(r"\s+", s) if t and t not in _FILLER_WORDS]
    return " ".join(tokens).strip()


class OpenAppSkill(Skill):
    name = "open_app"
    description = "Open a macOS application by name"
    priority = 30  # runs after open_website (25)

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        m = _PATTERN.search(text.lower())
        if not m:
            return None
        app = _clean_captured_app(m.group(1))
        if not app:
            return None
        # URL-shaped captures go to open_website, not here
        if re.search(r"\.\w{2,4}(/|$)", app):
            return None
        return SkillMatch(confidence=0.92, entities={"app_name": app})

    async def run(self, text: str, entities: dict) -> SkillResult:
        app = entities.get("app_name", text)
        ok, resolved = await run_in_thread(open_app, app)
        if ok:
            return SkillResult(text=self._responses.app_opened(resolved))
        return SkillResult(text=self._responses.app_not_found(app))
