# Generated by Claudian.
"""Skill: recall facts from long-term memory.

Example utterances:
  "what do you know about aki"
  "what did i say about the haiintel interview"
  "recall anything about coffee"
  "do you remember something about my mother's birthday"
"""

import re

from memory import get_memory
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

# Patterns capture the "query" — everything after the trigger phrase
_PATTERNS = [
    re.compile(
        r"(?:what\s+(?:do\s+you\s+know|did\s+i\s+say|did\s+we\s+talk))\s+about\s+(.+)",
        re.IGNORECASE,
    ),
    re.compile(
        r"(?:recall|remind\s+me)\s+(?:anything\s+)?(?:about\s+)?(.+)",
        re.IGNORECASE,
    ),
    re.compile(
        r"(?:do\s+you\s+)?remember\s+(?:anything|something)\s+about\s+(.+)",
        re.IGNORECASE,
    ),
]


class RecallSkill(Skill):
    name = "recall"
    description = "Recall stored facts — 'what do you know about X?'"
    priority = 11

    def match(self, text: str) -> SkillMatch | None:
        low = text.strip()
        for pat in _PATTERNS:
            m = pat.match(low)
            if m:
                query = m.group(1).strip().rstrip("?.!")
                if query:
                    return SkillMatch(confidence=0.9, entities={"query": query})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        query = (entities.get("query") or "").strip()
        if not query:
            return SkillResult(text="What should I recall?")
        facts = await run_in_thread(get_memory().recall, query, 3)
        if not facts:
            return SkillResult(text=f"I don't have anything stored about {query}.")
        # One fact: say it plainly.
        if len(facts) == 1:
            return SkillResult(text=f"Here's what I have: {facts[0].text}")
        # Multiple: list the top 3.
        parts = [f"{i}. {f.text}" for i, f in enumerate(facts, 1)]
        return SkillResult(
            text=f"I found {len(facts)} things about {query}. " + " ".join(parts)
        )
