# Generated by Claudian.
"""Skill: store a fact in long-term memory.

Example utterances:
  "remember that my girlfriend is called aki"
  "remember: my interview at haiintel is on april 25 at 2 pm"
  "note to self: coffee tastes better from the moka pot"
"""

import re

from memory import get_memory
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

_TRIGGERS = re.compile(
    r"^(?:jarvis\s+)?(?:please\s+)?"
    r"(?:remember|note\s+(?:to\s+self|this|that)|save\s+this|make\s+a\s+note)"
    r"(?:\s+that)?"
    r"[\s:,-]+(.+)$",
    re.IGNORECASE,
)


class RememberSkill(Skill):
    name = "remember"
    description = "Store a fact in long-term memory — 'remember that X'"
    priority = 11

    def match(self, text: str) -> SkillMatch | None:
        m = _TRIGGERS.match(text.strip())
        if not m:
            return None
        fact = m.group(1).strip()
        if not fact:
            return None
        return SkillMatch(confidence=0.93, entities={"fact": fact})

    async def run(self, text: str, entities: dict) -> SkillResult:
        fact = (entities.get("fact") or "").strip()
        if not fact:
            return SkillResult(text="What should I remember?")
        await run_in_thread(get_memory().remember, fact)
        # Keep the confirmation short — Ruthish likes terse replies
        preview = fact if len(fact) < 80 else fact[:77] + "..."
        return SkillResult(text=f"Got it — I'll remember that. ({preview})")
