# Generated by Claudian.
"""Skill: research a topic on the web and explain it.

Replaces `wikipedia_lookup` as the default for open questions. That skill read
one Wikipedia summary aloud verbatim — one source, no cross-checking, and the
answer was whoever last edited the article.

This reads five different sites and answers in its own words. Entirely over
HTTP: no browser window opens, nothing steals focus, nothing appears on screen
while you are working.

Priority sits above `wikipedia_lookup` (65) so "what is X" comes here first,
but below `coding_assistant` (60)... deliberately not: research is slower than
every other skill, so it must not out-rank the specific ones. See below.
"""

from __future__ import annotations

import re

from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

# Explicit research requests — high confidence, this is unambiguous.
_EXPLICIT = [
    re.compile(r"(?:research|look\s+into|dig\s+into|find\s+out\s+about)\s+(.+)"),
    re.compile(r"(?:read\s+up\s+on|study)\s+(.+)"),
    re.compile(r"what\s+do(?:es)?\s+the\s+(?:web|internet)\s+say\s+about\s+(.+)"),
    re.compile(r"(?:search|google)\s+(?:and\s+)?(?:tell|explain|summari[sz]e)\s+(?:me\s+)?(?:about\s+)?(.+)"),
    re.compile(r"tell\s+me\s+(?:all\s+)?about\s+(.+)"),
]

# Open questions — lower confidence so a more specific skill can win.
_QUESTIONS = [
    re.compile(r"what\s+(?:is|are|was|were)\s+(?:a\s+|an\s+|the\s+)?(.+)"),
    re.compile(r"who\s+(?:is|are|was|were)\s+(.+)"),
    re.compile(r"how\s+(?:does|do|did)\s+(.+?)\s+work"),
    re.compile(r"why\s+(?:is|are|does|do|did)\s+(.+)"),
    re.compile(r"explain\s+(?:to\s+me\s+)?(?:about\s+)?(.+)"),
]

_TAIL = re.compile(r"\s+(?:please|jarvis|for\s+me|to\s+me)\s*$", re.I)

# Open-ended questions that parse as lookups but are not. Searching five
# websites for "the meaning of life" returns encyclopedia definitions, which
# is a worse answer than simply talking about it. `define_word` and
# `wikipedia_lookup` already carry the same guard.
_PHILOSOPHICAL = {
    "the meaning of life", "meaning of life", "the point of it all",
    "the purpose of life", "purpose of life", "the meaning of everything",
    "meaning of existence", "the meaning of it all",
}


# Questions about JARVIS itself. These parse as perfect research requests —
# "tell me about yourself" is literally "tell me about X" — but the answer is
# not on the web. Searching it returned a grammar lesson on the reflexive
# pronoun "yourself" from merriam-webster and wiktionary, which is a correct
# answer to the wrong question.
#
# Same guard as _PHILOSOPHICAL above: hand it back so the conversation engine
# answers as JARVIS, which already has the system prompt and capability block
# needed to say who it is.
_SELF_REFERENTIAL = re.compile(
    r"^(?:"
    r"your\s*self|yourself|you|u|jarvis|me"
    r"|your\s+(?:capabilities|abilities|skills|features|functions|purpose"
    r"|name|creator|maker|origin|story|background|job|role|self)"
    r"|who\s+(?:you\s+are|are\s+you)"
    r"|what\s+(?:you\s+(?:are|do|can\s+do)|are\s+you|can\s+you\s+do)"
    r")$"
)


class ResearchSkill(Skill):
    name = "research"
    description = ("Research a topic across several websites and explain it in "
                   "plain language, rather than reciting one page")
    # Above wikipedia_lookup (65) so open questions route here instead of to a
    # single Wikipedia summary.
    priority = 70

    def match(self, text: str) -> SkillMatch | None:
        low = _TAIL.sub("", text.lower().strip(" ?.!"))

        for pat in _EXPLICIT:
            m = pat.search(low)
            if m:
                topic = m.group(1).strip()
                # "tell me about yourself" is not a research request.
                if _SELF_REFERENTIAL.match(topic):
                    return None
                if len(topic) > 2:
                    return SkillMatch(confidence=0.93, entities={"topic": topic})

        for pat in _QUESTIONS:
            m = pat.search(low)
            if m:
                topic = m.group(1).strip()
                # 0.62 is chosen, not arbitrary:
                #   - above wikipedia_lookup's 0.55 for the same phrasings,
                #     because the registry breaks ties by list order and
                #     wikipedia sorts first — an equal score always lost.
                #   - below the 0.85 high-confidence gate, so "what time is
                #     it" still reaches time_date (0.95) and "what is a
                #     decorator" still reaches coding_assistant (0.9).
                # Philosophical questions parse as lookups but are not.
                # Searching five sites for "the meaning of life" returns
                # encyclopedia definitions — a worse answer than talking
                # about it. define_word and wikipedia_lookup already skip
                # these; research has to as well or it intercepts them first.
                if topic in _PHILOSOPHICAL:
                    return None
                if _SELF_REFERENTIAL.match(topic):
                    return None
                # >1 not >3: acronyms are exactly the things worth
                # researching. 'agi', 'llm', 'rag' were all excluded.
                if len(topic) > 1:
                    return SkillMatch(confidence=0.62, entities={"topic": topic})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        topic = (entities.get("topic") or text).strip()
        if not topic:
            return SkillResult("What would you like me to look into?")

        logger.info(f"researching: {topic!r}")
        try:
            # The agentic browser, not the one-shot search. It reads, judges
            # whether it can actually answer, and searches again if not —
            # which is the difference between looking something up and
            # researching it.
            from functools import partial
            from research.browser import browse
            # browse() takes keyword-only arguments, and run_in_thread passes
            # positionally — so bind them here rather than silently raising
            # TypeError inside the worker and reporting it as "couldn't get
            # out to the web", which is a network error message for a
            # programming mistake.
            out = await run_in_thread(
                partial(browse, topic, per_hop=4, max_hops=2))
        except Exception as exc:
            # Distinguish the two. "Couldn't reach the web" for a TypeError
            # sent a real debugging session looking at the network.
            logger.exception("research failed")
            if isinstance(exc, (TypeError, AttributeError, ImportError)):
                return SkillResult(
                    "My research tool is misconfigured — that's a bug on my "
                    "side, not a network problem.")
            return SkillResult("I couldn't get out to the web just then.")

        if not out.get("ok"):
            reason = out.get("error", "nothing useful came back")
            return SkillResult(
                f"I searched for that but {reason}. Try rephrasing it?")

        answer = out["answer"]
        hosts = []
        for s in out.get("sources", []):
            if s["host"] not in hosts:
                hosts.append(s["host"])
        hosts = hosts[:5]
        if hosts:
            # Spoken, so name the sources rather than listing URLs.
            answer += f" I read that across {', '.join(hosts[:-1])} and {hosts[-1]}."
        return SkillResult(answer)
