# Generated by Claudian.
"""Skill: shut Jarvis itself down (not the Mac)."""

import re

from ai.response_generator import ResponseGenerator
from skills._base import Skill, SkillMatch, SkillResult

_PATTERNS = [
    re.compile(r"\b(goodbye|bye|stop|exit|quit|shutdown)\s+jarvis\b"),
    re.compile(r"\bjarvis\s+(goodbye|bye|stop|exit|quit)\b"),
]


class ShutdownJarvisSkill(Skill):
    name = "shutdown_jarvis"
    description = "Stop the Jarvis assistant (not the Mac)"
    priority = 5  # beats everything else

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()
        for pat in _PATTERNS:
            if pat.search(low):
                return SkillMatch(confidence=0.98)
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        return SkillResult(text=self._responses.goodbye(), should_shutdown=True)
