# Generated by Claudian.
"""Skill: shut the Mac down.

⚠  This is a destructive action.  A future improvement (Phase 5-ish) will
add a confirmation step — until then the regex is intentionally strict so
misheard phrases don't trigger it.
"""

import re

from automation.system_control import shutdown_mac
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult

_PATTERN = re.compile(
    r"(shut\s*down|power\s*off)\s*(the\s+)?(mac|macbook|computer|laptop|system)?$"
)


class ShutdownSystemSkill(Skill):
    name = "shutdown_system"
    description = "Shut the Mac down (destructive!)"
    priority = 8  # before most, so generic 'shut down' doesn't fall through

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower().strip()
        # "shutdown jarvis" / "jarvis shutdown" belong to shutdown_jarvis
        if "jarvis" in low:
            return None
        if _PATTERN.search(low):
            return SkillMatch(confidence=0.95)
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        # Gated: irreversible. The gate lives in core/confirmation.py so
        # this skill cannot approve itself.
        async def _do() -> str:
            await run_in_thread(shutdown_mac)
            return "Shutting down. Goodbye."

        from core.confirmation import PendingAction
        return SkillResult(
            text="Shut down your Mac? Say yes to confirm.",
            confirm=PendingAction(description="shut down your Mac", run=_do),
        )
