# Generated by Claudian.
"""Skill: report CPU, memory, and disk usage.

Ported from GauravSingh9356/J.A.R.V.I.S (which reported bare CPU percent via
psutil) and expanded: this reports CPU, RAM and disk in one spoken summary,
and can answer each individually.
"""

from __future__ import annotations

import re

from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

_CPU = re.compile(r"\b(?:cpu|processor)\b")
_RAM = re.compile(r"\b(?:ram|memory)\b")
_DISK = re.compile(r"\b(?:disk|storage|drive|space)\b")
_TRIGGER = re.compile(
    r"\b(?:usage|used|utilisation|utilization|load|stats?|status|"
    r"how much|how's|hows|check|free|available|performance)\b"
)


class SystemStatsSkill(Skill):
    name = "system_stats"
    description = "Report CPU, memory (RAM), and disk usage of this machine"
    priority = 25

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()

        wants_cpu = bool(_CPU.search(low))
        wants_ram = bool(_RAM.search(low))
        wants_disk = bool(_DISK.search(low))

        if not (wants_cpu or wants_ram or wants_disk):
            # "system stats" / "how's my system"
            if re.search(r"\bsystem\b", low) and _TRIGGER.search(low):
                return SkillMatch(confidence=0.9, entities={"parts": ["cpu", "ram", "disk"]})
            return None

        # A resource word alone isn't enough ("open activity monitor" mentions
        # nothing, but "play memory by anderson .paak" would false-positive).
        if not _TRIGGER.search(low):
            return None

        parts = []
        if wants_cpu:
            parts.append("cpu")
        if wants_ram:
            parts.append("ram")
        if wants_disk:
            parts.append("disk")

        return SkillMatch(confidence=0.93, entities={"parts": parts})

    async def run(self, text: str, entities: dict) -> SkillResult:
        parts = entities.get("parts") or ["cpu", "ram", "disk"]
        try:
            return SkillResult(await run_in_thread(self._read, parts))
        except Exception as e:
            logger.error(f"system_stats failed: {e}")
            return SkillResult("I couldn't read the system stats.")

    def _read(self, parts: list[str]) -> str:
        import psutil

        chunks = []

        if "cpu" in parts:
            # interval=0.4 gives a real sample; interval=None returns a
            # meaningless 0.0 on the first ever call.
            cpu = psutil.cpu_percent(interval=0.4)
            cores = psutil.cpu_count(logical=True)
            chunks.append(f"CPU is at {cpu:.0f} percent across {cores} cores")

        if "ram" in parts:
            mem = psutil.virtual_memory()
            used_gb = (mem.total - mem.available) / (1024 ** 3)
            total_gb = mem.total / (1024 ** 3)
            chunks.append(
                f"memory is {mem.percent:.0f} percent used, "
                f"{used_gb:.1f} of {total_gb:.0f} gigabytes"
            )

        if "disk" in parts:
            disk = psutil.disk_usage("/")
            free_gb = disk.free / (1024 ** 3)
            chunks.append(f"disk is {disk.percent:.0f} percent full with {free_gb:.0f} gigabytes free")

        if not chunks:
            return "Nothing to report."

        if len(chunks) == 1:
            return chunks[0].capitalize() + "."

        return ", and ".join([", ".join(chunks[:-1]), chunks[-1]]).capitalize() + "."
