# Generated by Claudian.
"""Skill: answer "what time is it" / "what day is it" etc."""

import re

from ai.response_generator import ResponseGenerator
from skills._base import Skill, SkillMatch, SkillResult

_TIME_RE = re.compile(
    r"what\s+(time|is\s+the\s+time)|current\s+time|tell\s+me\s+the\s+time|what's\s+the\s+time"
)
_DATE_RE = re.compile(
    r"what\s+(day|date)|today'?s?\s+date|current\s+date|what\s+is\s+today|day\s+is\s+it"
)


class TimeDateSkill(Skill):
    name = "time_date"
    description = "Answer 'what time is it' or 'what's today's date'"
    priority = 10

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()
        if _TIME_RE.search(low):
            return SkillMatch(confidence=0.95, entities={"kind": "time"})
        if _DATE_RE.search(low):
            return SkillMatch(confidence=0.95, entities={"kind": "date"})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        kind = entities.get("kind", "time")
        if kind == "date":
            return SkillResult(text=self._responses.date_response())
        return SkillResult(text=self._responses.time_response())
