# Generated by Claudian.
"""Skill: change system volume (set a level, or up/down)."""

import re

from ai.response_generator import ResponseGenerator
from automation.system_control import change_volume
from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.helpers import parse_volume


def _clamp(v: int) -> int:
    return max(0, min(100, v))


class VolumeSkill(Skill):
    name = "volume"
    description = "Change system volume (to a specific level, or up/down)"
    priority = 12  # before 'mute' so "volume off" isn't captured as mute

    def __init__(self):
        self._responses = ResponseGenerator()

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower()
        if "volume" not in low and "sound" not in low:
            return None

        m = re.search(r"volume\s+(?:to\s+)?(\d{1,3})", low)
        if m:
            return SkillMatch(confidence=0.95, entities={"level": _clamp(int(m.group(1)))})

        if re.search(r"full\s+volume|max\s+volume|maximum\s+volume", low):
            return SkillMatch(confidence=0.95, entities={"level": 100})
        if re.search(r"half\s+volume", low):
            return SkillMatch(confidence=0.95, entities={"level": 50})
        if re.search(r"(zero|no)\s+volume|volume\s+(to\s+)?(zero|nothing)", low):
            return SkillMatch(confidence=0.95, entities={"level": 0})

        if re.search(
            r"(volume|sound)\s+(up|higher|louder)"
            r"|(raise|increase|turn\s+up)\s+(the\s+)?(volume|sound)",
            low,
        ):
            return SkillMatch(confidence=0.9, entities={"action": "up"})
        if re.search(
            r"(volume|sound)\s+(down|lower|quieter)"
            r"|(lower|decrease|turn\s+down)\s+(the\s+)?(volume|sound)",
            low,
        ):
            return SkillMatch(confidence=0.9, entities={"action": "down"})
        return None

    async def run(self, text: str, entities: dict) -> SkillResult:
        level = entities.get("level")
        action = entities.get("action")

        if level is None and action is None:
            level = parse_volume(text)
            if level is None:
                action = "up" if any(w in text.lower() for w in ["up", "increase", "louder"]) else "down"

        ok, result = await run_in_thread(change_volume, level, action)
        if not ok:
            return SkillResult(text=self._responses.action_failed("adjust volume"))
        if result.isdigit():
            return SkillResult(text=self._responses.volume_set(int(result)))
        return SkillResult(text=f"Volume {result}.")
