# Generated by Claudian.
"""Skill: say who has messaged on WhatsApp and what they said.

Reads macOS Notification Center rather than WhatsApp itself — see
`integrations/whatsapp/notification_reader` for why (short version: driving a
real WhatsApp session risks the account, and this cannot).

Pairs with `whatsapp_send`: this one reads, that one replies.
"""

from __future__ import annotations

import re

from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

# Deliberately narrow. "any messages" is a plausible thing to say about other
# things too, so every pattern names WhatsApp, texting, or messages explicitly.
_ASK = re.compile(
    r"(?i)\b("
    r"who(?:'s| has| have)?\s+(?:texted|messaged|pinged|written|whatsapp(?:ed)?)"
    r"|(?:any|new|unread|check)\s+(?:my\s+)?(?:whats\s*app\s+)?(?:messages?|texts?|chats?)"
    r"|check\s+(?:my\s+)?whats\s*app"
    # what / whats / what's — speech-to-text drops apostrophes constantly.
    r"|what(?:'?s| is| are)?\s+(?:on\s+)?(?:my\s+)?whats\s*app"
    r"|read\s+(?:me\s+)?(?:my\s+)?(?:whats\s*app|messages?)"
    r"|did\s+(?:anyone|anybody|someone)\s+(?:text|message|ping)\s+me"
    r"|messages?\s+from\s+\w+"
    r")"
)

# "any messages from Aki" — report just that person.
_FROM = re.compile(r"(?i)\bfrom\s+([a-z][\w'-]*(?:\s+[a-z][\w'-]*)?)\s*[.?!]*$")


class WhatsAppReadSkill(Skill):
    name = "whatsapp_read"
    description = "Say who has messaged on WhatsApp recently and what they said"
    # Above whatsapp_send (18) would steal "message Aki saying hi", so sit
    # just below it — send is the more specific intent and should win.
    priority = 19

    def match(self, text: str) -> SkillMatch | None:
        if not _ASK.search(text or ""):
            return None
        # A send request mentions both a contact and a body; those belong to
        # whatsapp_send and it bids higher anyway. This only guards the case
        # where someone says "message from Aki" meaning *read*, not *send*.
        if re.search(r"(?i)\b(saying|tell\s+\w+\s+that)\b", text):
            return None
        ents = {}
        m = _FROM.search(text)
        if m:
            ents["who"] = m.group(1).strip().lower()
        return SkillMatch(confidence=0.9, entities=ents)

    async def run(self, text: str, entities: dict) -> SkillResult:
        from integrations.whatsapp import notification_reader as nr

        ok, why = await run_in_thread(nr.available)
        if not ok:
            # Say what is wrong and how to fix it. "I couldn't check" with no
            # reason is the kind of dead end that makes a feature look broken
            # when it is one checkbox away from working.
            return SkillResult(text=f"I can't read your WhatsApp notifications. {why}.")

        notes = await run_in_thread(nr.recent, 0.0, 50)

        who = (entities or {}).get("who")
        if who:
            notes = [n for n in notes
                     if who in n.sender.lower() or who in (n.group or "").lower()]
            if not notes:
                return SkillResult(text=f"Nothing from {who} on WhatsApp.")

        if not notes:
            return SkillResult(text="No recent WhatsApp messages.")

        # Spoken aloud, so cap it. Reading forty notifications is not useful.
        notes = notes[-6:]
        return SkillResult(text=await run_in_thread(nr.summarise, notes))
