# Generated by Claudian.
"""Skill: look something up on Wikipedia and speak a short summary.

Ported from the feature set of GauravSingh9356/J.A.R.V.I.S.

That project used the `wikipedia` PyPI package.  We tried the same and it
HUNG INDEFINITELY: `wikipedia` 1.4.0 (released 2014, unmaintained) passes no
`timeout` to its underlying requests call, so a slow or rate-limited response
blocks the calling thread forever — and because `run_in_thread` hands work to
a ThreadPoolExecutor, a hung call permanently burns one of only four workers.
Four such lookups would deadlock every skill in the assistant.

So this talks to Wikipedia's REST API directly:
  • an explicit timeout on every request (the actual bug fix)
  • one HTTP round trip instead of the library's three
  • no extra dependency — just `requests`, which is already required
  • disambiguation handled via the opensearch endpoint
"""

from __future__ import annotations

import re
from urllib.parse import quote

import requests

from multitasking.async_executor import run_in_thread
from skills._base import Skill, SkillMatch, SkillResult
from utils.logger import get_logger

logger = get_logger(__name__)

SUMMARY_URL = "https://en.wikipedia.org/api/rest_v1/page/summary/{title}"
SEARCH_URL = "https://en.wikipedia.org/w/api.php"

# Wikipedia's API policy asks for a descriptive UA identifying the client.
HEADERS = {"User-Agent": "JarvisAI/1.0 (personal voice assistant)"}

TIMEOUT = 8  # seconds — the thing the `wikipedia` package forgot

# Reused across calls so we pay DNS + TLS handshake once, not per request.
# Matters most on the disambiguation path, which makes three round trips.
_session = requests.Session()
_session.headers.update(HEADERS)

_PATTERNS = [
    re.compile(r"(?:search\s+)?wikipedia\s+(?:for\s+)?(.+)"),
    re.compile(r"who\s+(?:is|was|are|were)\s+(.+)"),
    re.compile(r"what\s+(?:is|was|are|were)\s+(?:a\s+|an\s+|the\s+)?(.+)"),
    re.compile(r"tell\s+me\s+about\s+(.+)"),
]

_TAIL = re.compile(r"\s+(?:please|jarvis|for me)\s*$")


class WikipediaSkill(Skill):
    name = "wikipedia_lookup"
    description = "Look up a person, place, or topic on Wikipedia and summarise it"
    # Loses to coding_assistant (60) for "what is a decorator" and to
    # time_date / define_word, which are more specific.
    priority = 65

    def match(self, text: str) -> SkillMatch | None:
        low = text.lower().strip(" ?.!")

        if low.startswith("wikipedia") or "search wikipedia" in low:
            m = _PATTERNS[0].search(low)
            if m:
                return SkillMatch(confidence=0.95, entities={"topic": self._clean(m.group(1))})

        m = _PATTERNS[1].search(low)
        if m:
            return SkillMatch(confidence=0.88, entities={"topic": self._clean(m.group(1))})

        # Weaker forms — sit below the 0.85 threshold so the LLM tie-breaker
        # can hand these to coding_assistant or conversation instead.
        for pat in _PATTERNS[2:]:
            m = pat.search(low)
            if m:
                topic = self._clean(m.group(1))
                if len(topic) > 2:
                    return SkillMatch(confidence=0.55, entities={"topic": topic})

        return None

    @staticmethod
    def _clean(topic: str) -> str:
        return _TAIL.sub("", topic).strip(" ?.!,")

    async def run(self, text: str, entities: dict) -> SkillResult:
        topic = (entities.get("topic") or "").strip()
        if not topic:
            return SkillResult("What would you like me to look up?")

        try:
            return SkillResult(await run_in_thread(self._lookup, topic))
        except requests.Timeout:
            return SkillResult("Wikipedia took too long to respond.")
        except Exception as e:
            logger.error(f"wikipedia lookup failed for {topic!r}: {e}")
            return SkillResult("I couldn't reach Wikipedia just now.")

    # ── Network (always called via run_in_thread) ────────────────────────────

    def _lookup(self, topic: str) -> str:
        summary = self._summary(topic)
        if summary:
            return summary

        # Direct title missed — fall back to search and retry the best hit.
        best = self._search_first(topic)
        if best and best.lower() != topic.lower():
            summary = self._summary(best)
            if summary:
                return summary

        return f"I couldn't find a Wikipedia article for {topic}."

    def _summary(self, title: str) -> str | None:
        url = SUMMARY_URL.format(title=quote(title.replace(" ", "_"), safe=""))
        resp = _session.get(url, timeout=TIMEOUT)

        if resp.status_code == 404:
            return None
        resp.raise_for_status()
        data = resp.json()

        # Disambiguation pages have no useful extract — resolve to a real one.
        if data.get("type") == "disambiguation":
            alt = self._search_first(title, skip=title)
            if alt:
                nested = _session.get(
                    SUMMARY_URL.format(title=quote(alt.replace(" ", "_"), safe="")),
                    timeout=TIMEOUT,
                )
                if nested.ok:
                    ndata = nested.json()
                    if ndata.get("type") != "disambiguation" and ndata.get("extract"):
                        return f"There are a few. Going with {alt}. {self._trim(ndata['extract'])}"
            return f"There are several things called {title}. Could you be more specific?"

        extract = (data.get("extract") or "").strip()
        return self._trim(extract) if extract else None

    def _search_first(self, query: str, skip: str | None = None) -> str | None:
        resp = _session.get(
            SEARCH_URL,
            params={
                "action": "opensearch",
                "search": query,
                "limit": 5,
                "namespace": 0,
                "format": "json",
            },
            timeout=TIMEOUT,
        )
        resp.raise_for_status()
        data = resp.json()

        # opensearch returns [query, [titles], [descriptions], [urls]]
        titles = data[1] if len(data) > 1 and isinstance(data[1], list) else []
        for t in titles:
            if skip and t.lower() == skip.lower():
                continue
            if "disambiguation" in t.lower():
                continue
            return t
        return None

    @staticmethod
    def _trim(extract: str, max_sentences: int = 2) -> str:
        """Keep it short — this gets spoken aloud, not read."""
        parts = re.split(r"(?<=[.!?])\s+", extract.strip())
        return " ".join(parts[:max_sentences]).strip()
