#!/usr/bin/env python3
# Generated by Claudian.
"""Turn real usage into training data.

    python3 training/collect_feedback.py            # report only
    python3 training/collect_feedback.py --write    # write the dataset

WHY THIS BEATS MORE SYNTHETIC DATA
----------------------------------
The holdout evaluation showed the classifier fails on phrasings it has never
seen — "boot up sublime", "crank it", "catch me up". I can invent paraphrases
forever and still not guess how *you* actually speak. Your own logged
commands are the ground truth for that.

WHERE THE LABELS COME FROM
--------------------------
Every handled command is logged with the routing tier that decided it.  Only
`source='regex'` rows above the registry's high-confidence threshold are used
here.  Those came from an explicit pattern match, so the label is effectively
free ground truth.

Rows routed by the local model or the LLM are deliberately excluded.  Training
a model on its own predictions is self-confirmation: it would relabel its
mistakes as correct and drift further with every retrain.

WHAT THE REGEX ROWS ACTUALLY TEACH
----------------------------------
It's fair to ask what use it is to learn utterances the regex already handles.
The value isn't the utterance itself — it's the vocabulary.  Seeing that you
say "chuck on some music" teaches the model your register, which generalises
to nearby phrasings the regex does *not* catch.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

FEEDBACK_PATH = Path(__file__).parent.parent / "data" / "models" / "feedback_data.json"

MIN_CONFIDENCE = 0.85
MIN_LENGTH = 2          # single tokens are too ambiguous to label
MAX_LENGTH = 120


def _existing_utterances() -> set[str]:
    """Everything already in the synthetic dataset, for dedup."""
    from ai.intent_augment import build_augmented

    seen: set[str] = set()
    for utts in build_augmented().values():
        seen.update(u.strip().lower() for u in utts)
    return seen


def collect() -> tuple[dict[str, list[str]], dict]:
    from memory.store import get_memory

    memory = get_memory()
    rows = memory.training_events(source="regex", min_confidence=MIN_CONFIDENCE)

    known = _existing_utterances()

    collected: dict[str, list[str]] = {}
    novel = 0
    duplicate = 0
    rejected = 0
    per_skill_seen: set[tuple[str, str]] = set()

    for utterance, skill in rows:
        text = (utterance or "").strip().lower()
        if not text or not skill:
            rejected += 1
            continue
        if not (MIN_LENGTH <= len(text.split()) or len(text) >= 4):
            rejected += 1
            continue
        if len(text) > MAX_LENGTH:
            rejected += 1
            continue
        if (text, skill) in per_skill_seen:
            duplicate += 1
            continue
        per_skill_seen.add((text, skill))
        if text in known:
            duplicate += 1
            continue
        collected.setdefault(skill, []).append(text)
        novel += 1

    stats = {
        "rows_examined": len(rows),
        "novel": novel,
        "duplicate": duplicate,
        "rejected": rejected,
        "skills_covered": len(collected),
    }
    return collected, stats


def audit_current_model(collected: dict[str, list[str]]) -> None:
    """Show which real utterances the current model gets wrong.

    These are the highest-value examples in the whole set: real things you
    said that the model would misroute today.
    """
    try:
        from ai.intent_classifier_local import get_local_classifier
    except Exception:
        return

    clf = get_local_classifier()
    if not clf.available:
        return

    wrong: list[str] = []
    below_gate = 0
    total = 0
    for skill, utts in collected.items():
        for u in utts:
            total += 1
            pred, conf = clf.predict(u)
            if pred != skill:
                wrong.append(f"    {u!r:44} {skill} -> {pred} ({conf:.2f})")
            elif conf < clf.threshold:
                below_gate += 1

    if not total:
        return

    print(f"  Current model on your real utterances:")
    print(f"    misrouted        : {len(wrong)}/{total}")
    print(f"    right but unsure : {below_gate}/{total} (would defer to the LLM)")
    if wrong:
        print("  Highest-value examples (model gets these wrong today):")
        for line in wrong[:15]:
            print(line)
        if len(wrong) > 15:
            print(f"    ... and {len(wrong) - 15} more")
    print()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="write the collected data to data/models/feedback_data.json")
    ap.add_argument("--min-per-skill", type=int, default=1)
    args = ap.parse_args()

    print("=" * 70)
    print("FEEDBACK COLLECTION — real usage into training data".center(70))
    print("=" * 70)
    print()

    collected, stats = collect()

    print(f"  trustworthy rows examined : {stats['rows_examined']}")
    print(f"  novel utterances          : {stats['novel']}")
    print(f"  already in dataset        : {stats['duplicate']}")
    print(f"  rejected (too short/long) : {stats['rejected']}")
    print(f"  skills covered            : {stats['skills_covered']}")
    print()

    if not collected:
        print("  Nothing to collect yet.")
        print()
        print("  This is expected on a fresh install — the pool fills as you")
        print("  actually use JARVIS. Talk to it for a few days, then re-run.")
        print()
        print("=" * 70)
        return 0

    counts = Counter({k: len(v) for k, v in collected.items()})
    print("  Novel utterances per skill:")
    for skill, n in counts.most_common():
        print(f"    {skill:20} {n:4}")
    print()

    audit_current_model(collected)

    filtered = {k: v for k, v in collected.items() if len(v) >= args.min_per_skill}

    if args.write:
        FEEDBACK_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(FEEDBACK_PATH, "w") as f:
            json.dump(filtered, f, indent=2)
        print(f"  Wrote {sum(len(v) for v in filtered.values())} utterances "
              f"-> {FEEDBACK_PATH.name}")
        print()
        print("  Retrain to pick them up:")
        print("    python3 training/train_intent_model.py --epochs 100")
        print("    python3 training/holdout_eval.py")
    else:
        print("  Dry run. Re-run with --write to save.")

    print()
    print("=" * 70)
    return 0


if __name__ == "__main__":
    sys.exit(main())
