# Generated by Claudian.
"""Free-form conversation engine.

Routes the chat call through whichever LLM provider is configured:
  • LLM_PROVIDER=groq   → Groq cloud API (fast, default)
  • LLM_PROVIDER=ollama → local Ollama server (private, offline, free)

Both providers share the same `chat(user_message) -> str` surface so the
`conversation` skill doesn't care which one is active.
"""

from __future__ import annotations

import re
from typing import Callable, Iterator, Optional

from ai.memory import ConversationMemory
from config import settings
from config.constants import SYSTEM_PROMPT


# ── Capability grounding ─────────────────────────────────────────────────────
# Without this the model had no idea what Jarvis can actually do, so it
# confidently agreed to things that do not exist. Measured before the fix:
#   "can you send an email for me" -> "Sure thing, Boss. Who's the recipient?"
#   "book me a flight to delhi"    -> asked for travel dates and class
#   "what can you do"              -> claimed it could create/move/rename files
# It has no email skill, no booking skill, and can only *search* for files.
#
# The list is generated from the live skill registry rather than written by
# hand, so it cannot drift out of sync as skills are added or removed.
#
# Prompted by GPT-6 Astra's capability-hallucination result (4.2% vs 12.2%
# for the previous model): a system that knows its own boundaries is more
# useful than one that agrees to everything.

_capabilities_cache: str | None = None


def _capability_block() -> str:
    """Describe the real skill set, built from the registry at first use."""
    global _capabilities_cache
    if _capabilities_cache is not None:
        return _capabilities_cache

    try:
        # Imported lazily: the registry imports every skill, and the
        # conversation skill imports this module — at module scope that
        # would be circular.
        from skills._registry import get_registry
        lines = [
            f"- {s.description}"
            for s in get_registry().all_skills()
            if s.name != "conversation"
        ]
        listing = "\n".join(sorted(lines))
    except Exception:
        listing = "- (capability list unavailable)"

    _capabilities_cache = (
        "\n\nWHAT YOU CAN ACTUALLY DO\n"
        "These are your only real abilities on this Mac:\n"
        f"{listing}\n\n"
        "Anything outside that list you CANNOT do. You cannot send email, "
        "book travel, order food, make purchases, send SMS, edit or delete "
        "files, or control other devices.\n"
        "If asked for something you cannot do, say so plainly in one sentence "
        "and suggest the closest thing you can do. Never ask for details "
        "(dates, recipients, addresses) for a task you cannot complete — "
        "collecting information you will never use is worse than refusing.\n"
        "Never claim an action succeeded unless you actually performed it.\n\n"
        "SPEAKING\n"
        "Your replies are spoken aloud. Never use markdown, bullet points, "
        "numbered lists, or headings — they are read out as literal "
        "punctuation. Write in plain spoken sentences."
    )
    return _capabilities_cache
from utils.logger import get_logger

# Sentence boundary: end-punct followed by whitespace OR end-of-string.
_SENTENCE_END = re.compile(r"([\.\!\?]+)(\s+|$)")
# Minimum chars before we'll flush a sentence — avoids speaking "Oh." alone
# while a longer continuation is still streaming in.
_MIN_FLUSH_CHARS = 12

logger = get_logger(__name__)


_OFFLINE_REPLY = (
    "I can handle system tasks offline — opening apps, volume, WhatsApp, screenshots, and more. "
    "For general questions I need an LLM.  Either set GROQ_API_KEY in .env, "
    "or run a local model with `ollama serve` and set LLM_PROVIDER=ollama."
)


class ConversationEngine:
    def __init__(self, memory: ConversationMemory):
        self._memory = memory
        self._groq = None
        self._ollama = None

    # ── Public ───────────────────────────────────────────────────────────────

    def chat(self, user_message: str) -> str:
        self._memory.add("user", user_message)
        if not settings.has_ai():
            self._memory.add("assistant", _OFFLINE_REPLY)
            return _OFFLINE_REPLY

        provider = settings.LLM_PROVIDER
        try:
            if provider == "ollama":
                reply = self._chat_ollama(user_message)
            else:
                reply = self._chat_groq(user_message)
        except Exception as e:
            logger.error(f"{provider} chat error: {e}")
            return self._provider_failure_message(provider)

        self._memory.add("assistant", reply)
        return reply

    def chat_stream(
        self,
        user_message: str,
        on_sentence: Callable[[str], None],
    ) -> str:
        """Stream a reply from the LLM, calling `on_sentence(sentence)` as
        each complete sentence is detected.  Returns the full assembled
        reply (also written to memory).

        Falls back to non-streaming `chat()` for providers that can't stream.
        """
        self._memory.add("user", user_message)
        if not settings.has_ai():
            self._memory.add("assistant", _OFFLINE_REPLY)
            on_sentence(_OFFLINE_REPLY)
            return _OFFLINE_REPLY

        provider = settings.LLM_PROVIDER
        if provider != "groq":
            # Ollama path — no streaming yet, just speak the whole reply once.
            reply = self.chat(user_message)
            on_sentence(reply)
            # `chat()` already appended both user+assistant, so undo the
            # duplicate user-message we added at the top of this method.
            history = self._memory.get_history()
            if len(history) >= 2 and history[-2]["role"] == "user" \
                    and history[-2]["content"] == user_message \
                    and history[-3:-2] and history[-3]["role"] == "user":
                # Only happens if `chat()` re-added user — defensive no-op
                pass
            return reply

        try:
            return self._stream_groq(on_sentence)
        except Exception as e:
            logger.error(f"Groq streaming error: {e}")
            fallback = self._provider_failure_message("groq")
            self._memory.add("assistant", fallback)
            on_sentence(fallback)
            return fallback

    def _stream_groq(self, on_sentence: Callable[[str], None]) -> str:
        client = self._get_groq()
        messages = [{"role": "system", "content": SYSTEM_PROMPT + _capability_block()}] + self._build_history(self._last_user_message())
        stream = client.chat.completions.create(
            model=settings.GROQ_CHAT_MODEL,
            messages=messages,
            max_tokens=512,
            temperature=0.7,
            stream=True,
            timeout=15.0,
        )

        buffer = ""
        full = ""
        for chunk in stream:
            try:
                delta = chunk.choices[0].delta.content or ""
            except (AttributeError, IndexError):
                delta = ""
            if not delta:
                continue
            buffer += delta
            full += delta
            # Flush any complete sentences sitting in the buffer.
            while True:
                m = _SENTENCE_END.search(buffer)
                if not m:
                    break
                end = m.end()
                sentence = buffer[:end].strip()
                if len(sentence) < _MIN_FLUSH_CHARS:
                    break  # wait for more — don't flush a tiny fragment yet
                on_sentence(sentence)
                buffer = buffer[end:]

        # Flush any tail (no trailing punctuation, but the model is done)
        tail = buffer.strip()
        if tail:
            on_sentence(tail)

        full = full.strip()
        self._memory.add("assistant", full)
        return full

    # ── Provider-specific ────────────────────────────────────────────────────

    def _chat_groq(self, _user_message: str) -> str:
        client = self._get_groq()
        messages = [{"role": "system", "content": SYSTEM_PROMPT + _capability_block()}] + self._build_history(self._last_user_message())
        response = client.chat.completions.create(
            model=settings.GROQ_CHAT_MODEL,
            messages=messages,
            max_tokens=512,
            temperature=0.7,
            timeout=15.0,
        )
        return (response.choices[0].message.content or "").strip()

    def _chat_ollama(self, _user_message: str) -> str:
        client = self._get_ollama()
        messages = [{"role": "system", "content": SYSTEM_PROMPT + _capability_block()}] + self._build_history(self._last_user_message())
        return client.chat(messages, max_tokens=512, temperature=0.7)

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _last_user_message(self) -> str:
        """The most recent user turn, used as the retrieval query.

        Read from history rather than passed in: the three call sites have
        inconsistent signatures (`_user_message`, and none at all for the
        streaming path), and the last user turn is already recorded by the
        time any of them run.
        """
        try:
            for msg in reversed(self._memory.get_history()):
                if msg.get("role") == "user":
                    return msg.get("content", "")
        except Exception:
            pass
        return ""

    def _build_history(self, query: str = "") -> list[dict]:
        """Recent turns, plus anything older that is relevant to `query`.

        The sliding window keeps the last N turns and DROPS the rest, so
        "what did I say about the deadline?" fails the moment that turn ages
        out — the information is gone from context even though it is still on
        disk in the events table.

        GPT-6 Astra's Codex integration handles the same problem by keeping
        earlier context searchable instead of compressing it into a single
        lossy summary. The same idea applies here, and cheaply: every handled
        command is already logged to SQLite with an FTS5 index. So rather than
        discarding aged-out turns, we retrieve the relevant ones on demand.

        Cost is bounded: a local FTS5 query and at most a few hundred extra
        tokens, only when something actually matches.
        """
        recent = [
            {"role": msg["role"], "content": msg["content"]}
            for msg in self._memory.get_history()
        ]

        recalled = self._recall_relevant(query, recent)
        if not recalled:
            return recent

        # Injected as a system message so the model treats it as reference
        # material rather than as something the user just said.
        return [{
            "role": "system",
            "content": (
                "Relevant earlier exchanges, retrieved from long-term memory "
                "because they relate to the current message. They are older "
                "than the visible conversation:\n" + recalled
            ),
        }] + recent

    # How many aged-out exchanges to pull back in, and the shortest query
    # worth searching on — single words match far too broadly to be useful.
    _RECALL_LIMIT = 3
    _MIN_QUERY_WORDS = 2

    def _recall_relevant(self, query: str, recent: list[dict]) -> str:
        """Search past events for exchanges not already in the window."""
        if not query or len(query.split()) < self._MIN_QUERY_WORDS:
            return ""

        try:
            from memory import get_memory as _get_store
            store = _get_store()
            rows = store.search_events(query, limit=self._RECALL_LIMIT * 3)
        except Exception as e:
            logger.debug(f"memory recall failed: {e}")
            return ""

        # Skip anything already visible in the recent window; repeating it
        # wastes context and can make the model think it happened twice.
        seen = {m["content"].strip().lower() for m in recent}

        lines = []
        for user_text, reply_text in rows:
            if user_text.strip().lower() in seen:
                continue
            snippet = (reply_text or "").strip().replace("\n", " ")
            if len(snippet) > 160:
                snippet = snippet[:160].rsplit(" ", 1)[0] + "..."
            lines.append(f"- You asked: {user_text.strip()}\n  I answered: {snippet}")
            if len(lines) >= self._RECALL_LIMIT:
                break

        return "\n".join(lines)

    def _get_groq(self):
        if self._groq is None:
            from groq import Groq
            self._groq = Groq(api_key=settings.GROQ_API_KEY)
        return self._groq

    def _get_ollama(self):
        if self._ollama is None:
            from ai.local_llm import OllamaClient
            self._ollama = OllamaClient()
        return self._ollama

    def _provider_failure_message(self, provider: str) -> str:
        if provider == "ollama":
            return (
                "I couldn't reach the local Ollama server.  "
                "Try running `ollama serve` and `ollama pull "
                f"{settings.OLLAMA_MODEL}`."
            )
        return "I'm having trouble reaching Groq right now. Check your API key and internet connection."
