# Generated by Claudian.
"""Free-form conversation engine.

Routes the chat call through whichever LLM provider is configured:
  • LLM_PROVIDER=groq   → Groq cloud API (fast, default)
  • LLM_PROVIDER=ollama → local Ollama server (private, offline, free)

Both providers share the same `chat(user_message, lang_code) -> str` surface so
the conversation skill doesn't care which one is active.  `lang_code` is a
BCP-47 tag (e.g. "ta-IN", "fr-FR") that steers the reply language.

The skill path (`skills/conversation.py`) uses this engine, so adding
`lang_code` here fixes multi-language replies for both the voice loop AND the
web/API frontend.
"""

from __future__ import annotations

import re
from typing import Callable, Iterator, Optional

from ai.memory import ConversationMemory
from config import settings
from config.constants import SYSTEM_PROMPT

# ── Capability grounding ─────────────────────────────────────────────────────
# Without this the model had no idea what Jarvis can actually do, so it
# confidently agreed to things that do not exist. Measured before the fix:
#   "can you send an email for me" -> "Sure thing, Boss. Who's the recipient?"
#   "book me a flight to delhi"    -> asked for travel dates and class
#   "what can you do"              -> claimed it could create/move/rename files
# It has no email skill, no booking skill, and can only *search* for files.
#
# The list is generated from the live skill registry rather than written by
# hand, so it cannot drift out of sync as skills are added or removed.
#
# Prompted by GPT-6 Astra's capability-hallucination result (4.2% vs 12.2%
# for the previous model): a system that knows its own boundaries is more
# useful than one that agrees to everything.

_capabilities_cache: str | None = None


def _capability_block() -> str:
    """Describe the real skill set, built from the registry at first use."""
    global _capabilities_cache
    if _capabilities_cache is not None:
        return _capabilities_cache

    try:
        # Imported lazily: the registry imports every skill, and the
        # conversation skill imports this module — at module scope that
        # would be circular.
        from skills._registry import get_registry
        lines = [
            f"- {s.description}"
            for s in get_registry().all_skills()
            if s.name != "conversation"
        ]
        listing = "\n".join(sorted(lines))
    except Exception:
        listing = "- (capability list unavailable)"

    _capabilities_cache = (
        "\n\nWHAT YOU CAN ACTUALLY DO\n"
        "These are your only real abilities on this Mac:\n"
        f"{listing}\n\n"
        "Anything outside that list you CANNOT do. You cannot send email, "
        "book travel, order food, make purchases, send SMS, edit or delete "
        "files, or control other devices.\n"
        "If asked for something you cannot do, say so plainly in one sentence "
        "and suggest the closest thing you can do. Never ask for details "
        "(dates, recipients, addresses) for a task you cannot complete — "
        "collecting information you will never use is worse than refusing.\n"
        "Never claim an action succeeded unless you actually performed it.\n\n"
        "SPEAKING\n"
        "Your replies are spoken aloud. Never use markdown, bullet points, "
        "numbered lists, or headings — they are read out as literal "
        "punctuation. Write in plain spoken sentences."
    )
    return _capabilities_cache


# Claims the conversation engine is structurally incapable of making truthfully.
#
# This engine has no tools. It talks, and nothing else — every real action goes
# through a skill, and a skill that ran would have answered instead of this.
# So a first-person "I sent it" from here is false 100% of the time, not
# occasionally.
#
# The system prompt already says "Never claim an action succeeded unless you
# actually performed it." The model said "Message sent to Aki on WhatsApp: Hi"
# anyway, and Ruthish believed it — the message was never sent. That is the
# lesson: an instruction is a request, not a guarantee. The capability list
# tells the model JARVIS *can* send WhatsApp messages, and the model does not
# distinguish "JARVIS can" from "I just did".
#
# So the check is structural, where it cannot be talked around.
_FALSE_ACTION_CLAIM = re.compile(
    r"(?i)("
    r"\bmessage\s+sent\b"
    r"|\bi(?:'ve|\s+have)?\s+(?:just\s+)?"
    r"(?:sent|messaged|texted|pinged|emailed|whatsapp(?:ed)?|notified)\b"
    r"|\bsent\s+(?:your|the|a)\s+message\b"
    r"|\bi(?:'ve|\s+have)?\s+(?:just\s+)?(?:opened|launched|started|played)\s"
    # Present progressive at the start of the reply. The past-tense patterns
    # above missed "Opening Obsidian... Obsidian's up and running." entirely,
    # and it was just as false — nothing opened. Anchored to the start so an
    # explanatory sentence ("opening a vault in Obsidian works like…") is not
    # caught.
    # The negative lookahead separates a claim from an explanation: "Opening
    # Obsidian" and "Opening the Obsidian app" are claims; "Opening a vault in
    # Obsidian works by…" is describing how something is done. An indefinite
    # article after the verb is the tell.
    r"|^\s*(?:opening|launching|starting|playing|pausing|sending|messaging)"
    r"\s+(?!a\s|an\s)\w"
    # "X is up and running" / "X is now open" — completion by another name.
    r"|\bis\s+(?:now\s+)?(?:up\s+and\s+running|open|running|launched)\b"
    r")"
)


def _strip_false_claim(reply: str, user_message: str) -> str | None:
    """Return a replacement when the model claims to have done something.

    None means the reply is fine. The replacement names the real phrasing that
    would work, so the turn is still useful rather than just a refusal.
    """
    if not reply or not _FALSE_ACTION_CLAIM.search(reply):
        return None
    logger.warning(
        f"conversation engine claimed an action it cannot perform: {reply[:80]!r}")
    if "whatsapp" in user_message.lower() or "whatsapp" in reply.lower():
        return ("I didn't actually send that — I can only send WhatsApp "
                "messages when you phrase it as a command, like: message Aki "
                "on WhatsApp saying Hi.")
    return ("I didn't actually do that. I can only act when a request matches "
            "one of my skills — say it as a direct command and I'll run it.")


def _language_clause(lang_code: str) -> str:
    """Instruction that makes the model reply in the target language.

    Without this, non-English replies fail silently: the model answers in
    English because nothing told it otherwise.  The instruction is explicit
    that this is a WRITING task — told to "reply in Tamil, spoken-sounding"
    the model previously decided it was being asked to synthesise audio and
    refused with "I can't generate spoken Tamil audio directly".
    """
    if not lang_code or lang_code.lower().startswith("en"):
        return ""
    # Use the human-readable language name from the LANGUAGES registry when
    # available, falling back to the code itself.
    try:
        from conversation.languages import by_tag
        lang = by_tag(lang_code) or by_tag(lang_code.split("-")[0])
        name = lang.name if lang else lang_code
    except Exception:
        name = lang_code
    return (
        f"\n\nWRITE your reply in {name}, using {name} script. "
        f"You are producing TEXT — a separate text-to-speech "
        f"system will read it aloud, so never say you cannot "
        f"speak, pronounce, or generate audio in {name}. "
        f"Just answer the question in {name}. "
        f"Keep it short and conversational."
    )


from utils.logger import get_logger

# Sentence boundary: end-punct followed by whitespace OR end-of-string.
# Inside a character class `.` `!` `?` are literal, so they need no
# escaping. The doubled form matched a literal backslash and required
# the two characters "\s" rather than whitespace — so sentences only
# flushed at end-of-string and streaming TTS never fired mid-reply.
_SENTENCE_END = re.compile(r"([.!?]+)(\s+|$)")
# Minimum chars before we'll flush a sentence — avoids speaking "Oh." alone
# while a longer continuation is still streaming in.
_MIN_FLUSH_CHARS = 12

logger = get_logger(__name__)


_OFFLINE_REPLY = (
    "I can handle system tasks offline — opening apps, volume, WhatsApp, screenshots, and more. "
    "For general questions I need an LLM.  Either set GROQ_API_KEY in .env, "
    "or run a local model with `ollama serve` and set LLM_PROVIDER=ollama."
)


def _explain_failure(exc: Exception) -> str | None:
    """Turn a provider exception into something worth saying out loud."""
    msg = str(exc)
    if "rate_limit" in msg or "413" in msg or "too large" in msg.lower():
        return ("That request was too big for my current rate limit. "
                "I've trimmed the conversation — try again.")
    if "401" in msg or "invalid_api_key" in msg:
        return "My API key is being rejected. It probably needs rotating."
    if "429" in msg:
        return "I'm being rate limited. Give it a moment."
    return None


class ConversationEngine:
    def __init__(self, memory: ConversationMemory, default_lang: str = "en"):
        self._memory = memory
        self._groq = None
        self._ollama = None
        self._last_error_message: str | None = None
        self._default_lang = default_lang

    # ── Public ───────────────────────────────────────────────────────────────

    def chat(self, user_message: str, context: str | None = None,
             lang_code: str = "en") -> str:
        """Answer `user_message` in the language given by `lang_code`.

        `context` is retrieval material for THIS TURN ONLY. It is injected
        into the request but never written to memory — that distinction is
        load-bearing. Retrieved context was previously prepended to the
        user message, so every turn stored ~3,500 characters of documents
        forever. Twenty turns later the history alone was 9,272 tokens and
        every request hit Groq's 8,000 TPM ceiling with HTTP 413.
        """
        self._memory.add("user", user_message)
        self._pending_context = context

        # Short social turns go to the local persona LoRA — ~0.4s and offline,
        # against ~1.3s for a cloud round trip that needed no knowledge.
        #
        # This lives here rather than in ConversationSkill because the skill
        # bids confidence 0.05, below web/server.py's MEDIUM=0.60 gate, so the
        # server never calls it — it reaches this engine directly. A router
        # placed in the skill is dead code for every web and voice request.
        #
        # Note `context` is deliberately NOT consulted. The first version
        # skipped the LoRA whenever retrieval had returned anything, assuming
        # a hit meant the turn needed documents. It does not: nearest-neighbour
        # search always returns its nearest neighbours, relevant or not, so
        # "nice work" pulled 2,417 characters of notes and "good morning"
        # 1,633. That guard silently disabled the router for four turns in six.
        #
        # The allowlist is the authority. If a turn is literally "thanks", a
        # retrieval hit is noise and the documents are dropped unused.
        from ai import local_persona
        if local_persona.is_social(user_message, lang_code):
            local = local_persona.reply(user_message)
            if local:
                logger.info(f"persona LoRA handled: {user_message[:40]!r}")
                self._memory.add("assistant", local)
                return local

        if not settings.has_ai():
            self._memory.add("assistant", _OFFLINE_REPLY)
            return _OFFLINE_REPLY

        provider = settings.LLM_PROVIDER
        try:
            if provider == "ollama":
                reply = self._chat_ollama(user_message, lang_code)
            else:
                reply = self._chat_groq(user_message, lang_code)
        except Exception as e:
            logger.error(f"{provider} chat error: {e}")
            self._last_error_message = _explain_failure(e)
            from ai.llm_fallback import try_fallbacks
            messages = [
                {"role": "system",
                 "content": SYSTEM_PROMPT + _capability_block()
                 + _language_clause(lang_code)}
            ] + self._build_history(self._last_user_message())
            reply = try_fallbacks(messages)
            if not reply:
                return self._provider_failure_message(provider)
            logger.info("Recovered via LLM fallback chain")

        # Last line of defence: never let a fabricated success reach the user.
        replacement = _strip_false_claim(reply, user_message)
        if replacement is not None:
            reply = replacement

        self._memory.add("assistant", reply)
        return reply

    def chat_stream(
        self,
        user_message: str,
        on_sentence: Callable[[str], None],
        lang_code: str = "en",
    ) -> str:
        """Stream a reply from the LLM, calling `on_sentence(sentence)` as
        each complete sentence is detected.  Returns the full assembled
        reply (also written to memory).

        Falls back to non-streaming `chat()` for providers that can't stream.
        """
        self._memory.add("user", user_message)
        if not settings.has_ai():
            self._memory.add("assistant", _OFFLINE_REPLY)
            on_sentence(_OFFLINE_REPLY)
            return _OFFLINE_REPLY

        provider = settings.LLM_PROVIDER
        if provider != "groq":
            reply = self.chat(user_message, lang_code=lang_code)
            on_sentence(reply)
            return reply

        spoken: list[str] = []

        def _tracked(sentence: str) -> None:
            spoken.append(sentence)
            on_sentence(sentence)

        try:
            return self._stream_groq(_tracked, lang_code)
        except Exception as e:
            logger.error(f"Groq streaming error: {e}")

            if not spoken:
                from ai.llm_fallback import try_fallbacks
                messages = [
                    {"role": "system",
                     "content": SYSTEM_PROMPT + _capability_block()
                     + _language_clause(lang_code)}
                ] + self._build_history(self._last_user_message())
                reply = try_fallbacks(messages)
                if reply:
                    logger.info("Recovered via LLM fallback chain (stream)")
                    self._memory.add("assistant", reply)
                    on_sentence(reply)
                    return reply
            else:
                partial = " ".join(spoken).strip()
                logger.warning(
                    f"Groq stream died after {len(spoken)} sentence(s); "
                    "keeping the partial reply")
                recovery = "Sorry — I lost my train of thought there."
                on_sentence(recovery)
                self._memory.add("assistant", f"{partial} {recovery}".strip())
                return f"{partial} {recovery}".strip()

            fallback = self._provider_failure_message("groq")
            self._memory.add("assistant", fallback)
            on_sentence(fallback)
            return fallback

    def _stream_groq(self, on_sentence: Callable[[str], None],
                     lang_code: str = "en") -> str:
        client = self._get_groq()
        system = SYSTEM_PROMPT + _capability_block()
        ctx = getattr(self, "_pending_context", None)
        if ctx:
            system += "\n\nCONTEXT FOR THIS QUESTION ONLY\n" + ctx

        messages = [{"role": "system", "content": system}] \
            + self._build_history(self._last_user_message())

        # The language instruction goes on the LAST USER MESSAGE, not in the
        # system prompt — and only in the outgoing request, never in memory.
        #
        # Placement is not cosmetic. With the clause in the system message,
        # Tamil, Hindi and Japanese still complied but Kannada and Malayalam
        # answered in English: a system-level instruction carries less weight
        # for lower-resource languages than one sitting immediately before the
        # question. Appending here gives recency without the ~350 characters
        # accumulating in conversation history every single turn.
        clause = _language_clause(lang_code)
        if clause and messages and messages[-1].get("role") == "user":
            messages = messages[:-1] + [{
                "role": "user",
                "content": messages[-1]["content"] + clause,
            }]
        stream = client.chat.completions.create(
            model=settings.GROQ_CHAT_MODEL,
            messages=messages,
            max_tokens=512,
            temperature=0.7,
            stream=True,
            timeout=15.0,
        )

        buffer = ""
        full = ""
        for chunk in stream:
            try:
                delta = chunk.choices[0].delta.content or ""
            except (AttributeError, IndexError):
                delta = ""
            if not delta:
                continue
            buffer += delta
            full += delta
            while True:
                m = _SENTENCE_END.search(buffer)
                if not m:
                    break
                end = m.end()
                sentence = buffer[:end].strip()
                if len(sentence) < _MIN_FLUSH_CHARS:
                    break
                on_sentence(sentence)
                buffer = buffer[end:]

        tail = buffer.strip()
        if tail:
            on_sentence(tail)

        full = full.strip()
        self._memory.add("assistant", full)
        return full

    # ── Provider-specific ────────────────────────────────────────────────────

    def _chat_groq(self, _user_message: str, lang_code: str = "en") -> str:
        client = self._get_groq()
        system = SYSTEM_PROMPT + _capability_block()
        ctx = getattr(self, "_pending_context", None)
        if ctx:
            system += "\n\nCONTEXT FOR THIS QUESTION ONLY\n" + ctx

        messages = [{"role": "system", "content": system}] \
            + self._build_history(self._last_user_message())

        # The language instruction goes on the LAST USER MESSAGE, not in the
        # system prompt — and only in the outgoing request, never in memory.
        #
        # Placement is not cosmetic. With the clause in the system message,
        # Tamil, Hindi and Japanese still complied but Kannada and Malayalam
        # answered in English: a system-level instruction carries less weight
        # for lower-resource languages than one sitting immediately before the
        # question. Appending here gives recency without the ~350 characters
        # accumulating in conversation history every single turn.
        clause = _language_clause(lang_code)
        if clause and messages and messages[-1].get("role") == "user":
            messages = messages[:-1] + [{
                "role": "user",
                "content": messages[-1]["content"] + clause,
            }]
        response = client.chat.completions.create(
            model=settings.GROQ_CHAT_MODEL,
            messages=messages,
            max_tokens=512,
            temperature=0.7,
            timeout=15.0,
        )
        return (response.choices[0].message.content or "").strip()

    def _chat_ollama(self, _user_message: str, lang_code: str = "en") -> str:
        client = self._get_ollama()
        system = SYSTEM_PROMPT + _capability_block() + _language_clause(lang_code)
        messages = [{"role": "system", "content": system}] \
            + self._build_history(self._last_user_message())
        return client.chat(messages, max_tokens=512, temperature=0.7)

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _last_user_message(self) -> str:
        """The most recent user turn, used as the retrieval query."""
        try:
            for msg in reversed(self._memory.get_history()):
                if msg.get("role") == "user":
                    return msg.get("content", "")
        except Exception:
            pass
        return ""

    _HISTORY_CHAR_BUDGET = 6000

    def _trim_history(self, history: list[dict]) -> list[dict]:
        kept: list[dict] = []
        total = 0
        for msg in reversed(history):
            size = len(msg.get("content", ""))
            if kept and total + size > self._HISTORY_CHAR_BUDGET:
                break
            kept.append(msg)
            total += size
        return list(reversed(kept))

    def _build_history(self, query: str = "") -> list[dict]:
        recent = [
            {"role": msg["role"], "content": msg["content"]}
            for msg in self._memory.get_history()
        ]
        recent = self._trim_history(recent)
        recalled = self._recall_relevant(query, recent)
        if not recalled:
            return recent
        return [{
            "role": "system",
            "content": (
                "Relevant earlier exchanges, retrieved from long-term memory "
                "because they relate to the current message. They are older "
                "than the visible conversation:\n" + recalled
            ),
        }] + recent

    _RECALL_LIMIT = 3
    _MIN_QUERY_WORDS = 2

    def _recall_relevant(self, query: str, recent: list[dict]) -> str:
        if not query or len(query.split()) < self._MIN_QUERY_WORDS:
            return ""
        try:
            from memory import get_memory as _get_store
            store = _get_store()
            rows = store.search_events(query, limit=self._RECALL_LIMIT * 3)
        except Exception as e:
            logger.debug(f"memory recall failed: {e}")
            return ""
        seen = {m["content"].strip().lower() for m in recent}
        lines = []
        for user_text, reply_text in rows:
            if user_text.strip().lower() in seen:
                continue
            snippet = (reply_text or "").strip().replace("\n", " ")
            if len(snippet) > 160:
                snippet = snippet[:160].rsplit(" ", 1)[0] + "..."
            lines.append(f"- You asked: {user_text.strip()}\n  I answered: {snippet}")
            if len(lines) >= self._RECALL_LIMIT:
                break
        return "\n".join(lines)

    def _get_groq(self):
        if self._groq is None:
            from groq import Groq
            self._groq = Groq(api_key=settings.GROQ_API_KEY)
        return self._groq

    def _get_ollama(self):
        if self._ollama is None:
            from ai.local_llm import OllamaClient
            self._ollama = OllamaClient()
        return self._ollama

    def _provider_failure_message(self, provider: str) -> str:
        if provider == "ollama":
            return (
                "I couldn't reach the local Ollama server.  "
                "Try running `ollama serve` and `ollama pull "
                f"{settings.OLLAMA_MODEL}`."
            )
        return self._last_error_message or (
            "I'm having trouble reaching Groq right now.")