# Generated by Claudian.
"""Paraphrase bank — phrasing diversity, not slot diversity.

WHY THIS EXISTS
---------------
The first augmentation pass expanded slots: 36 app names x 8 templates gave
`open_app` 367 examples.  Validation accuracy hit 97%, but a hand-written
holdout of unseen phrasings scored only 68.9% — and the model was confidently
wrong on things like "bring the sound down a bit" -> mute (0.96).

The reason: slot expansion teaches the model many *nouns* but only a handful
of *verbs*.  It learned "open {X}" perfectly and had no representation for
"bring up", "boot up", "fire up", "pull up".  Novel phrasing fell off a cliff.

So this file varies the part that actually differs between real utterances —
the verb and the sentence shape — and keeps slots minimal.  Roughly the
inverse of the first pass.

DISCIPLINE
----------
Nothing here is copied from `training/holdout_eval.py`.  Reusing holdout
phrasings as training data would make the evaluation meaningless.  These are
written in the same spirit but are distinct utterances.
"""

from __future__ import annotations

PARAPHRASES: dict[str, list[str]] = {

    "open_app": [
        "bring up spotify", "pull up chrome", "get slack going",
        "i need terminal", "throw open finder", "spin up docker",
        "load notion", "can you bring up vscode", "put discord on screen",
        "give me the calculator", "i want photoshop open", "switch to safari",
        "jump into figma", "wake up zoom", "show me the notes app",
        "bring the mail app up", "get me into postman", "run xcode",
        "i need to get into obsidian", "open that calendar for me",
        "let me into activity monitor", "surface the messages app",
    ],

    "close_app": [
        "get rid of the chrome window", "make spotify go away",
        "dismiss the slack window", "i'm done with terminal",
        "take discord off my screen", "close out of figma",
        "end the zoom app", "stop running docker", "drop the notes app",
        "wrap up photoshop", "get finder off screen", "toss out the calculator",
        "shut the mail window", "no more safari", "put vscode away",
    ],

    "open_website": [
        "load up youtube in the browser", "send me over to github",
        "point the browser at reddit", "i want to see twitter",
        "bring reddit up in a tab", "navigate to linkedin",
        "hop onto stack overflow", "get netflix on screen",
        "head to amazon", "surf to hacker news", "drop me on medium",
        "open a tab for gmail", "web browser to leetcode",
    ],

    "volume": [
        "crank the sound", "pump up the audio", "bring the sound down",
        "ease the volume back", "nudge the volume up", "knock it down a notch",
        "sound is too quiet", "i can barely hear it", "way too loud",
        "dial the audio back", "push the volume higher", "drop the sound a bit",
        "make the audio softer", "boost the sound", "turn the audio to forty",
        "set the sound level to eighty", "audio level twenty",
        "put the sound at thirty five", "just a bit louder", "quieter please",
    ],

    "brightness": [
        "screen is too dim", "the display is blinding me",
        "crank the screen brightness", "ease the brightness down",
        "make the display darker", "brighten this screen up",
        "screen brightness to forty", "dial the display back",
        "too dark to read", "turn the panel brightness up",
    ],

    "mute": [
        "kill the sound", "cut the audio", "no sound at all",
        "shut the speakers up", "silence everything", "audio off please",
        "bring the sound back", "let me hear again", "turn audio back on",
        "restore the speakers", "un silence it",
    ],

    "battery": [
        "how much power is left", "am i about to die", "is this thing charging",
        "power remaining", "do i need to find a charger",
        "whats my charge at", "battery running low", "am i on mains power",
        "how long till the battery dies", "check the charge",
    ],

    "wifi": [
        "which router am i on", "what wireless am i connected to",
        "tell me the network im using", "am i on the internet",
        "name of the wifi please", "which access point",
        "what connection is this", "wifi status",
    ],

    "screenshot": [
        "capture whats on the display", "grab an image of the screen",
        "save what im looking at", "snap the display",
        "picture of my screen please", "record the screen as an image",
        "shoot whats showing", "screen image",
    ],

    "lock_screen": [
        "im stepping out lock this", "secure the display",
        "put the lock on", "lock me out", "engage the screen lock",
        "protect my screen",
    ],

    "empty_trash": [
        "wipe the trash", "flush the bin", "get rid of the deleted files",
        "clean out the wastebasket", "dump the trash for good",
    ],

    "music": [
        "throw on a track", "put some tunes on", "i wanna hear something",
        "start the tunes", "get some sound going", "queue up a song",
        "hit play", "resume the track", "hold the music",
        "stop the track", "jump to the next one", "go back a song",
        "skip ahead", "play something upbeat", "put on background music",
    ],

    "search_local": [
        "dig up a file on this machine", "hunt for a document on my disk",
        "where did i stash that file", "track down a folder here",
        "look through my drive for a pdf", "find something saved locally",
        "scan my mac for that document",
    ],

    "web_search": [
        "look that up online", "run a search on the internet",
        "check the web for me", "do an online lookup",
        "search the net for reviews", "find that on google",
        "web lookup please", "hunt online for prices",
    ],

    "news_headlines": [
        "catch me up on whats going on", "brief me on world events",
        "anything happening today", "whats going on out there",
        "give me the rundown on the news", "fill me in on current events",
        "read the top stories", "whats breaking right now",
        "update me on the world", "any developments today",
    ],

    "define_word": [
        "give me the dictionary meaning of stoic",
        "spell out what tenacious means", "explain the word candour",
        "dictionary definition of lucid", "what would you call the meaning of astute",
        "the word prudent means what", "look up the word brevity",
    ],

    "wikipedia_lookup": [
        "give me background on winston churchill",
        "i want to read up on the amazon", "fill me in on who galileo was",
        "some context on the renaissance", "brief me on the moon landing",
        "background on the pyramids please", "give me the story of the titanic",
        "what's the deal with the bermuda triangle",
        "i'd like to learn about volcanoes",
    ],

    "coding_assistant": [
        "my script keeps throwing an index error",
        "show me how to merge two dictionaries",
        "whats the point of a virtual environment",
        "walk me through github actions",
        "this loop runs way too slow how do i fix it",
        "keep getting a key error in my dict",
        "teach me about pointers", "help me understand inheritance",
        "whats wrong with my sql query", "how would you structure a flask app",
        "is there a cleaner way to write this if statement",
        "my api call returns 401 what does that mean",
        "explain what a lambda function does",
        "when should i use a set instead of a list",
        "how do i make this function asynchronous",
        "whats the deal with mutable default arguments",
    ],

    "system_stats": [
        "is something eating all my memory", "give me a readout on the processor",
        "hows the machine holding up", "whats the load like",
        "am i low on disk", "how hard is the cpu working",
        "check resources for me", "whats my ram situation",
        "is the drive nearly full", "machine health check",
    ],

    "jokes": [
        "lighten the mood", "crack me up", "give me something funny",
        "i need a laugh", "amuse me", "got anything humorous",
        "be funny for a second", "hit me with something silly",
    ],

    "remember": [
        "jot down that the spare key is under the mat",
        "hang on to this for me my badge is 8842",
        "file this away my desk is on floor two",
        "keep this in mind i owe rahul money",
        "log that the car service is due in march",
        "hold onto the fact that my passport expires soon",
        "put it on record that i finished the report",
    ],

    "recall": [
        "what was that thing i mentioned earlier",
        "dig up what i told you before", "bring back what i saved",
        "surface my old notes", "what have you got stored on me",
        "retrieve what i said about the car",
        "whats in your memory about my schedule",
    ],

    "whatsapp_send": [
        "shoot priya a whatsapp", "fire off a whatsapp to rahul",
        "ping mom on whatsapp", "drop john a whatsapp message",
        "get a whatsapp over to sarah",
    ],

    "time_date": [
        "got a clock on you", "give me the current hour",
        "how far into the day are we", "whats on the calendar today",
        "which date are we on", "remind me what day this is",
        "is it still morning", "how much of the day is left",
    ],

    "shutdown_jarvis": [
        "alright thats it for now", "you can rest",
        "im done talking to you", "stop paying attention",
        "take a break jarvis", "power yourself down",
        "we're finished here", "dismiss yourself",
    ],

    "shutdown_system": [
        "power the whole machine down", "kill the computer entirely",
        "switch the laptop off", "close everything down and power off",
    ],

    "restart_system": [
        "give the mac a reboot", "cycle the machine",
        "boot it back up fresh", "power cycle the laptop",
    ],

    "conversation": [
        "do you ever wonder about things", "im second guessing myself",
        "whats your take on it", "been a long week",
        "appreciate you sticking around", "i could use some company",
        "not feeling great today", "things are looking up",
        "you ever get lonely", "whats on your mind",
        "just wanted to chat", "keep me company for a bit",
        "i dont really know what im doing", "everything feels heavy lately",
        "tell me im doing okay", "whats something worth knowing",
        "do you actually understand me", "how do you decide what to say",
        "i got some good news today", "feeling pretty low",
        "you're surprisingly good at this", "what would you do in my place",
        "im doubting the whole plan", "talk some sense into me",
        "nothing much just checking in", "hey there you",
        "im back", "missed talking to you", "that was helpful thanks",
        "youve been really useful lately",
    ],
}


def paraphrase_count() -> int:
    return sum(len(v) for v in PARAPHRASES.values())


if __name__ == "__main__":
    print(f"Paraphrase bank: {paraphrase_count()} utterances "
          f"across {len(PARAPHRASES)} intents")
    for k, v in sorted(PARAPHRASES.items(), key=lambda kv: -len(kv[1])):
        print(f"  {k:20} {len(v):3}")
