# Generated by Claudian.
"""LLM-backed intent classifier — used *only* as a fallback when no skill
matches locally with high confidence.

Previously this file also orchestrated the hand-rolled local classifier.
That's now redundant — each skill owns its own `match()` method.  This
module just asks Groq: "here are the available skills with descriptions —
which one handles this utterance, and what entities does it need?"
"""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING, Optional

from config import settings
from utils.logger import get_logger

if TYPE_CHECKING:
    from skills._registry import SkillRegistry

logger = get_logger(__name__)


_SYSTEM_PROMPT = (
    "You are a precise intent classifier for a macOS voice assistant.  "
    "You will be given a user command and a list of skills with descriptions.  "
    "Pick exactly ONE skill that best handles the command and extract the relevant "
    "entities.  Return ONLY valid JSON, no commentary or Markdown.  "
    'Shape: {"intent": "<skill_name>", "entities": {...}, "confidence": 0.0-1.0}'
)


# Robust JSON extraction — tolerates models that wrap JSON in ```json …``` or
# prepend explanation text.
_JSON_OBJECT_RE = re.compile(r"\{.*\}", re.DOTALL)


class IntentClassifier:
    def __init__(self, registry: "SkillRegistry"):
        self._registry = registry
        self._groq = None  # lazy
        self._ollama = None  # lazy

    # ── Public ───────────────────────────────────────────────────────────────

    def classify(self, text: str) -> Optional[dict]:
        """Return {'intent': <skill_name>, 'entities': {...}, 'confidence': float}
        or None if the LLM isn't available / couldn't classify."""
        if not settings.has_ai():
            return None
        try:
            raw = self._call_llm(text)
        except Exception as e:
            logger.error(f"LLM classification failed: {e}")
            return None
        if not raw:
            return None
        parsed = self._parse_json(raw)
        if parsed is None:
            logger.warning(f"Groq classifier returned unparseable JSON: {raw!r}")
            return None

        intent = parsed.get("intent") or ""
        if self._registry.by_name(intent) is None:
            # LLM hallucinated a skill name; fall back to conversation
            logger.debug(f"Groq suggested unknown skill '{intent}' — ignoring")
            return None

        return {
            "intent": intent,
            "entities": parsed.get("entities") or {},
            "confidence": float(parsed.get("confidence", 0.7)),
        }

    # ── Internal ─────────────────────────────────────────────────────────────

    def _build_prompt(self, text: str) -> str:
        return (
            "Available skills:\n"
            f"{self._registry.describe_for_llm()}\n\n"
            f'User command: "{text.strip()}"\n\n'
            "Return the JSON classification now."
        )

    def _parse_json(self, raw: str) -> Optional[dict]:
        m = _JSON_OBJECT_RE.search(raw)
        if not m:
            return None
        try:
            return json.loads(m.group(0))
        except json.JSONDecodeError:
            return None

    def _call_llm(self, text: str) -> Optional[str]:
        """Provider-aware LLM call.  Returns the raw model text or None."""
        provider = settings.LLM_PROVIDER
        prompt = self._build_prompt(text)

        if provider == "ollama":
            client = self._get_ollama()
            return client.chat(
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=200,
                temperature=0.0,
            )

        # Default: Groq
        client = self._get_groq()
        response = client.chat.completions.create(
            model=settings.GROQ_FAST_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            max_tokens=200,
            temperature=0.0,
            timeout=5.0,
        )
        return response.choices[0].message.content or ""

    def _get_groq(self):
        if self._groq is None:
            from groq import Groq
            self._groq = Groq(api_key=settings.GROQ_API_KEY)
        return self._groq

    def _get_ollama(self):
        if self._ollama is None:
            from ai.local_llm import OllamaClient
            self._ollama = OllamaClient()
        return self._ollama
