# Generated by Claudian.
"""Fallback LLM chain — what Jarvis tries when the primary provider dies.

Why this exists
---------------
Jarvis had exactly one path to an LLM: a single `GROQ_API_KEY`. If Groq
rate-limited, timed out, or had an outage, the user got
"I'm having trouble reaching Groq" and the conversation was over. One key
was a single point of failure for the whole assistant.

Design constraint: **do not slow down the happy path.**
Jarvis's top blocker is responsiveness, and Groq is fast because of its
hardware. So nothing here runs unless the primary has *already* failed.
This is a safety net, not a router — Groq stays the direct, unwrapped,
default path.

The chain, in order:

  1. FreeLLMAPI router   — set FREELLMAPI_BASE_URL to enable.
                           Aggregates ~34 free provider tiers behind one
                           OpenAI-compatible endpoint with its own internal
                           failover. See github.com/tashfeenahmed/freellmapi
  2. Local Ollama        — always tried last. Works with no network at all.

Each tier gets a short timeout. A slow fallback is barely better than a dead
one when someone is waiting for a voice reply.

Configuration (all optional, all via .env):

    FREELLMAPI_BASE_URL=http://localhost:3001/v1
    FREELLMAPI_API_KEY=freellmapi-...
    FREELLMAPI_MODEL=auto
    LLM_FALLBACK_ENABLED=true        # set false to disable the whole chain
    LLM_FALLBACK_TIMEOUT=12
"""

from __future__ import annotations

import logging
import os
from typing import Any

logger = logging.getLogger(__name__)

# A fallback that takes 30s is not a fallback — the user has given up by then.
DEFAULT_TIMEOUT = float(os.getenv("LLM_FALLBACK_TIMEOUT", "12"))


def _enabled() -> bool:
    return os.getenv("LLM_FALLBACK_ENABLED", "true").strip().lower() not in (
        "0", "false", "no", "off",
    )


# ── Tier 1: FreeLLMAPI router ────────────────────────────────────────────────

def _try_freellmapi(messages: list[dict[str, Any]]) -> str | None:
    """Route through a local FreeLLMAPI container, if one is configured.

    Speaks the OpenAI wire format, so the existing `openai` client works —
    only the base_url changes.
    """
    base_url = os.getenv("FREELLMAPI_BASE_URL", "").strip()
    if not base_url:
        return None  # not configured; skip silently

    try:
        from openai import OpenAI
    except ImportError:
        logger.debug("openai package unavailable — skipping FreeLLMAPI tier")
        return None

    try:
        client = OpenAI(
            base_url=base_url,
            # The router requires *a* key but ignores its value when it is
            # only serving localhost.
            api_key=os.getenv("FREELLMAPI_API_KEY", "not-needed"),
            timeout=DEFAULT_TIMEOUT,
        )
        response = client.chat.completions.create(
            model=os.getenv("FREELLMAPI_MODEL", "auto"),
            messages=messages,
            max_tokens=512,
            temperature=0.7,
        )
        reply = (response.choices[0].message.content or "").strip()
        if reply:
            logger.info("Fallback hit: FreeLLMAPI router answered")
            return reply
    except Exception as exc:  # noqa: BLE001 — a dead tier must not raise
        logger.warning(f"FreeLLMAPI fallback failed: {exc}")
    return None


# ── Tier 2: local Ollama ─────────────────────────────────────────────────────

def _try_ollama(messages: list[dict[str, Any]]) -> str | None:
    """Last resort. No network required, so this is the true floor.

    Note: on an 8 GB machine, keep OLLAMA_MODEL small (llama3.2:3b or
    qwen2.5:3b). A 7B model will swap to disk and take far longer than the
    timeout allows.
    """
    try:
        from ai.local_llm import OllamaClient
    except ImportError as exc:
        logger.debug(f"Ollama client unavailable: {exc}")
        return None

    try:
        # OllamaClient defaults to a 60s timeout — far too long when someone
        # is waiting for a spoken reply. Hold it to the fallback budget.
        client = OllamaClient(timeout=int(DEFAULT_TIMEOUT))
        reply = client.chat(messages)
        if isinstance(reply, str) and reply.strip():
            logger.info("Fallback hit: local Ollama answered")
            return reply.strip()
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"Ollama fallback failed: {exc}")
    return None


# ── Public ───────────────────────────────────────────────────────────────────

def try_fallbacks(messages: list[dict[str, Any]]) -> str | None:
    """Walk the fallback chain. Returns a reply, or None if every tier failed.

    Never raises. The caller already has a user-facing failure message for
    the None case, and a fallback chain that can itself throw would be worse
    than no chain at all.
    """
    if not _enabled():
        return None
    if not messages:
        return None

    for tier in (_try_freellmapi, _try_ollama):
        try:
            reply = tier(messages)
        except Exception as exc:  # noqa: BLE001 — belt and braces
            logger.warning(f"Fallback tier {tier.__name__} raised: {exc}")
            continue
        if reply:
            return reply

    logger.error("Every LLM fallback tier failed")
    return None


def status() -> dict[str, Any]:
    """Report which tiers are configured. Used by preflight/diagnostics."""
    return {
        "enabled": _enabled(),
        "freellmapi": bool(os.getenv("FREELLMAPI_BASE_URL", "").strip()),
        "ollama": True,  # always attempted; availability checked at call time
        "timeout_seconds": DEFAULT_TIMEOUT,
    }
