# Generated by Claudian.
"""Route short social turns to the local JARVIS persona LoRA.

WHY
---
Roughly half of JARVIS's logged conversation is not questions — it is "thank
you", "hey", "got it", "good morning". Those cost a full Groq round trip
(~1.29s) to produce a sentence the model did not need any knowledge to write.

A 1B LoRA fine-tuned on JARVIS's own replies answers them in ~0.3-0.6s, in the
right voice, with no network. Measured: 0.36s local against 1.29s Groq.

WHAT THIS IS NOT
----------------
Not a replacement for Groq. The 1B model is much weaker on anything requiring
knowledge, and it leaks markdown headings into long answers — which matters
because JARVIS speaks its replies aloud. So the split is deliberately lopsided:
a *tight allowlist* goes local and everything else, including anything
unrecognised, goes to Groq. An unknown utterance is a knowledge question until
proven otherwise.

FAILURE POLICY
--------------
Any problem — server down, timeout, empty reply, non-English — returns None and
the caller falls through to Groq. The LoRA server is an optimisation; JARVIS
must work identically when it is not running.
"""

from __future__ import annotations

import os
import re

from utils.logger import get_logger

logger = get_logger(__name__)

PERSONA_URL = os.getenv("JARVIS_PERSONA_URL", "http://127.0.0.1:8421")
PERSONA_ENABLED = os.getenv("JARVIS_PERSONA", "1") != "0"

# Short enough to be a pleasantry. "explain HNSW indexes" is three words, so
# length alone is not a safe test — it only narrows what the patterns below
# then have to confirm.
_MAX_WORDS = 7

# Deliberately an allowlist. Each entry is a complete social turn, anchored at
# both ends, so a question that merely starts with a greeting ("hey, what is
# HNSW") does not match and goes to Groq.
_SOCIAL = re.compile(
    r"^\s*(?:"
    r"(?:hi|hey|hello|yo|hiya|heya)(?:\s+(?:there|jarvis|boss))?"
    r"|good\s+(?:morning|afternoon|evening|night)(?:\s+jarvis)?"
    r"|(?:thank\s*you|thanks|thanx|thx|ty)(?:\s+(?:so\s+much|a\s+lot|jarvis|boss|man))?"
    r"|(?:much\s+)?appreciated|appreciate\s+it"
    r"|(?:ok|okay|kk|cool|nice|great|awesome|perfect|sweet|alright|all\s+right)"
    r"|(?:got\s+it|gotcha|understood|makes\s+sense|fair\s+enough|no\s+worries)"
    r"|(?:yes|yeah|yep|yup|no|nope|nah|sure)"
    r"|(?:bye|goodbye|see\s+you|see\s+ya|later|good\s*night|cya)"
    r"|(?:how\s+are\s+you|how's\s+it\s+going|what's\s+up|sup|how\s+you\s+doing)"
    r"|(?:you're\s+welcome|my\s+bad|sorry|excuse\s+me)"
    r"|(?:well\s+done|good\s+job|nice\s+work|thumbs\s+up)"
    r")"
    r"[\s.!,?]*$",
    re.I,
)


def is_social(text: str, lang_code: str = "en") -> bool:
    """True only for turns the LoRA was actually trained on.

    English only — the adapter saw no other language, and JARVIS genuinely
    supports several, so a Tamil greeting must still reach Groq.
    """
    if not PERSONA_ENABLED or not text:
        return False
    if not lang_code.lower().startswith("en"):
        return False
    if len(text.split()) > _MAX_WORDS:
        return False
    return bool(_SOCIAL.match(text.strip()))


def reply(text: str, timeout: float = 2.5) -> str | None:
    """Ask the local persona model. None means 'caller should use Groq'.

    The timeout is short on purpose. If the local model cannot beat Groq's
    ~1.3s there is no reason to be using it, so a slow local answer should
    lose to the cloud rather than delay the user past what Groq would have cost.
    """
    if not PERSONA_ENABLED:
        return None
    try:
        import requests

        r = requests.post(
            f"{PERSONA_URL}/v1/chat/completions",
            json={"messages": [{"role": "user", "content": text}],
                  "max_tokens": 60},
            timeout=timeout,
        )
        if r.status_code != 200:
            logger.debug(f"persona server HTTP {r.status_code}")
            return None
        out = (r.json()["choices"][0]["message"]["content"] or "").strip()
        if not out:
            return None
        # The adapter leaks markdown on longer generations. These turns are
        # short so it rarely fires, but JARVIS speaks its output aloud and an
        # asterisk read literally is worse than a cloud round trip.
        if any(m in out for m in ("**", "##", "\n- ", "\n* ")):
            logger.debug("persona reply contained markup — deferring to Groq")
            return None
        return out
    except Exception as e:
        logger.debug(f"persona server unavailable: {e}")
        return None
