# Generated by Claudian.
"""Publishes the loudness of whatever Jarvis is currently saying.

The desktop visualiser needs to move with the voice, which means it needs
amplitude, not just the coarse idle/speaking state in core/voice_state.py.

WHERE THE SIGNAL COMES FROM
---------------------------
The ElevenLabs engine already streams raw 16-bit PCM straight to the sound
card, so the exact samples being played are in hand. Computing an RMS level
per chunk costs one numpy reduction over ~2000 samples — negligible next to
the network and audio I/O around it.

WHY A SEPARATE CHANNEL FROM voice_state
---------------------------------------
State changes a handful of times per utterance; level changes ~10x a second.
Pushing level through the same atomic JSON write would mean hundreds of
temp-file creations per reply. This writes a single short line instead, and
a torn read is harmless: the reader takes the last good float and a missed
frame is invisible at 60fps.
"""

from __future__ import annotations

import math
import os
import threading
from pathlib import Path

from utils.logger import get_logger

logger = get_logger(__name__)

LEVEL_PATH = Path(__file__).parent.parent / "data" / "level"

# Smoothing. Raw RMS is jittery enough to look like noise rather than speech;
# an asymmetric filter that rises fast and falls slowly reads as natural
# motion — quick attack on a consonant, gentle decay through a vowel tail.
ATTACK = 0.55
DECAY = 0.15

_lock = threading.Lock()
_smoothed = 0.0


def _write(value: float) -> None:
    try:
        LEVEL_PATH.parent.mkdir(parents=True, exist_ok=True)
        # Plain float, no atomic rename: at ~10 writes/second the temp-file
        # churn would cost more than a torn read, which the reader ignores.
        with open(LEVEL_PATH, "w") as f:
            f.write(f"{value:.4f}")
    except Exception as e:
        logger.debug(f"level write failed: {e}")


def publish_pcm(chunk: bytes) -> None:
    """Measure a chunk of 16-bit mono PCM and publish its smoothed level."""
    global _smoothed
    if not chunk or len(chunk) < 2:
        return

    try:
        import numpy as np

        samples = np.frombuffer(chunk[: len(chunk) - (len(chunk) % 2)], dtype=np.int16)
        if samples.size == 0:
            return
        rms = float(np.sqrt(np.mean(samples.astype(np.float32) ** 2))) / 32768.0
    except Exception:
        return

    # Speech RMS sits low in the range; a square root spreads the quiet end
    # so normal talking fills the visual range instead of barely twitching.
    level = min(1.0, math.sqrt(max(0.0, rms)) * 1.8)

    with _lock:
        coeff = ATTACK if level > _smoothed else DECAY
        _smoothed += (level - _smoothed) * coeff
        out = _smoothed

    _write(out)


def reset() -> None:
    """Decay to silence. Called when playback stops."""
    global _smoothed
    with _lock:
        _smoothed = 0.0
    _write(0.0)


def current() -> float:
    with _lock:
        return _smoothed
