# Generated by Claudian.
"""Decide whether a transcription is Jarvis hearing itself.

THE PROBLEM
-----------
Barge-in means listening while the speakers are playing, so the microphone
picks up Jarvis's own voice. Without a way to reject that, the first thing it
"hears" is itself, which it treats as a command, which produces a reply,
which it hears again — a runaway loop. That risk is why the mic is normally
muted outright during TTS.

THE APPROACH
------------
Proper acoustic echo cancellation needs the reference signal and an adaptive
filter (speexdsp, webrtc-audio-processing). Both are heavy native
dependencies, and neither is necessary here, because we have something an
ordinary AEC does not: **the exact text being spoken**.

If the transcription substantially overlaps the words currently coming out of
the speakers, it is almost certainly echo. If it does not, it is you.

BIAS
----
Deliberately tuned to prefer false negatives. Missing a barge-in costs you one
repeated attempt. Mistaking your voice for echo is harmless. Mistaking echo
for *your voice* starts the feedback loop. So when uncertain, we call it echo.
"""

from __future__ import annotations

import re
from difflib import SequenceMatcher

_WORD = re.compile(r"[a-z0-9']+")

# Fraction of heard words that must also appear in the spoken text before we
# call it echo. 0.5 means "half of what I heard, I am currently saying".
OVERLAP_THRESHOLD = 0.5

# Whole-string similarity that flags echo regardless of overlap, for short
# utterances where token overlap is a poor signal.
SIMILARITY_THRESHOLD = 0.7

# Very common words carry no evidence either way — "the" appearing in both
# means nothing. Excluded from the overlap calculation.
_STOPWORDS = {
    "a", "an", "the", "is", "it", "to", "of", "and", "or", "in", "on",
    "at", "for", "i", "you", "your", "im", "its", "that", "this", "was",
    "are", "be", "am", "s", "t",
}


def _tokens(text: str) -> list[str]:
    return [w for w in _WORD.findall(text.lower()) if w not in _STOPWORDS]


def is_echo(heard: str, spoken: str | None) -> bool:
    """True if `heard` looks like the microphone picking up `spoken`.

    `spoken` is whatever TTS is currently playing, or None when silent.
    """
    if not heard or not heard.strip():
        return True  # nothing usable — never treat as a barge-in
    if not spoken or not spoken.strip():
        return False  # nothing playing, so nothing to echo

    heard_tokens = _tokens(heard)
    spoken_tokens = set(_tokens(spoken))

    if not heard_tokens:
        # Heard only stopwords. No evidence it is a real command.
        return True

    overlap = sum(1 for t in heard_tokens if t in spoken_tokens)
    if overlap / len(heard_tokens) >= OVERLAP_THRESHOLD:
        return True

    # Short utterances defeat token overlap ("go on" vs "going on"), so fall
    # back to whole-string similarity.
    ratio = SequenceMatcher(None, heard.lower().strip(), spoken.lower().strip()).ratio()
    if ratio >= SIMILARITY_THRESHOLD:
        return True

    # Also check against any single sentence of the spoken text: TTS may be
    # mid-paragraph, so the mic only caught one clause of a longer reply.
    for sentence in re.split(r"(?<=[.!?])\s+", spoken):
        sentence = sentence.strip()
        if len(sentence) < 8:
            continue
        if SequenceMatcher(None, heard.lower().strip(), sentence.lower()).ratio() >= SIMILARITY_THRESHOLD:
            return True

    return False


def looks_like_interrupt(heard: str) -> bool:
    """True for the short commands people use to cut someone off.

    These bypass the length checks elsewhere: "stop" is a legitimate and very
    common barge-in even though it is a single short word.
    """
    cleaned = heard.lower().strip().strip(".,!?")
    return cleaned in {
        "stop", "stop it", "shut up", "quiet", "be quiet", "enough",
        "wait", "hold on", "hang on", "cancel", "nevermind", "never mind",
        "shush", "silence", "pause", "no stop", "okay stop", "thats enough",
        "that's enough",
    }
