# Generated by Claudian.
"""Shared 'is Jarvis currently speaking?' flag.

Used to:
  1. Prevent the wake-word listener from re-triggering on Jarvis's own
     TTS output (self-hearing / feedback loop).
  2. Let any thread query speaking state without poking into TTS internals.

Thread-safe via threading.Event.  Cheap to query (no lock contention).
"""

from __future__ import annotations

import threading
import time

_event = threading.Event()
# Brief settle window after TTS ends — lets the audio buffer drain so the
# tail of "say" doesn't get captured by the next listen() call.
_SETTLE_MS = 150


def set_speaking() -> None:
    _event.set()


def clear_speaking() -> None:
    _event.clear()


def is_speaking() -> bool:
    return _event.is_set()


def wait_until_silent(poll_interval: float = 0.05) -> None:
    """Block (cheaply) until Jarvis stops speaking, then add a short settle."""
    while _event.is_set():
        time.sleep(poll_interval)
    time.sleep(_SETTLE_MS / 1000)
