# Generated by Claudian.
"""Pluggable speech engines.

`TextToSpeech` owns queueing, ordering, `speaking_state` and barge-in. This
module owns only "turn this string into sound", so a new voice provider can
be added without touching any of that machinery.

ENGINES
-------
MacSayEngine        macOS `say`. Zero latency, offline, robotic.
ElevenLabsEngine    Streaming neural TTS. Far better voice, network-bound.

ON "LATENCY FREE"
-----------------
A network TTS call cannot be zero-latency — the audio is synthesised on
someone else's GPU. What it can be is *imperceptible*, and four things get it
there:

  1. Streaming. Playback starts on the first chunk instead of waiting for the
     whole clip. This is the big one: it converts "wait for the sentence" into
     "wait for the first syllable".
  2. Flash v2.5 (~75ms model inference), roughly half the credits of the
     multilingual model.
  3. Raw PCM output rather than MP3, so there is no decode step between bytes
     arriving and the speaker moving.
  4. A disk cache. Jarvis repeats itself constantly — greetings,
     acknowledgements, "opening Chrome". Those replay from disk at genuinely
     zero network latency.

And when the network is slow or absent, it falls back to `say` rather than
leaving you in silence.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import threading
import time
from pathlib import Path
from typing import Callable, Optional

from utils.logger import get_logger
from voice.audio_lock import portaudio_lock
from voice import audio_level

logger = get_logger(__name__)

# Stop-check callback: engines poll this between chunks so barge-in can cut
# playback off mid-sentence.
StopCheck = Callable[[], bool]


class SpeechEngine:
    """Interface every engine implements."""

    name = "base"

    def speak(self, text: str, should_stop: Optional[StopCheck] = None) -> bool:
        """Render and play `text`. Returns True if it completed normally."""
        raise NotImplementedError

    def stop(self) -> None:
        """Interrupt playback immediately."""
        raise NotImplementedError

    def available(self) -> bool:
        return True


# ── macOS `say` ──────────────────────────────────────────────────────────────

class MacSayEngine(SpeechEngine):
    name = "say"

    def __init__(self, voice: str, rate: int):
        self.voice = voice
        self.rate = rate
        self._proc: subprocess.Popen | None = None
        self._lock = threading.Lock()

    def speak(self, text: str, should_stop: Optional[StopCheck] = None) -> bool:
        proc = subprocess.Popen(
            ["say", "-v", self.voice, "-r", str(self.rate), text]
        )
        with self._lock:
            self._proc = proc
        try:
            proc.wait()
            return proc.returncode == 0
        finally:
            with self._lock:
                if self._proc is proc:
                    self._proc = None

    def stop(self) -> None:
        with self._lock:
            if self._proc is not None and self._proc.poll() is None:
                self._proc.terminate()

    def available(self) -> bool:
        return os.path.exists("/usr/bin/say") or os.path.exists("/bin/say")


# ── ElevenLabs ───────────────────────────────────────────────────────────────

API_URL = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream"

# pcm_22050 keeps the payload small and needs no decoding — bytes off the
# socket go straight to the sound card.
OUTPUT_FORMAT = "pcm_22050"
SAMPLE_RATE = 22050

# Their fastest model. Turbo is functionally equivalent but slower on
# average, and ElevenLabs recommends Flash over Turbo in all cases.
DEFAULT_MODEL = "eleven_flash_v2_5"

# 0-4; higher trades quality for latency. 3 is aggressive without disabling
# the text normaliser (4 does, which mangles numbers and abbreviations —
# unacceptable when half of what Jarvis says is times, percentages and dates).
STREAMING_LATENCY = 3

CACHE_DIR = Path(__file__).parent.parent / "data" / "tts_cache"
CACHE_MAX_BYTES = 200 * 1024 * 1024  # 200MB of PCM is a lot of phrases

CHUNK_BYTES = 4096

# ~40ms of silence written after each utterance. Closing the device
# immediately after the last sample cuts the hardware buffer mid-waveform,
# which is audible as a click.
SILENCE_PAD = b"\x00" * int(SAMPLE_RATE * 0.04) * 2
REQUEST_TIMEOUT = 30
CONNECT_TIMEOUT = 6

# How long speak() will wait for the startup warm-up before going ahead anyway.
# Long enough to cover a normal handshake + first synthesis, short enough that
# a dead network costs this once rather than on every utterance.
WARM_WAIT_SEC = 4.0


class ElevenLabsEngine(SpeechEngine):
    name = "elevenlabs"

    def __init__(self, api_key: str, voice_id: str,
                 model: str = DEFAULT_MODEL, cache: bool = True):
        self.api_key = api_key
        self.voice_id = voice_id
        self.model = model
        self.cache_enabled = cache

        self._stop_flag = threading.Event()
        self._audio = None       # lazy PyAudio instance
        self._stream = None
        self._lock = threading.Lock()

        # "Is it safe to use the network yet?" speak() waits on this.
        #
        # Starts SET — i.e. nothing to wait for. Only build_engine(), which
        # actually launches a warm-up thread, clears it first. An engine
        # constructed directly (warm_voice_cache.py, tests) therefore never
        # stalls: if nobody is warming, there is nothing to wait for, and a
        # default of "not ready" would have made every such utterance pay the
        # full WARM_WAIT_SEC for a warm-up that was never coming.
        self.warm_ready = threading.Event()
        self.warm_ready.set()

        # Persistent connection. Without this every utterance pays a fresh
        # DNS lookup and TLS handshake — measured at 4.7s cold versus ~450ms
        # on a warm socket, which is the difference between unusable and fine.
        self._session = None

        if self.cache_enabled:
            CACHE_DIR.mkdir(parents=True, exist_ok=True)

    # ── Availability ─────────────────────────────────────────────────────

    def available(self) -> bool:
        if not self.api_key or not self.voice_id:
            return False
        try:
            import pyaudio  # noqa: F401
            import requests  # noqa: F401
        except ImportError:
            return False
        return True

    # ── Cache ────────────────────────────────────────────────────────────

    def _get_session(self):
        import requests
        with self._lock:
            if self._session is None:
                self._session = requests.Session()
                self._session.headers.update({
                    "xi-api-key": self.api_key,
                    "Content-Type": "application/json",
                    "Accept": "audio/pcm",
                })
            return self._session

    def warm_connection(self) -> float | None:
        """Open the TLS connection ahead of the first real utterance.

        Called at startup so the greeting doesn't eat the handshake cost.
        Returns milliseconds taken, or None on failure.
        """
        try:
            t0 = time.perf_counter()
            session = self._get_session()
            # A HEAD against the API root is enough to establish the socket
            # without spending any character quota.
            session.head("https://api.elevenlabs.io/v1/models", timeout=(CONNECT_TIMEOUT, 10))
            return (time.perf_counter() - t0) * 1000
        except Exception as e:
            logger.debug(f"connection warm-up failed: {e}")
            return None

    def warm_synthesis(self) -> float | None:
        """Make one real synthesis round-trip so the first spoken line doesn't.

        `warm_connection()` only opens a socket to /v1/models. That warms TLS
        and nothing else: measured, the first real utterance still took 3250ms
        to first audio against 312ms for the one after it. Sending a genuine
        synthesis request first brings the first spoken line to ~550ms.

        Deliberately not routed through `warm_cache()`, which skips any phrase
        already on disk. That would warm the path on the very first launch and
        then silently stop warming it on every launch afterwards.

        Costs two characters of quota per start. The audio is discarded.
        """
        try:
            t0 = time.perf_counter()
            resp = self._get_session().post(
                API_URL.format(voice_id=self.voice_id),
                params={"output_format": OUTPUT_FORMAT},
                json={"text": "ok", "model_id": self.model},
                timeout=(CONNECT_TIMEOUT, REQUEST_TIMEOUT),
            )
            if resp.status_code != 200:
                logger.debug(f"synthesis warm-up HTTP {resp.status_code}")
                return None
            return (time.perf_counter() - t0) * 1000
        except Exception as e:
            logger.debug(f"synthesis warm-up failed: {e}")
            return None

    def _cache_path(self, text: str) -> Path:
        key = hashlib.sha256(
            f"{self.voice_id}|{self.model}|{text}".encode()
        ).hexdigest()[:20]
        return CACHE_DIR / f"{key}.pcm"

    def _prune_cache(self) -> None:
        """Keep the cache under its size cap, oldest-accessed first."""
        try:
            files = sorted(
                CACHE_DIR.glob("*.pcm"), key=lambda p: p.stat().st_atime
            )
            total = sum(f.stat().st_size for f in files)
            while total > CACHE_MAX_BYTES and files:
                victim = files.pop(0)
                total -= victim.stat().st_size
                victim.unlink(missing_ok=True)
        except Exception as e:
            logger.debug(f"TTS cache prune failed: {e}")

    # ── Playback ─────────────────────────────────────────────────────────

    def _open_stream(self, _retry: bool = True):
        """Open the output stream, re-initialising PortAudio if it went stale.

        PortAudio enumerates devices ONCE, at Pa_Initialize(), and this engine
        caches a single PyAudio instance for the life of the process. When the
        default output device changes afterwards — Bluetooth speakers
        connecting or dropping, a monitor sleeping, another app taking the
        device exclusively — the cached handle still describes the old
        topology and every open fails with:

            [Errno -9996] Invalid output device (no default output device)

        Previously it never recovered: one device change and the neural voice
        was gone for the rest of the session, silently falling back to the
        system voice on every single utterance.

        So a device error tears the instance down and re-initialises once.
        """
        import pyaudio

        with self._lock:
            if self._audio is None:
                # Pa_Initialize() is not thread-safe and the microphone
                # thread can be opening a device at the same moment.
                with portaudio_lock:
                    self._audio = pyaudio.PyAudio()
            try:
                self._stream = self._audio.open(
                    format=pyaudio.paInt16,
                    channels=1,
                    rate=SAMPLE_RATE,
                    output=True,
                )
                return self._stream
            except Exception as e:
                if not _retry:
                    raise
                logger.info(
                    f"Audio output unavailable ({e}) — re-initialising the "
                    "device list and retrying"
                )
                try:
                    with portaudio_lock:
                        self._audio.terminate()
                except Exception:
                    pass
                self._audio = None

        # Retry outside the lock so the recursive call can re-acquire it.
        return self._open_stream(_retry=False)

    def _close_stream(self) -> None:
        with self._lock:
            if self._stream is not None:
                try:
                    self._stream.stop_stream()
                    self._stream.close()
                except Exception:
                    pass
                self._stream = None

    # ── Main entry point ─────────────────────────────────────────────────

    def speak(self, text: str, should_stop: Optional[StopCheck] = None) -> bool:
        self._stop_flag.clear()

        def interrupted() -> bool:
            return self._stop_flag.is_set() or bool(should_stop and should_stop())

        cache_file = self._cache_path(text) if self.cache_enabled else None

        # Cache hit: no network at all.
        if cache_file is not None and cache_file.exists():
            try:
                data = cache_file.read_bytes()
                os.utime(cache_file, None)  # touch for LRU
                logger.debug(f"TTS cache hit ({len(data)} bytes)")
                return self._play_bytes(data, interrupted)
            except Exception as e:
                logger.debug(f"TTS cache read failed: {e}")

        # Wait for the startup warm-up before going to the network.
        #
        # THIS IS THE ONE THAT MAKES JARVIS SOUND RIGHT. Without it the first
        # utterance races the TLS handshake: ElevenLabs takes long enough to
        # look like a failure, FallbackEngine drops to the robotic macOS voice,
        # and the very first thing JARVIS says every launch is in the wrong
        # voice. Firing the warm-up thread is not enough — something has to
        # wait for it.
        #
        # Bounded, and only on the network path: a cache hit never waits, and a
        # dead network costs WARM_WAIT_SEC once rather than hanging.
        self.warm_ready.wait(timeout=WARM_WAIT_SEC)

        return self._stream_and_play(text, cache_file, interrupted)

    def _stream_and_play(self, text: str, cache_file: Optional[Path],
                         interrupted: Callable[[], bool]) -> bool:
        import requests

        url = API_URL.format(voice_id=self.voice_id)
        params = {
            "output_format": OUTPUT_FORMAT,
            "optimize_streaming_latency": STREAMING_LATENCY,
        }
        payload = {
            "text": text,
            "model_id": self.model,
            "voice_settings": {
                "stability": 0.5,
                "similarity_boost": 0.75,
                "speed": 1.0,
            },
        }
        t0 = time.perf_counter()
        collected = bytearray()
        stream = None
        first_audio_at = None
        carry = b""   # trailing odd byte held over between chunks

        try:
            resp = self._get_session().post(
                url, params=params, json=payload,
                stream=True, timeout=(CONNECT_TIMEOUT, REQUEST_TIMEOUT),
            )
            if resp.status_code != 200:
                detail = ""
                try:
                    detail = resp.text[:200]
                except Exception:
                    pass
                logger.warning(
                    f"ElevenLabs HTTP {resp.status_code}: {detail}"
                )
                return False

            for chunk in resp.iter_content(chunk_size=CHUNK_BYTES):
                if interrupted():
                    logger.debug("ElevenLabs playback interrupted")
                    return False
                if not chunk:
                    continue

                # Open the output device only once real audio arrives, so a
                # failed request never briefly seizes the sound card.
                if stream is None:
                    stream = self._open_stream()
                    first_audio_at = time.perf_counter()
                    logger.info(
                        f"TTS first audio in {(first_audio_at - t0) * 1000:.0f}ms"
                    )

                # 16-bit PCM means every sample is exactly 2 bytes, but the
                # HTTP stream splits on arbitrary boundaries — measured chunk
                # sizes included 1183, 1211, 1213 and 2403. Writing an odd
                # number of bytes shifts every subsequent sample by one byte,
                # pairing the low half of one sample with the high half of the
                # next, which is heard as loud static for the rest of the clip.
                # Hold any trailing odd byte back and prepend it to the next
                # chunk so only whole samples ever reach the device.
                buf = carry + chunk
                carry = b""
                if len(buf) % 2:
                    carry = buf[-1:]
                    buf = buf[:-1]

                if buf:
                    stream.write(buf)
                    # Drives the desktop visualiser: these are the exact
                    # samples reaching the speaker.
                    audio_level.publish_pcm(buf)
                    if cache_file is not None:
                        collected.extend(buf)

            # A dangling half-sample at end of stream would be dropped; pad
            # it to a whole sample rather than truncating mid-sample.
            if carry and stream is not None:
                tail = carry + b"\x00"
                stream.write(tail)
                if cache_file is not None:
                    collected.extend(tail)

            # Brief silence so the device buffer drains instead of being cut
            # mid-waveform, which produces an audible click at the end.
            if stream is not None:
                stream.write(SILENCE_PAD)

            if cache_file is not None and collected and not interrupted():
                try:
                    cache_file.write_bytes(bytes(collected))
                    self._prune_cache()
                except Exception as e:
                    logger.debug(f"TTS cache write failed: {e}")

            return True

        except Exception as e:
            logger.warning(f"ElevenLabs stream failed: {e}")
            return False
        finally:
            self._close_stream()

    def _play_bytes(self, data: bytes, interrupted: Callable[[], bool]) -> bool:
        stream = None
        try:
            stream = self._open_stream()
            # Truncate to whole samples. A cached file should always be even,
            # but a partial write from an earlier crash must not desynchronise
            # playback into static.
            usable = len(data) - (len(data) % 2)
            for i in range(0, usable, CHUNK_BYTES):
                if interrupted():
                    return False
                block = data[i:i + CHUNK_BYTES]
                stream.write(block)
                audio_level.publish_pcm(block)
            stream.write(SILENCE_PAD)
            return True
        except Exception as e:
            logger.warning(f"Cached PCM playback failed: {e}")
            return False
        finally:
            self._close_stream()

    def stop(self) -> None:
        self._stop_flag.set()
        self._close_stream()

    def shutdown(self) -> None:
        """Release the audio device. PyAudio holds a CoreAudio handle that is
        not freed by closing streams alone."""
        self.stop()
        with self._lock:
            if self._audio is not None:
                try:
                    self._audio.terminate()
                except Exception as e:
                    logger.debug(f"PyAudio terminate failed: {e}")
                self._audio = None
            if self._session is not None:
                try:
                    self._session.close()
                except Exception:
                    pass
                self._session = None

    def warm_cache(self, phrases: list[str]) -> int:
        """Pre-generate common phrases so they never cost a network call."""
        import requests

        done = 0
        for phrase in phrases:
            path = self._cache_path(phrase)
            if path.exists():
                continue
            try:
                resp = self._get_session().post(
                    API_URL.format(voice_id=self.voice_id),
                    params={"output_format": OUTPUT_FORMAT},
                    json={"text": phrase, "model_id": self.model},
                    timeout=(CONNECT_TIMEOUT, REQUEST_TIMEOUT),
                )
                if resp.status_code == 200:
                    path.write_bytes(resp.content)
                    done += 1
                else:
                    logger.warning(f"warm_cache HTTP {resp.status_code} for {phrase!r}")
            except Exception as e:
                logger.warning(f"warm_cache failed for {phrase!r}: {e}")
        if done:
            self._prune_cache()
        return done


# ── Fallback wrapper ─────────────────────────────────────────────────────────

class FallbackEngine(SpeechEngine):
    """Try the primary engine; drop to the backup if it fails.

    Jarvis going silent because an API call timed out is a worse outcome than
    a sentence in the robotic system voice, so any failure falls through.
    """

    name = "fallback"

    def __init__(self, primary: SpeechEngine, backup: SpeechEngine):
        self.primary = primary
        self.backup = backup
        self._active = backup
        self._lock = threading.Lock()
        self._consecutive_failures = 0

    def speak(self, text: str, should_stop: Optional[StopCheck] = None) -> bool:
        if self.primary.available():
            with self._lock:
                self._active = self.primary
            if self.primary.speak(text, should_stop):
                self._consecutive_failures = 0
                return True

            # An interruption is not a failure — don't let barge-in trip the
            # circuit breaker or re-speak the line we just cut off.
            if should_stop and should_stop():
                return False

            self._consecutive_failures += 1
            if self._consecutive_failures == 3:
                logger.warning(
                    "ElevenLabs has failed 3 times in a row — still retrying, "
                    "but check your API key, quota and connection."
                )
            logger.info("Falling back to system voice for this utterance")

        with self._lock:
            self._active = self.backup
        return self.backup.speak(text, should_stop)

    def stop(self) -> None:
        # Stop both: which one is mid-playback is racy from the caller's side.
        self.primary.stop()
        self.backup.stop()

    def shutdown(self) -> None:
        for engine in (self.primary, self.backup):
            fn = getattr(engine, "shutdown", None)
            if callable(fn):
                try:
                    fn()
                except Exception:
                    pass

    def available(self) -> bool:
        return self.backup.available()

    @property
    def active_name(self) -> str:
        with self._lock:
            return self._active.name


# ── Factory ──────────────────────────────────────────────────────────────────

def build_engine() -> SpeechEngine:
    """Construct the configured engine, wrapped in a fallback if needed."""
    from config import settings

    mac = MacSayEngine(settings.TTS_VOICE, settings.TTS_RATE)

    engine_choice = getattr(settings, "TTS_ENGINE", "say").lower()
    if engine_choice != "elevenlabs":
        return mac

    api_key = getattr(settings, "ELEVENLABS_API_KEY", "")
    voice_id = getattr(settings, "ELEVENLABS_VOICE_ID", "")

    if not api_key:
        logger.warning(
            "TTS_ENGINE=elevenlabs but ELEVENLABS_API_KEY is not set — "
            "using the system voice. Add the key to .env."
        )
        return mac

    eleven = ElevenLabsEngine(
        api_key=api_key,
        voice_id=voice_id,
        model=getattr(settings, "ELEVENLABS_MODEL", DEFAULT_MODEL),
    )
    if not eleven.available():
        logger.warning("ElevenLabs engine unavailable — using the system voice")
        return mac

    # Warm the connection AND the synthesis path off-thread, so the first
    # spoken line pays neither. Cold was measured at 4.7s versus ~450ms warm.
    #
    # `warm_ready` is the load-bearing part. The previous version started this
    # thread and never waited on it, so the first utterance raced the handshake
    # and FallbackEngine dropped to the robotic system voice — the first thing
    # JARVIS said every launch was in the wrong voice. speak() now waits.
    #
    # `finally` matters too: if warm-up throws, the event must still be set or
    # every utterance would block for the full WARM_WAIT_SEC.
    # Mark not-ready before the thread starts, so speak() cannot slip past the
    # gate in the window between launching the thread and it doing any work.
    eleven.warm_ready.clear()

    def _warm() -> None:
        try:
            ms = eleven.warm_connection()
            logger.info(f"ElevenLabs connection warm ({ms or -1:.0f}ms)")
            ms2 = eleven.warm_synthesis()
            if ms2 is not None:
                logger.info(f"ElevenLabs synthesis warm ({ms2:.0f}ms)")
        except Exception as exc:
            logger.warning(f"ElevenLabs warm-up failed: {exc}")
        finally:
            eleven.warm_ready.set()

    threading.Thread(target=_warm, daemon=True, name="tts-warmup").start()

    logger.info(f"TTS: ElevenLabs ({eleven.model}, voice {voice_id[:8]}...) "
                "with system-voice fallback")
    return FallbackEngine(primary=eleven, backup=mac)
