# Generated by Claudian.
"""Text-to-speech via macOS `say`, serialized through a single worker thread.

WHY A QUEUE
-----------
The previous implementation let any thread call `speak()` directly, and
`speak()` began with `self.stop()` — executed *outside* the lock — which
terminated whatever `say` process was already running.  With multiple
concurrent speakers (assistant replies, the conversation skill streaming
sentence-by-sentence, proactive agents on the scheduler thread) this caused:

  1. Truncated speech — an agent firing mid-conversation killed the reply
     you were listening to, halfway through a word.
  2. A self-hearing feedback loop — the interrupted thread's `finally`
     cleared `speaking_state` while the *next* utterance was still playing,
     so the wake-word listener opened the mic during TTS and transcribed
     Jarvis's own voice as a command.
  3. A data race on `_current_process`, mutated by every caller thread.

Now exactly ONE thread ever touches `say`.  Callers enqueue.  Utterances
play in submission order and are never truncated by another speaker.

`speaking_state` is held for the whole drain rather than per-utterance, so
the mic stays closed *between* sentences of a streamed reply too — closing
the gap where feedback used to leak in.
"""

from __future__ import annotations

import queue
import subprocess
import threading
from dataclasses import dataclass, field

from config import settings
from utils.helpers import clean_for_speech
from utils.logger import get_logger
from voice import speaking_state
from voice.speech_engines import build_engine

logger = get_logger(__name__)


def _publish_state(state: str) -> None:
    """Tell the HUD what the speaker is doing.

    Imported lazily and failure-tolerant: voice_state lives in `core`, which
    imports voice modules, so a module-level import here would be circular.
    """
    try:
        from core import voice_state
        voice_state.set_state(state)
    except Exception:
        pass


@dataclass
class _Utterance:
    text: str
    done: threading.Event = field(default_factory=threading.Event)


# Sentinel pushed on shutdown to wake the worker out of its blocking get().
_SHUTDOWN = _Utterance(text="\x00__shutdown__")


class TextToSpeech:
    def __init__(self, engine=None):
        self.voice = settings.TTS_VOICE
        self.rate = settings.TTS_RATE

        # Rendering is delegated so a new voice provider needs no changes to
        # the queueing, ordering, speaking_state or barge-in logic here.
        self._engine = engine if engine is not None else build_engine()

        self._queue: "queue.Queue[_Utterance]" = queue.Queue()

        # Guards _current_text and coordinates stop() across threads.
        self._proc_lock = threading.Lock()
        self._interrupt = threading.Event()

        # What is coming out of the speakers right now. The echo filter needs
        # it to tell Jarvis's own voice from the user's during barge-in.
        self._current_text: str | None = None

        self._shutdown = False
        self._worker = threading.Thread(
            target=self._drain, daemon=True, name="jarvis-tts"
        )
        self._worker.start()

    # ── Public API ───────────────────────────────────────────────────────────

    def speak(self, text: str, timeout: float | None = 120.0) -> None:
        """Enqueue `text` and block until it has finished playing.

        Preserves the original blocking contract, so the conversation skill's
        sentence-by-sentence streaming and the test-suite both behave as
        before — but without the cross-thread process race.
        """
        utt = self._enqueue(text)
        if utt is not None:
            # Timeout guards against a wedged `say` deadlocking a caller.
            if not utt.done.wait(timeout=timeout) and timeout is not None:
                logger.warning(f"TTS wait timed out after {timeout}s: {text[:60]!r}")

    def speak_async(self, text: str) -> None:
        """Enqueue `text` and return immediately."""
        self._enqueue(text)

    def stop(self) -> None:
        """Barge-in: drop everything queued and kill the current utterance.

        This is now an explicit, deliberate action.  Previously it ran as a
        silent side effect at the top of every speak() call, which is what
        made speakers cut each other off.
        """
        # Drain pending work first so nothing new starts after we kill.
        drained = 0
        while True:
            try:
                pending = self._queue.get_nowait()
            except queue.Empty:
                break
            pending.done.set()  # never leave a blocked caller hanging
            self._queue.task_done()
            drained += 1

        self._interrupt.set()
        try:
            self._engine.stop()
        except Exception as e:
            logger.debug(f"engine.stop() failed: {e}")

        if drained:
            logger.debug(f"TTS stop(): dropped {drained} queued utterance(s)")

    def is_speaking(self) -> bool:
        with self._proc_lock:
            return self._current_text is not None

    def current_text(self) -> str | None:
        """The utterance currently playing, or None if silent."""
        with self._proc_lock:
            return self._current_text

    def shutdown(self) -> None:
        """Stop the worker thread. Called on assistant shutdown."""
        self._shutdown = True
        self.stop()
        self._queue.put(_SHUTDOWN)
        self._worker.join(timeout=3)
        # Release the audio device and any pooled HTTP connection.
        fn = getattr(self._engine, "shutdown", None)
        if callable(fn):
            try:
                fn()
            except Exception as e:
                logger.debug(f"engine shutdown failed: {e}")

    # ── Internals ────────────────────────────────────────────────────────────

    def _enqueue(self, text: str) -> _Utterance | None:
        text = clean_for_speech(text)
        if not text:
            return None
        if self._shutdown:
            logger.debug("TTS is shut down — dropping utterance")
            return None
        utt = _Utterance(text=text)
        self._queue.put(utt)
        return utt

    def _drain(self) -> None:
        """Sole owner of the `say` subprocess."""
        while True:
            utt = self._queue.get()

            if utt is _SHUTDOWN or self._shutdown:
                utt.done.set()
                self._queue.task_done()
                if utt is _SHUTDOWN:
                    return
                continue

            # Hold speaking_state across the whole drain: if more sentences
            # are already queued (streamed reply), the mic must stay shut
            # between them, not flicker open in the gap.
            speaking_state.set_speaking()
            _publish_state("speaking")
            self._interrupt.clear()
            with self._proc_lock:
                self._current_text = utt.text
            try:
                self._say(utt.text)
            except Exception as e:
                logger.error(f"TTS error: {e}")
                self._fallback_speak(utt.text)
            finally:
                with self._proc_lock:
                    self._current_text = None
                utt.done.set()
                self._queue.task_done()
                # Only reopen the mic once nothing else is waiting to play.
                if self._queue.empty():
                    speaking_state.clear_speaking()
                    _publish_state("idle")
                    # Let the visualiser settle rather than freezing at
                    # whatever amplitude the last chunk happened to have.
                    try:
                        from voice import audio_level
                        audio_level.reset()
                    except Exception:
                        pass

    def _say(self, text: str) -> None:
        logger.debug(f"Speaking: {text[:80]}")
        # The engine polls this so barge-in can cut playback off mid-stream
        # rather than only between utterances.
        self._engine.speak(text, should_stop=self._interrupt.is_set)

    @property
    def engine_name(self) -> str:
        return getattr(self._engine, "active_name", self._engine.name)

    def _fallback_speak(self, text: str) -> None:
        """Last resort if the configured voice is unavailable."""
        try:
            subprocess.run(["say", text], timeout=30)
        except Exception as e:
            logger.error(f"Fallback TTS failed: {e}")


# ── Singleton ────────────────────────────────────────────────────────────────
# Shared so the conversation skill streams into the same queue the assistant
# uses — that ordering guarantee is the whole point.

_tts_singleton: TextToSpeech | None = None
_singleton_lock = threading.Lock()


def get_tts() -> TextToSpeech:
    global _tts_singleton
    # Double-checked locking: agents start on their own threads and could
    # otherwise each construct a separate TTS (and a separate worker).
    if _tts_singleton is None:
        with _singleton_lock:
            if _tts_singleton is None:
                _tts_singleton = TextToSpeech()
    return _tts_singleton
