# Generated by Claudian.
"""Agents — proactive behaviours that run on their own.

Unlike skills (which are reactive — they wait for the user to ask something),
agents act autonomously: they fire on a schedule, on a trigger, or on a
system event, and use Jarvis's voice to tell Ruthish things.

Current agents:
  morning_brief    — speaks a morning summary every weekday at 08:00
  focus_guardian   — when he's coding for >15 min, auto-silences distractions
  end_of_day       — on screen-lock at night, speaks a day recap + saves it

Add a new agent: drop a file in `agents/`, subclass `Agent`, implement
`tick()` + `should_run(now)`.  The AgentRunner picks it up automatically.
"""

from agents._base import Agent, AgentContext
from agents._runner import AgentRunner, get_agent_runner

__all__ = ["Agent", "AgentContext", "AgentRunner", "get_agent_runner"]
