# Generated by Claudian.
"""Agent base class + shared context.

An agent is a callable that the AgentRunner ticks once per minute.  The
agent decides for itself whether it should do something *now* via
`should_run(now)` — this keeps scheduling logic inside each agent rather
than in a central cron-like config.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Callable, Optional

from utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class AgentContext:
    """Handles an agent passes around — keeps them loosely coupled to
    JarvisAssistant internals.

    `speak` is the callable the agent uses to say something out loud.
    `memory` is the shared MemoryStore (already imported lazily so tests
    don't spin up a DB just to construct an agent).
    """

    speak: Callable[[str], None]
    memory: object = None  # set to MemoryStore by the runner; opaque here

    # Per-agent scratch space (e.g. "last time I fired") — indexed by agent name.
    state: dict = field(default_factory=dict)


class Agent:
    """Subclass this in `agents/<name>.py`."""

    name: str = ""
    description: str = ""

    # If True, the agent is skipped until `enable()` is explicitly called.
    # Useful for guarded-off experiments.
    disabled_by_default: bool = False

    def should_run(self, now: datetime, ctx: AgentContext) -> bool:
        """Return True if `tick()` should execute *right now*."""
        raise NotImplementedError

    def tick(self, ctx: AgentContext) -> None:
        """Do whatever this agent does.  Called in a worker thread — keep
        it reasonably quick (seconds, not minutes)."""
        raise NotImplementedError

    # ── Convenience ─────────────────────────────────────────────────────────

    def _state(self, ctx: AgentContext) -> dict:
        """Per-agent mutable state dict — survives across ticks, lost on restart."""
        return ctx.state.setdefault(self.name, {})

    def _mark_fired(self, ctx: AgentContext, key: str = "last_fired_at") -> None:
        self._state(ctx)[key] = datetime.now().isoformat()

    def _last_fired(self, ctx: AgentContext, key: str = "last_fired_at") -> Optional[datetime]:
        raw = self._state(ctx).get(key)
        if not raw:
            return None
        try:
            return datetime.fromisoformat(raw)
        except ValueError:
            return None
