# Generated by Claudian.
"""Agent: end-of-day wrap.

Fires once a day in the evening (default 22:00) IF Ruthish has been
active today.  Generates a one-paragraph recap from today's events log,
saves it to memory.summaries (so tomorrow's morning_brief can reference
it), and speaks it out loud.

Recap is built from raw events + a Groq summarisation pass when available;
falls back to a hand-rolled "you ran X commands today" summary when the
LLM is offline.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Optional

from agents._base import Agent, AgentContext
from utils.logger import get_logger

logger = get_logger(__name__)


WRAP_HOUR = 22
WRAP_MINUTE = 0
WRAP_WINDOW_MIN = 30  # fire any time 22:00–22:30


class EndOfDayAgent(Agent):
    name = "end_of_day"
    description = "Speaks a daily recap at ~22:00 and saves it to memory"

    def should_run(self, now: datetime, ctx: AgentContext) -> bool:
        target_start = now.replace(hour=WRAP_HOUR, minute=WRAP_MINUTE, second=0, microsecond=0)
        target_end = target_start + timedelta(minutes=WRAP_WINDOW_MIN)
        if not (target_start <= now < target_end):
            return False
        last = self._last_fired(ctx)
        if last and last.date() == now.date():
            return False
        # Don't bother if there were no events today
        try:
            events = ctx.memory.today_events()  # type: ignore[union-attr]
        except Exception:
            events = []
        if not events:
            return False
        return True

    def tick(self, ctx: AgentContext) -> None:
        self._mark_fired(ctx)
        recap = self._build_recap(ctx) or "You were quiet today, Boss."
        # Persist
        try:
            ctx.memory.save_daily_summary(recap)  # type: ignore[union-attr]
        except Exception as e:
            logger.debug(f"save_daily_summary failed: {e}")
        ctx.speak(recap)

    # ── Recap builder ───────────────────────────────────────────────────────

    def _build_recap(self, ctx: AgentContext) -> Optional[str]:
        try:
            events = ctx.memory.today_events()  # type: ignore[union-attr]
        except Exception:
            events = []
        if not events:
            return None

        # Skill counts
        skill_counts: dict[str, int] = {}
        for e in events:
            skill_counts[e.skill] = skill_counts.get(e.skill, 0) + 1

        # Try LLM summary first
        llm = self._llm_summary(events)
        if llm:
            return llm

        # Fallback: hand-rolled stat sentence
        total = len(events)
        top = sorted(skill_counts.items(), key=lambda kv: -kv[1])[:3]
        parts = [f"Wrap-up Boss — {total} commands today."]
        if top:
            top_str = ", ".join(f"{s.replace('_', ' ')} x{c}" for s, c in top)
            parts.append(f"Most-used: {top_str}.")
        parts.append("Get some rest.")
        return " ".join(parts)

    def _llm_summary(self, events) -> Optional[str]:
        try:
            from config import settings
            if not settings.has_ai():
                return None
            from groq import Groq
            client = Groq(api_key=settings.GROQ_API_KEY)
            # Build a compact transcript
            transcript = "\n".join(
                f"- ({e.skill}) {e.user_text} → {e.reply_text[:80]}"
                for e in events[-30:]  # last 30 events max
            )
            prompt = (
                "Summarize Ruthish's day in 2 short sentences.  Tone: friendly "
                "personal assistant, addresses him as 'Boss', no bullet points, "
                "no preamble.  Mention 1-2 concrete things he did.  Keep under 40 words.\n\n"
                f"Today's commands:\n{transcript}"
            )
            resp = client.chat.completions.create(
                model=settings.GROQ_FAST_MODEL,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=120,
                temperature=0.5,
            )
            text = (resp.choices[0].message.content or "").strip()
            return text or None
        except Exception as e:
            logger.debug(f"end_of_day LLM summary failed: {e}")
            return None
