# Generated by Claudian.
"""Agent: focus guardian.

When Ruthish has been continuously focused on a coding/work app for 15+
minutes, automatically:
  • mute system audio (no notification dings)
  • mute the system, lower volume to 30 (so any music doesn't ramp later)
  • say a brief one-liner: "Focus mode on — silenced notifications."

When he switches AWAY from a focus app for 10+ minutes, restore.

Heuristic — no Apple Focus Mode API used.  Detects the frontmost app via
AppleScript every minute.
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timedelta

from agents._base import Agent, AgentContext
from utils.logger import get_logger

logger = get_logger(__name__)


# Apps that count as "focus mode worthy" — Ruthish's coding tools
FOCUS_APPS = {
    "Code",                      # VS Code's process name
    "Visual Studio Code",
    "Cursor",
    "PyCharm",
    "IntelliJ IDEA",
    "Xcode",
    "Terminal",
    "iTerm2",
    "Warp",
}

FOCUS_THRESHOLD_MIN = 15      # consecutive minutes before activating
RELAX_THRESHOLD_MIN = 10      # consecutive minutes away before deactivating


def _frontmost_app() -> str:
    """Return the bundle/process name of the frontmost app, or '' on error."""
    try:
        result = subprocess.run(
            ["osascript", "-e",
             'tell application "System Events" to get name of first process whose frontmost is true'],
            capture_output=True, text=True, timeout=2,
        )
        return result.stdout.strip()
    except Exception:
        return ""


class FocusGuardianAgent(Agent):
    name = "focus_guardian"
    description = "Auto-silence notifications when coding for 15+ continuous minutes"

    def should_run(self, now: datetime, ctx: AgentContext) -> bool:
        # We tick every minute; the actual decision logic is inside `tick()`
        # because we need to update state regardless of whether we *speak*.
        last = self._last_fired(ctx, key="last_check")
        if last is None:
            return True
        return (now - last) >= timedelta(seconds=55)

    def tick(self, ctx: AgentContext) -> None:
        self._mark_fired(ctx, key="last_check")
        state = self._state(ctx)
        now = datetime.now()
        front = _frontmost_app()

        is_focus_app = front in FOCUS_APPS
        active = state.get("focus_active", False)

        if is_focus_app:
            # Track continuous focus time
            since = state.get("focus_since")
            if since is None:
                state["focus_since"] = now.isoformat()
                state["away_since"] = None
            elif not active:
                elapsed = now - datetime.fromisoformat(since)
                if elapsed >= timedelta(minutes=FOCUS_THRESHOLD_MIN):
                    self._activate(ctx)
                    state["focus_active"] = True
        else:
            # Track time away from focus apps
            since = state.get("away_since")
            if since is None:
                state["away_since"] = now.isoformat()
                state["focus_since"] = None
            elif active:
                elapsed = now - datetime.fromisoformat(since)
                if elapsed >= timedelta(minutes=RELAX_THRESHOLD_MIN):
                    self._deactivate(ctx)
                    state["focus_active"] = False

    # ── Focus actions ───────────────────────────────────────────────────────

    def _activate(self, ctx: AgentContext) -> None:
        logger.info("focus_guardian: activating")
        try:
            from automation.system_control import mute_audio
            mute_audio()
        except Exception as e:
            logger.debug(f"focus mute failed: {e}")
        ctx.speak("Focus mode on — silenced notifications.")

    def _deactivate(self, ctx: AgentContext) -> None:
        logger.info("focus_guardian: deactivating")
        try:
            from automation.system_control import unmute_audio
            unmute_audio()
        except Exception as e:
            logger.debug(f"focus unmute failed: {e}")
        ctx.speak("Welcome back. Notifications restored.")
