# Generated by Claudian.
"""Agent: morning brief.

Fires once a day, weekday mornings, around 08:00 local time.  Speaks a
30-second summary covering: today's date, battery + Wi-Fi status, recent
facts Ruthish has stored (e.g. interview times, deadlines), and any
half-finished thoughts from yesterday's events log.

Why: he's lazy.  The assistant that waits to be asked is good; the
assistant that proactively briefs him while he's still in bed is JARVIS.
"""

from __future__ import annotations

from datetime import datetime, time, timedelta

from agents._base import Agent, AgentContext


# When the brief should fire (local time)
BRIEF_HOUR = 8
BRIEF_MINUTE = 0
# Window of acceptable trigger time — fires once anywhere from 08:00 to 08:15
BRIEF_WINDOW_MIN = 15
# Skip weekends?  Set False to brief 7 days a week.
SKIP_WEEKENDS = False


class MorningBriefAgent(Agent):
    name = "morning_brief"
    description = "Speaks a morning briefing once a day around 8 AM"

    def should_run(self, now: datetime, ctx: AgentContext) -> bool:
        if SKIP_WEEKENDS and now.weekday() >= 5:  # 5=Sat, 6=Sun
            return False
        # Inside the trigger window?
        target_start = now.replace(hour=BRIEF_HOUR, minute=BRIEF_MINUTE, second=0, microsecond=0)
        target_end = target_start + timedelta(minutes=BRIEF_WINDOW_MIN)
        if not (target_start <= now < target_end):
            return False
        # Already fired today?
        last = self._last_fired(ctx)
        if last and last.date() == now.date():
            return False
        return True

    def tick(self, ctx: AgentContext) -> None:
        self._mark_fired(ctx)
        text = self._build_brief(ctx)
        ctx.speak(text)

    # ── Brief builder ────────────────────────────────────────────────────────

    def _build_brief(self, ctx: AgentContext) -> str:
        parts: list[str] = []
        now = datetime.now()
        greeting = self._time_of_day_greeting(now.hour)
        parts.append(f"{greeting} Boss.")
        parts.append(f"It's {now.strftime('%A, %B %d')}.")

        # Battery status
        try:
            from utils.os_utils import get_battery_info
            batt = get_battery_info()
            pct = batt.get("percent", "unknown")
            charging = batt.get("charging", False)
            if charging:
                parts.append(f"You're at {pct} and charging.")
            else:
                parts.append(f"Battery's at {pct}.")
        except Exception:
            pass

        # Recent facts that look time-sensitive (interview, deadline, meeting)
        try:
            time_keywords = ["interview", "meeting", "deadline", "appointment", "exam"]
            hits: list[str] = []
            for kw in time_keywords:
                facts = ctx.memory.recall(kw, limit=2)  # type: ignore[union-attr]
                for f in facts:
                    if f.text not in hits:
                        hits.append(f.text)
                if len(hits) >= 3:
                    break
            if hits:
                parts.append("Heads-up: " + " ".join(h.rstrip(".") + "." for h in hits[:2]))
        except Exception:
            pass

        # Yesterday recap (latest summary, if any)
        try:
            last_summary = ctx.memory.latest_summary()  # type: ignore[union-attr]
            if last_summary:
                # Only mention if it's from yesterday
                if last_summary.day == (now.date() - timedelta(days=1)).strftime("%Y-%m-%d"):
                    short = last_summary.text
                    if len(short) > 120:
                        short = short[:117].rsplit(" ", 1)[0] + "..."
                    parts.append(f"Yesterday's wrap: {short}")
        except Exception:
            pass

        parts.append("Have a good one.")
        return " ".join(parts)

    @staticmethod
    def _time_of_day_greeting(hour: int) -> str:
        if hour < 12:
            return "Good morning,"
        if hour < 17:
            return "Good afternoon,"
        return "Good evening,"
