# Generated by Claudian.
"""Language registry: what JARVIS can hear, think in, and speak.

Three separate concerns live here, deliberately kept apart:

  RECOGNITION  Whisper detects the language itself, so nothing needs
               configuring — but it reports an English NAME ("Tamil"), which
               has to be mapped to a tag before anything else can use it.

  SYNTHESIS    macOS ships voices per locale. Speaking Tamil with an English
               voice is worse than silence, so a language with no installed
               voice must be detected rather than assumed.

  SWITCHING    "Speak in Tamil" has to be recognised in whatever language the
               user happens to be speaking at the time — including in Tamil.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from functools import lru_cache


@dataclass(frozen=True)
class Language:
    tag: str            # BCP-47, e.g. "ta-IN"
    name: str           # English name — matches Whisper's output
    native: str         # endonym, for speaking back to the user
    aliases: tuple[str, ...] = ()   # how users refer to it, any script

    @property
    def code(self) -> str:
        return self.tag.split("-")[0]


LANGUAGES: tuple[Language, ...] = (
    Language("en-US", "English", "English", ("english", "inglish")),
    Language("ta-IN", "Tamil", "Tamil", ("tamil", "thamizh", "tamizh")),
    Language("hi-IN", "Hindi", "Hindi", ("hindi",)),
    Language("kn-IN", "Kannada", "Kannada", ("kannada",)),
    Language("ml-IN", "Malayalam", "Malayalam", ("malayalam",)),
    Language("ja-JP", "Japanese", "Japanese", ("japanese", "nihongo")),
    Language("te-IN", "Telugu", "Telugu", ("telugu",)),
    Language("bn-IN", "Bengali", "Bengali", ("bengali", "bangla")),
    Language("mr-IN", "Marathi", "Marathi", ("marathi",)),
    Language("gu-IN", "Gujarati", "Gujarati", ("gujarati",)),
    Language("pa-IN", "Punjabi", "Punjabi", ("punjabi",)),
    Language("ur-PK", "Urdu", "Urdu", ("urdu",)),
    Language("zh-CN", "Chinese", "Chinese", ("chinese", "mandarin")),
    Language("es-ES", "Spanish", "Espanol", ("spanish", "espanol")),
    Language("fr-FR", "French", "Francais", ("french", "francais")),
    Language("de-DE", "German", "Deutsch", ("german", "deutsch")),
    Language("pt-BR", "Portuguese", "Portugues", ("portuguese", "portugues")),
    Language("ru-RU", "Russian", "Russian", ("russian",)),
    Language("ar-SA", "Arabic", "Arabic", ("arabic",)),
    Language("ko-KR", "Korean", "Korean", ("korean",)),
    Language("it-IT", "Italian", "Italiano", ("italian", "italiano")),
    Language("id-ID", "Indonesian", "Indonesia", ("indonesian", "bahasa")),
    Language("tr-TR", "Turkish", "Turkce", ("turkish", "turkce")),
    Language("vi-VN", "Vietnamese", "Tieng Viet", ("vietnamese",)),
    Language("th-TH", "Thai", "Thai", ("thai",)),
    Language("nl-NL", "Dutch", "Nederlands", ("dutch", "nederlands")),
    Language("pl-PL", "Polish", "Polski", ("polish", "polski")),
)

DEFAULT = LANGUAGES[0]

_BY_TAG = {l.tag.lower(): l for l in LANGUAGES}
_BY_CODE = {l.code: l for l in LANGUAGES}
_BY_NAME = {l.name.lower(): l for l in LANGUAGES}

# Native-script names, kept as a separate lookup so the dataclass stays ASCII
# and this file has no surprises in it.
_NATIVE_ALIASES: dict[str, str] = {
    "தமிழ்": "ta-IN",          # Tamil
    "हिंदी": "hi-IN",          # Hindi
    "हिन्दी": "hi-IN",
    "ಕನ್ನಡ": "kn-IN",          # Kannada
    "മലയാളം": "ml-IN",    # Malayalam
    "日本語": "ja-JP",                      # Japanese
    "中文": "zh-CN",                            # Chinese
    "തെലുഗു": "te-IN",    # Telugu
    "বাংলা": "bn-IN",          # Bengali
    "한국어": "ko-KR",                      # Korean
    "العربية": "ar-SA",  # Arabic
    "اردو": "ur-PK",                # Urdu
}


def by_tag(tag: str) -> Language | None:
    if not tag:
        return None
    tag = tag.strip()
    return _BY_TAG.get(tag.lower()) or _BY_CODE.get(tag.split("-")[0].lower())


def by_name(name: str) -> Language | None:
    """Whisper reports 'Tamil', not 'ta'. Accept name, code, tag or endonym."""
    if not name:
        return None
    key = name.strip().lower()
    if key in _NATIVE_ALIASES:
        return by_tag(_NATIVE_ALIASES[key])
    return _BY_NAME.get(key) or _BY_CODE.get(key) or by_tag(key)


# ── Explicit switching ───────────────────────────────────────────────────────
#
# Verbs meaning speak / talk / reply / switch, in the languages someone is
# plausibly speaking when they ask. Broad on purpose: this runs before
# anything else, so a false negative merely falls through to ordinary
# conversation, while a false positive would hijack a real question.
_SWITCH_VERBS = (
    r"speak|talk|say|reply|respond|answer|switch|change|continue|converse",
    r"பேசு|மாறு",          # Tamil
    r"बोलो|बदलो",          # Hindi
    r"ಮಾತಾಡು",                       # Kannada
    r"പറയൂ",                                   # Malayalam
    r"話して|切り替えて",          # Japanese
)

_SWITCH_RE = re.compile(r"(?:" + "|".join(_SWITCH_VERBS) + r")",
                        re.IGNORECASE | re.UNICODE)

# Words that sit between the verb and the language and must never be mistaken
# for one. Without this, "speak in hindi" captured "in".
_STOPWORDS = {
    "in", "into", "to", "only", "using", "please", "now", "the", "a", "an",
    "me", "with", "and", "language", "from", "on", "for", "just", "can",
    "you", "could", "would", "will", "let", "us", "i", "want", "like",
}


def detect_switch_request(text: str) -> Language | None:
    """Return the language the user is asking to switch to, if any.

    Handles "speak in Tamil", "now speak in Hindi", "can you reply in French",
    "switch to Japanese", and the same requests made in those languages.

    Written as find-verb-then-scan-tokens rather than one regex. A single
    pattern kept capturing the preposition — "speak in hindi" matched "in" —
    because the lazy quantifier settled on the first word boundary it found.
    Scanning every following token instead is both simpler and correct.
    """
    if not text:
        return None
    low = text.lower().strip()

    m = _SWITCH_RE.search(low)
    if m:
        # Look only AFTER the verb, so "I speak Tamil at home, tell me about
        # France" cannot be read as a request to switch to French.
        tail = low[m.end():]
        for token in re.split(r"[^\w]+", tail):
            if not token or token in _STOPWORDS:
                continue
            lang = _match_alias(token)
            if lang:
                return lang
            # Give up at the first content word that is not a language —
            # "speak louder about Japanese history" is not a switch request.
            break

    # Bare "Tamil please" — only when the whole utterance is short, or any
    # sentence merely mentioning Tamil would switch language.
    if len(low.split()) <= 3:
        for token in re.split(r"[^\w]+", low):
            if token and token not in _STOPWORDS:
                lang = _match_alias(token)
                if lang:
                    return lang
    return None


def _match_alias(token: str) -> Language | None:
    if not token or len(token) < 2:
        return None
    t = token.lower()
    if t in _NATIVE_ALIASES:
        return by_tag(_NATIVE_ALIASES[t])
    for lang in LANGUAGES:
        if t == lang.name.lower() or t == lang.native.lower():
            return lang
        if any(t == a.lower() for a in lang.aliases):
            return lang
    return None


# ── Voices ───────────────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def installed_voices() -> dict[str, list[str]]:
    """macOS voices grouped by language code, parsed from `say -v '?'`.

    Cached: the subprocess costs ~80ms and the set cannot change at runtime.
    """
    out: dict[str, list[str]] = {}
    try:
        res = subprocess.run(["say", "-v", "?"], capture_output=True,
                             text=True, timeout=5)
        for line in res.stdout.splitlines():
            # "Eddy (Japanese (Japan))     ja_JP    # ..."
            m = re.match(r"^(.*?)\s+([a-z]{2}_[A-Z]{2})\s+#", line)
            if not m:
                continue
            out.setdefault(m.group(2).split("_")[0], []).append(m.group(1).strip())
    except Exception:
        pass
    return out


def voice_for(lang: Language) -> str | None:
    """Best installed macOS voice for a language, or None if there is none.

    Returning None matters. The caller has to distinguish "use this voice"
    from "there is no voice, tell the user" — rather than silently reading
    Tamil in an American accent, which is worse than saying nothing.
    """
    voices = installed_voices().get(lang.code, [])
    return voices[0] if voices else None


def missing_voice_note(lang: Language) -> str:
    return (f"I don't have a {lang.name} voice installed, so I'll show the "
            f"text instead. You can add one in System Settings, "
            f"Accessibility, Spoken Content, Manage Voices.")
