# Generated by Claudian.
"""LLM with language steering and sentence streaming.

Two things this does that a plain chat call does not:

  LANGUAGE     The reply must come back in the conversation's language, and
               the instruction has to be unambiguous that this is a WRITING
               task. Told to "reply in Tamil, spoken-sounding", the model
               concluded it was being asked to synthesise audio and refused
               with "I can't generate spoken Tamil audio directly" — a true
               statement about the wrong job.

  STREAMING    Sentences are yielded as they arrive, so synthesis can begin on
               sentence one while the model is still writing sentence four.
               Perceived latency becomes time-to-first-clause instead of
               time-to-last-token, which is the difference between a
               conversation and a form submission.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Iterator, Optional

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from .languages import DEFAULT, Language

_SENTENCE_END = re.compile(r"(?<=[.!?।。])\s")

SYSTEM = (
    "You are JARVIS, a spoken assistant. You are being listened to, not read: "
    "no markdown, no bullet points, no numbered lists, no headings, no "
    "asterisks. Write plain sentences a person would say out loud. "
    "Be brief — two or three sentences unless genuinely asked for more."
)


def language_clause(lang: Language) -> str:
    """The instruction that actually makes non-English replies work."""
    if lang.code == "en":
        return ""
    return (
        f"\n\nWrite your reply in {lang.name}, using {lang.name} script. "
        f"You are producing TEXT. A separate text-to-speech system reads it "
        f"aloud, so never say you cannot speak, pronounce, or generate audio "
        f"in {lang.name} — that is not what is being asked. Simply answer in "
        f"{lang.name}."
    )


class LLM:
    def __init__(self, model: Optional[str] = None, temperature: float = 0.6):
        from config import settings
        self.settings = settings
        self.model = model or settings.GROQ_CHAT_MODEL
        self.temperature = temperature

    def _client(self):
        from openai import OpenAI
        return OpenAI(api_key=self.settings.GROQ_API_KEY,
                      base_url="https://api.groq.com/openai/v1", timeout=45)

    def _messages(self, prompt: str, lang: Language, history) -> list[dict]:
        msgs = [{"role": "system", "content": SYSTEM + language_clause(lang)}]
        for turn in history or []:
            msgs.append({"role": turn.get("role", "user"),
                         "content": turn.get("content", "")})
        msgs.append({"role": "user", "content": prompt})
        return msgs

    def reply(self, prompt: str, lang: Language = DEFAULT,
              history=None, max_tokens: int = 400) -> str:
        try:
            resp = self._client().chat.completions.create(
                model=self.model,
                messages=self._messages(prompt, lang, history),
                max_tokens=max_tokens,
                temperature=self.temperature,
            )
            return (resp.choices[0].message.content or "").strip()
        except Exception:
            return self._fallback(prompt, lang, history)

    def reply_json(self, prompt: str, max_tokens: int = 400) -> Optional[dict]:
        """Machine-readable reply. Deliberately skips the spoken persona.

        SYSTEM tells the model it is being listened to and must answer in plain
        spoken sentences with no markup. That is exactly right for every reply
        a person hears, and exactly wrong for one a parser reads: asked for
        JSON while under those instructions, the model returns prose or an
        empty string, and the caller's regex finds no object at all. Measured
        on gpt-oss-120b at 1/5 parses through `reply()` against 8/8 here.

        Two changes do the work — a system message that asks for JSON instead
        of forbidding it, and Groq's `json_object` response format, which
        constrains decoding rather than merely requesting good behaviour.

        Returns the parsed object, or None when it could not be parsed. None
        means "no answer" and callers must treat it as such; substituting a
        default-shaped dict here is how a failed assessment silently becomes a
        confident one.
        """
        import json

        try:
            resp = self._client().chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You output JSON only."},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=max_tokens,
                temperature=self.temperature,
                response_format={"type": "json_object"},
            )
            raw = (resp.choices[0].message.content or "").strip()
            return json.loads(raw) if raw else None
        except Exception:
            return None

    def stream_sentences(self, prompt: str, lang: Language = DEFAULT,
                         history=None, max_tokens: int = 400,
                         should_stop=None) -> Iterator[str]:
        """Yield complete sentences as the model writes them.

        Stops early when `should_stop` returns True, so an interruption ends
        generation instead of quietly finishing and being thrown away.
        """
        buf = ""
        try:
            stream = self._client().chat.completions.create(
                model=self.model,
                messages=self._messages(prompt, lang, history),
                max_tokens=max_tokens,
                temperature=self.temperature,
                stream=True,
            )
            for chunk in stream:
                try:
                    delta = chunk.choices[0].delta.content or ""
                except (AttributeError, IndexError):
                    continue
                if not delta:
                    continue
                buf += delta
                while True:
                    m = _SENTENCE_END.search(buf)
                    if not m:
                        break
                    sentence, buf = buf[:m.end()].strip(), buf[m.end():]
                    if len(sentence) >= 10:
                        yield sentence
                        if should_stop and should_stop():
                            return
                    else:
                        buf = sentence + " " + buf
                        break
            tail = buf.strip()
            if tail and not (should_stop and should_stop()):
                yield tail
        except Exception:
            text = self._fallback(prompt, lang, history)
            if text:
                yield text

    def _fallback(self, prompt: str, lang: Language, history) -> str:
        """Groq is down or the key is rejected — use the provider chain."""
        try:
            from ai.llm_fallback import try_fallbacks
            return try_fallbacks(self._messages(prompt, lang, history)) or ""
        except Exception:
            return ""
