#!/usr/bin/env python3
# Generated by Claudian.
"""The conversation loop — where every module meets.

    python3 -m conversation.loop
    python3 -m conversation.loop --lang ta-IN      # start pinned to Tamil
    python3 -m conversation.loop --no-wake         # respond to everything

DESIGN
------
One thread owns the microphone and never lets go, including while JARVIS is
speaking. Synthesis runs on a worker so the capture loop keeps segmenting
during playback; that is what makes interruption possible at all — a loop
that stops listening to talk cannot be interrupted by definition.

  capture thread   frames -> VAD -> Segmenter -> utterance queue
  main loop        utterance -> STT -> route -> LLM -> TTS worker
  TTS worker       sentence-by-sentence, polling state.should_stop()

BARGE-IN
--------
While speaking, the mic hears JARVIS as well as the user. Rather than guess a
fixed threshold — which depends on speaker volume, mic gain and whether
headphones are in — the loop measures its own leakage during the first moments
of playback and requires the user to clearly exceed it.
"""

from __future__ import annotations

import argparse
import sys
import threading
import time
from pathlib import Path
from queue import Empty, Queue

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from .audio_io import Microphone, duration_of
from .languages import DEFAULT, by_tag, detect_switch_request, voice_for
from .llm import LLM
from .state import ConversationState, Turn
from .stt import SpeechToText
from .tts import TextToSpeech
from .vad import Segmenter, make_vad, rms_of

WAKE_WORDS = ("jarvis", "jarviss", "jervis", "javis")

# Barge-in: the user must be this much louder than JARVIS's own leakage, and
# at least this loud in absolute terms for a quiet room.
BARGE_FACTOR = 2.0
BARGE_FLOOR = 0.030
BARGE_FRAMES = 8            # ~240ms sustained, not one loud syllable


class Conversation:
    def __init__(self, *, language=DEFAULT, require_wake=True,
                 auto_detect=True, verbose=True):
        self.state = ConversationState(language, auto_detect=auto_detect)
        if language is not DEFAULT:
            self.state.set_language(language, pin=True)

        self.mic = Microphone()
        self.vad = make_vad(2)
        self.seg = Segmenter(self.vad)
        self.stt = SpeechToText()
        self.tts = TextToSpeech()
        self.llm = LLM()

        self.require_wake = require_wake
        self.verbose = verbose

        self._utterances: Queue[bytes] = Queue()
        self._running = False
        self._speak_thread: threading.Thread | None = None

        # Measured leakage of JARVIS's own voice back into the mic.
        self._leak = 0.0
        self._loud_run = 0

    # ── output ───────────────────────────────────────────────────────────

    def say_line(self, who: str, text: str) -> None:
        if self.verbose:
            print(f"  {who:<7} {text}")

    # ── capture ──────────────────────────────────────────────────────────

    def _capture(self) -> None:
        """Owns the mic for the whole session."""
        for frame in self.mic.frames():
            if not self._running:
                break

            if self.state.is_speaking:
                # Everything the mic hears right now is mostly JARVIS. Track
                # the running peak as the floor a real interruption must clear.
                level = rms_of(frame)
                self._leak = max(self._leak * 0.995, level)
                bar = max(self._leak * BARGE_FACTOR, BARGE_FLOOR)

                if level > bar:
                    self._loud_run += 1
                    if self._loud_run >= BARGE_FRAMES:
                        self._loud_run = 0
                        self._on_barge_in()
                else:
                    self._loud_run = 0
                # Do not segment during playback: the utterance would be a
                # recording of JARVIS.
                continue

            done = self.seg.feed(frame)
            if done:
                self._utterances.put(done)

    def _on_barge_in(self) -> None:
        if self.state.request_interrupt():
            self.say_line("--", "(interrupted)")
            self.tts.stop()

    # ── speaking ─────────────────────────────────────────────────────────

    def _speak(self, text: str) -> None:
        self.state.set_turn(Turn.SPEAKING)
        self._leak = 0.0
        self._loud_run = 0

        result = self.tts.speak(text, self.state.language,
                                should_stop=self.state.should_stop)

        if result.note:
            self.say_line("note", result.note)

        if not result.completed and result.remaining:
            # Keep what was cut off so it can be offered back.
            self.state.request_interrupt(result.remaining)

        self.state.set_turn(Turn.IDLE)
        # Drop whatever the mic buffered during playback, or JARVIS's own tail
        # becomes the user's next "utterance".
        self.mic.drain()
        self.seg.reset()

    # ── routing ──────────────────────────────────────────────────────────

    def _strip_wake(self, text: str) -> tuple[bool, str]:
        low = text.lower()
        for w in WAKE_WORDS:
            i = low.find(w)
            if i == -1:
                continue
            after = text[i + len(w):].strip(" ,.:;!?")
            return True, (after or text[:i].strip(" ,.:;!?"))
        return False, text

    def _handle(self, text: str, detected) -> None:
        # 1. Explicit language switch, before anything else. "Speak in Tamil"
        #    is a command about the conversation, not a question to answer.
        target = detect_switch_request(text)
        if target:
            changed = self.state.set_language(target, pin=True)
            if not self.tts.can_speak(target):
                from .languages import missing_voice_note
                self.say_line("jarvis", missing_voice_note(target))
            ack = self.llm.reply(
                "The user asked you to switch to this language. "
                "Acknowledge in one short sentence.", target)
            self.say_line("jarvis", ack)
            self._speak(ack)
            self.say_line("--", f"(language -> {target.name}, pinned)")
            return

        # 2. Otherwise follow what they actually spoke, unless pinned.
        if detected and self.state.observe_detected(detected.name):
            self.say_line("--", f"(language -> {detected.name}, detected)")

        # 3. A pending resume offer answered yes/no.
        pending = self.state.take_unfinished()
        if pending and _is_yes(text):
            self.say_line("jarvis", "(resuming)")
            self._speak(pending)
            return

        # 4. Normal turn — stream sentences so speech starts early.
        self.state.set_turn(Turn.THINKING)
        lang = self.state.language
        sentences: list[str] = []

        for sentence in self.llm.stream_sentences(
                text, lang, should_stop=self.state.should_stop):
            sentences.append(sentence)
            if len(sentences) == 1:
                self.say_line("jarvis", sentence)
                self._speak(sentence)
                if self.state.should_stop():
                    break
            else:
                self.say_line("", sentence)
                self._speak(sentence)
                if self.state.should_stop():
                    break

        if pending:
            offer = "Before that, I was part way through something. Shall I finish it?"
            self.state.request_interrupt(pending)   # keep it for one more turn
            self.say_line("jarvis", offer)
            self._speak(offer)

    # ── main ─────────────────────────────────────────────────────────────

    def run(self) -> int:
        print("\n" + "=" * 66)
        print("  JARVIS — conversation loop")
        print("=" * 66)
        print(f"  language   {self.state.language.name}"
              f"{' (pinned)' if self.state.pinned else ' (auto-detect)'}")
        print(f"  voice      {voice_for(self.state.language) or 'none installed'}")
        print(f"  vad        {type(self.vad).__name__}")
        print(f"  wake word  {'required' if self.require_wake else 'not required'}")
        print("\n  Speak normally. Talk over JARVIS to interrupt. Ctrl-C to stop.\n")

        self._running = True
        self.mic.start()
        cap = threading.Thread(target=self._capture, daemon=True)
        cap.start()

        try:
            while self._running:
                try:
                    pcm = self._utterances.get(timeout=0.4)
                except Empty:
                    continue

                self.state.set_turn(Turn.LISTENING)
                hint = self.state.language if self.state.pinned else None
                result = self.stt.transcribe(pcm, hint=hint)

                if not result:
                    self.state.set_turn(Turn.IDLE)
                    continue

                heard = result.text.strip()
                woke, command = self._strip_wake(heard)

                if self.require_wake and not woke:
                    self.say_line("(heard)", heard)
                    self.state.set_turn(Turn.IDLE)
                    continue

                self.say_line("you", command or heard)
                self.state.record(command or heard)
                self._handle(command or heard, result.language)
                self.state.set_turn(Turn.IDLE)

        except KeyboardInterrupt:
            print("\n  stopping…")
        finally:
            self._running = False
            self.tts.stop()
            self.mic.stop()
            print(f"  mic stats: {self.mic.stats}")
        return 0


def _is_yes(text: str) -> bool:
    t = text.lower().strip()
    return any(t.startswith(w) for w in
               ("yes", "yeah", "yep", "sure", "go on", "carry on",
                "continue", "finish", "please do", "ok", "okay"))


def main() -> int:
    ap = argparse.ArgumentParser(description="JARVIS conversation loop")
    ap.add_argument("--lang", default=None,
                    help="start pinned to a language, e.g. ta-IN")
    ap.add_argument("--no-wake", action="store_true",
                    help="respond to everything, not just 'Jarvis ...'")
    ap.add_argument("--no-detect", action="store_true",
                    help="never switch language automatically")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    lang = by_tag(args.lang) if args.lang else DEFAULT
    if args.lang and not lang:
        print(f"unknown language {args.lang!r}")
        return 1

    return Conversation(
        language=lang or DEFAULT,
        require_wake=not args.no_wake,
        auto_detect=not args.no_detect,
        verbose=not args.quiet,
    ).run()


if __name__ == "__main__":
    sys.exit(main())
