#!/usr/bin/env python3
# Generated by Claudian.
"""End-to-end language and interruption self-test.

    python3 -m conversation.selftest              # the six mandatory languages
    python3 -m conversation.selftest --all        # every registered language
    python3 -m conversation.selftest --lang ta-IN
    python3 -m conversation.selftest --no-llm     # skip the network stages

WHY THIS EXISTS
---------------
"English works, other languages fail silently" is the hardest class of bug to
chase, because every individual piece reports success. The voice is listed.
The synthesiser exits zero. The model returns text. Nothing raises. And
nothing comes out of the speakers.

So this checks the thing that actually matters at each stage — did audio get
produced, does it contain sound, can it be recognised back — rather than
whether a call returned without error.

THE ROUND TRIP
--------------
The strongest stage is TTS -> STT. Synthesise a phrase in Tamil, feed the
audio straight back to Whisper, and check it comes back as Tamil. That single
test exercises the voice, the audio pipeline and the recogniser together, and
it cannot pass by accident.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from .languages import LANGUAGES, Language, by_tag, installed_voices, voice_for
from .state import ConversationState, Turn
from .tts import MacSayTTS, split_sentences

MANDATORY = ("en-US", "ta-IN", "hi-IN", "kn-IN", "ml-IN", "ja-JP")

# Something natural in each language, long enough to be recognisable but short
# enough that a full matrix does not take ten minutes.
PHRASES: dict[str, str] = {
    "en-US": "Hello, how are you doing today?",
    "ta-IN": "வணக்கம், நீங்கள் எப்படி இருக்கிறீர்கள்?",
    "hi-IN": "नमस्ते, आप कैसे हैं आज?",
    "kn-IN": "ನಮಸ್ಕಾರ, ನೀವು ಹೇಗಿದ್ದೀರಿ?",
    "ml-IN": "നമസ്കാരം, സുഖമാണോ?",
    "ja-JP": "こんにちは、今日はお元気ですか？",
    "te-IN": "నమస్కారం, మీరు ఎలా ఉన్నారు?",
    "bn-IN": "নমস্কার, আপনি কেমন আছেন?",
    "zh-CN": "你好，你今天好吗？",
    "es-ES": "Hola, ¿cómo estás hoy?",
    "fr-FR": "Bonjour, comment allez-vous?",
    "de-DE": "Hallo, wie geht es dir heute?",
    "ru-RU": "Здравствуйте, как дела?",
    "ar-SA": "مرحبا، كيف حالك اليوم؟",
    "ko-KR": "안녕하세요, 오늘 어떠세요?",
}

PASS, FAIL, SKIP, WARN = "PASS", "FAIL", "skip", "warn"


@dataclass
class Check:
    stage: str
    status: str
    detail: str = ""


@dataclass
class LangReport:
    lang: Language
    checks: list[Check] = field(default_factory=list)

    def add(self, stage: str, status: str, detail: str = "") -> None:
        self.checks.append(Check(stage, status, detail))

    @property
    def failed(self) -> bool:
        return any(c.status == FAIL for c in self.checks)


# ── Stages ───────────────────────────────────────────────────────────────────

def check_voice(rep: LangReport) -> str | None:
    voice = voice_for(rep.lang)
    if voice:
        rep.add("voice", PASS, voice)
        return voice
    rep.add("voice", FAIL, "no voice installed for this language")
    return None


def check_render(rep: LangReport, voice: str, text: str) -> Path | None:
    """Render to a file and prove it contains sound.

    An exit code of zero is not evidence. `say` happily produces a valid,
    perfectly silent file when handed a script its voice cannot render.
    """
    out = Path(tempfile.gettempdir()) / f"selftest_{rep.lang.code}.aiff"
    out.unlink(missing_ok=True)
    try:
        proc = subprocess.run(["say", "-v", voice, "-o", str(out), text],
                              capture_output=True, text=True, timeout=30)
    except subprocess.TimeoutExpired:
        rep.add("render", FAIL, "say timed out")
        return None

    if proc.returncode != 0 or not out.exists():
        rep.add("render", FAIL, (proc.stderr or "say failed").strip()[:70])
        return None

    size = out.stat().st_size
    if size < 4000:
        rep.add("render", FAIL, f"only {size} bytes — effectively empty")
        return None

    level = audio_level(out)
    if level is None:
        rep.add("render", WARN, f"{size} B, level unmeasurable")
    elif level < 0.005:
        # This is the silent-failure case the whole file exists to catch.
        rep.add("render", FAIL, f"{size} B but SILENT (rms {level:.4f})")
        return None
    else:
        rep.add("render", PASS, f"{size} B, rms {level:.3f}")
    return out


def audio_level(path: Path) -> float | None:
    """RMS of the rendered audio. Uses ffmpeg, which is already required."""
    try:
        import numpy as np
        proc = subprocess.run(
            ["ffmpeg", "-v", "error", "-i", str(path),
             "-f", "s16le", "-ac", "1", "-ar", "16000", "-"],
            capture_output=True, timeout=30)
        if proc.returncode != 0 or not proc.stdout:
            return None
        a = np.frombuffer(proc.stdout, dtype=np.int16).astype(np.float32) / 32768.0
        return float(np.sqrt(np.mean(a * a))) if a.size else 0.0
    except Exception:
        return None


def check_roundtrip(rep: LangReport, audio: Path) -> None:
    """Feed the synthesised audio back to the recogniser.

    The strongest single check here: it exercises the voice, the audio
    pipeline and the recogniser together, and cannot pass by accident.
    """
    try:
        proc = subprocess.run(
            ["ffmpeg", "-v", "error", "-i", str(audio),
             "-f", "s16le", "-ac", "1", "-ar", "16000", "-"],
            capture_output=True, timeout=30)
        pcm = proc.stdout
        if not pcm:
            rep.add("stt", SKIP, "could not decode the rendered audio")
            return

        from .stt import SpeechToText
        result = SpeechToText().transcribe(pcm)

        if not result.text:
            rep.add("stt", FAIL, f"no transcript ({result.engine})")
            return

        got = result.language.name if result.language else "?"
        if result.language and result.language.tag == rep.lang.tag:
            rep.add("stt", PASS, f"{got}: {result.text[:34]}")
        else:
            # Detected as something else — usually a related script, and worth
            # seeing rather than hiding.
            rep.add("stt", WARN, f"heard {got}: {result.text[:30]}")
    except Exception as exc:
        rep.add("stt", FAIL, f"{type(exc).__name__}: {exc}"[:60])


def check_llm(rep: LangReport) -> None:
    """Does the model actually reply IN the language, not about it."""
    try:
        from .llm import LLM
        reply = LLM().reply("Say a short friendly greeting.", rep.lang,
                            max_tokens=80)
        if not reply:
            rep.add("llm", FAIL, "empty reply")
            return

        # A refusal is the failure mode that actually happens: the model
        # decides it is being asked to synthesise audio and declines.
        low = reply.lower()
        if any(p in low for p in ("i can't", "i cannot", "unable to",
                                  "i'm not able")):
            rep.add("llm", FAIL, f"refused: {reply[:48]}")
            return

        if rep.lang.code != "en" and _is_mostly_ascii(reply):
            rep.add("llm", FAIL, f"replied in English: {reply[:40]}")
            return

        rep.add("llm", PASS, reply[:40])
    except Exception as exc:
        rep.add("llm", FAIL, f"{type(exc).__name__}: {exc}"[:60])


def _is_mostly_ascii(text: str) -> bool:
    """Non-Latin languages must come back in their own script."""
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return True
    return sum(c.isascii() for c in letters) / len(letters) > 0.7


def check_interrupt(rep: LangReport, text: str) -> None:
    """Cut synthesis off mid-sentence and measure how long it takes to stop."""
    state = ConversationState(rep.lang)
    state.set_turn(Turn.SPEAKING)
    tts = MacSayTTS(rate=185)

    long_text = " ".join([text] * 4)   # long enough to interrupt partway

    fired = threading.Event()

    def barge():
        time.sleep(1.2)
        state.request_interrupt()
        fired.set()

    threading.Thread(target=barge, daemon=True).start()
    t0 = time.perf_counter()
    result = tts.speak(long_text, rep.lang, should_stop=state.should_stop)
    elapsed = time.perf_counter() - t0

    if result.completed:
        rep.add("interrupt", FAIL, f"never stopped ({elapsed:.1f}s)")
    else:
        lag = elapsed - 1.2
        status = PASS if lag < 0.5 else WARN
        rep.add("interrupt", status, f"stopped {lag * 1000:.0f}ms after signal")


# ── Runner ───────────────────────────────────────────────────────────────────

ICON = {PASS: "PASS", FAIL: "FAIL", SKIP: "skip", WARN: "warn"}


def run_language(lang: Language, *, with_llm: bool, with_interrupt: bool) -> LangReport:
    rep = LangReport(lang)
    text = PHRASES.get(lang.tag) or PHRASES["en-US"]

    voice = check_voice(rep)
    audio = check_render(rep, voice, text) if voice else None

    if audio:
        check_roundtrip(rep, audio)
    else:
        rep.add("stt", SKIP, "no audio to test")

    if with_llm:
        check_llm(rep)
    else:
        rep.add("llm", SKIP, "--no-llm")

    if with_interrupt and voice:
        check_interrupt(rep, text)
    else:
        rep.add("interrupt", SKIP, "no voice" if not voice else "--no-interrupt")

    return rep


def main() -> int:
    ap = argparse.ArgumentParser(description="Language + interruption self-test")
    ap.add_argument("--lang", action="append", help="specific tags to test")
    ap.add_argument("--all", action="store_true", help="every language with a phrase")
    ap.add_argument("--no-llm", action="store_true")
    ap.add_argument("--no-interrupt", action="store_true")
    args = ap.parse_args()

    if args.lang:
        tags = args.lang
    elif args.all:
        tags = [t for t in PHRASES]
    else:
        tags = list(MANDATORY)

    langs = []
    for t in tags:
        lang = by_tag(t)
        if lang is None:
            print(f"unknown language {t!r}")
            return 1
        langs.append(lang)

    print("\n" + "=" * 78)
    print("  JARVIS — language and interruption self-test")
    print("=" * 78)
    print(f"  installed voice locales: {len(installed_voices())}")
    print(f"  testing: {', '.join(l.tag for l in langs)}\n")

    reports = []
    for lang in langs:
        print(f"  {lang.name} ({lang.tag})")
        rep = run_language(lang, with_llm=not args.no_llm,
                           with_interrupt=not args.no_interrupt)
        for c in rep.checks:
            print(f"      {ICON[c.status]:5} {c.stage:10} {c.detail}")
        reports.append(rep)
        print()

    # ── Matrix ───────────────────────────────────────────────────────────
    stages = ["voice", "render", "stt", "llm", "interrupt"]
    print("=" * 78)
    print(f"  {'language':14}" + "".join(f"{s:12}" for s in stages))
    print("  " + "-" * 74)
    for rep in reports:
        row = f"  {rep.lang.name[:13]:14}"
        for stage in stages:
            c = next((x for x in rep.checks if x.stage == stage), None)
            row += f"{ICON[c.status] if c else '-':12}"
        print(row)

    failed = [r for r in reports if r.failed]
    print("=" * 78)
    if failed:
        print(f"  {len(failed)} of {len(reports)} languages have failures: "
              f"{', '.join(r.lang.name for r in failed)}")
    else:
        print(f"  all {len(reports)} languages passed")
    print()
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
