# Generated by Claudian.
"""Conversation state — the single source of truth for language and turn.

Everything here is touched from more than one thread. Audio capture runs on a
PortAudio callback thread, synthesis runs on its own, and the orchestrator
runs on the main thread. Anything they share has to be guarded, so all mutable
state lives behind one lock and is only reachable through methods.

The interruption flag is an `threading.Event` rather than a bool on purpose:
the TTS engine needs to poll it between audio chunks without acquiring a lock
on every 4KB of PCM.
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field
from enum import Enum

from .languages import DEFAULT, Language, by_name, by_tag


class Turn(Enum):
    """Who holds the floor."""
    IDLE = "idle"            # nobody talking
    LISTENING = "listening"  # user is speaking
    THINKING = "thinking"    # transcribed, waiting on the model
    SPEAKING = "speaking"    # JARVIS is talking


@dataclass
class Utterance:
    text: str
    language: Language
    at: float = field(default_factory=time.time)
    interrupted: bool = False


class ConversationState:
    """Language, turn-taking and interruption for one conversation."""

    def __init__(self, language: Language = DEFAULT, *, auto_detect: bool = True):
        self._lock = threading.RLock()

        self._language = language
        self._pinned = False        # True once the user asks explicitly
        self._auto_detect = auto_detect

        self._turn = Turn.IDLE
        self._history: list[Utterance] = []

        # Polled by the TTS engine between chunks — an Event avoids taking the
        # lock on every buffer.
        self.interrupt = threading.Event()

        # What JARVIS was saying when it got cut off, so it can offer to
        # resume rather than silently dropping the thread.
        self._unfinished: str | None = None
        self._unfinished_at: float = 0.0

    # ── Language ─────────────────────────────────────────────────────────

    @property
    def language(self) -> Language:
        with self._lock:
            return self._language

    @property
    def pinned(self) -> bool:
        """True when the user explicitly chose the language.

        Once pinned, detection stops overriding it. Without this a single
        mis-detected utterance would silently throw the conversation back
        into English after the user had asked for Tamil.
        """
        with self._lock:
            return self._pinned

    def set_language(self, lang: Language, *, pin: bool = True) -> bool:
        """Returns True if the language actually changed."""
        with self._lock:
            changed = lang.tag != self._language.tag
            self._language = lang
            if pin:
                self._pinned = True
            return changed

    def observe_detected(self, name_or_tag: str) -> bool:
        """Feed in what the recogniser detected.

        Ignored when the language is pinned. Returns True if it changed.
        """
        lang = by_name(name_or_tag) or by_tag(name_or_tag)
        if not lang:
            return False
        with self._lock:
            if self._pinned or not self._auto_detect:
                return False
            changed = lang.tag != self._language.tag
            self._language = lang
            return changed

    def unpin(self) -> None:
        """Return to following whatever the user speaks."""
        with self._lock:
            self._pinned = False

    # ── Turn taking ──────────────────────────────────────────────────────

    @property
    def turn(self) -> Turn:
        with self._lock:
            return self._turn

    def set_turn(self, turn: Turn) -> None:
        with self._lock:
            self._turn = turn
        # Leaving SPEAKING always clears the flag: a stale interrupt would
        # abort the *next* reply before it began.
        if turn is not Turn.SPEAKING:
            self.interrupt.clear()

    @property
    def is_speaking(self) -> bool:
        return self.turn is Turn.SPEAKING

    # ── Interruption ─────────────────────────────────────────────────────

    def request_interrupt(self, spoken_so_far: str | None = None) -> bool:
        """Cut JARVIS off. Returns True if it was actually speaking."""
        if not self.is_speaking:
            return False
        with self._lock:
            # Only overwrite when the caller gives us new text.  An interrupt
            # with no argument (e.g. barge-in during a resume *offer*) must not
            # destroy the pending text that the offer was trying to surface.
            if spoken_so_far is not None:
                self._unfinished = spoken_so_far
                self._unfinished_at = time.time()
        self.interrupt.set()
        return True

    def should_stop(self) -> bool:
        """Polled by the TTS engine between audio chunks."""
        return self.interrupt.is_set()

    def take_unfinished(self, max_age: float = 300.0) -> str | None:
        """Retrieve and clear what was cut off, if it is still relevant.

        Offering to resume something from ten minutes ago is noise, not
        helpfulness, so stale threads are dropped rather than surfaced.
        """
        with self._lock:
            text, at = self._unfinished, self._unfinished_at
            self._unfinished = None
            self._unfinished_at = 0.0
        if not text or (time.time() - at) > max_age:
            return None
        return text

    # ── History ──────────────────────────────────────────────────────────

    def record(self, text: str, *, interrupted: bool = False) -> None:
        with self._lock:
            self._history.append(
                Utterance(text=text, language=self._language,
                          interrupted=interrupted))
            del self._history[:-200]     # bounded; this can run for days

    def recent(self, n: int = 10) -> list[Utterance]:
        with self._lock:
            return list(self._history[-n:])

    def snapshot(self) -> dict:
        """Everything a UI needs, taken under one lock."""
        with self._lock:
            return {
                "language": self._language.tag,
                "language_name": self._language.name,
                "pinned": self._pinned,
                "auto_detect": self._auto_detect,
                "turn": self._turn.value,
                "interrupting": self.interrupt.is_set(),
                "has_unfinished": self._unfinished is not None,
                "turns": len(self._history),
            }
