# Generated by Claudian.
"""Multilingual speech to text.

Two engines behind one call:

  Groq whisper-large-v3-turbo   229ms, needs network
  local Whisper                 1118ms, fully offline

Measured on this machine over six known phrases, both at 0.951 accuracy — a
4.9x speedup using a strictly larger model, so Groq leads and local is the
fallback rather than the other way round.

The important detail is that `language` is NOT sent. Pinning it forces the
decoder to interpret everything as that language, and Tamil decoded as
English comes back as phonetic gibberish. Letting Whisper detect is what
makes "just start speaking Tamil" work at all — and the detected language is
returned so the rest of the system can follow it.
"""

from __future__ import annotations

import os
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from .audio_io import duration_of, pcm_to_wav
from .languages import DEFAULT, Language, by_name


@dataclass
class Transcript:
    text: str
    language: Optional[Language]
    engine: str
    seconds: float = 0.0

    def __bool__(self) -> bool:
        return bool(self.text.strip())


# Whisper hallucinates set phrases on silence or noise — subtitle boilerplate
# from its training data. Dropping them stops JARVIS answering a cough.
_HALLUCINATIONS = {
    "thank you", "thanks for watching", "thank you.", "you", ".", "bye",
    "thanks for watching!", "please subscribe", "subscribe", "okay",
    "silence", "[music]", "[silence]", "music", "so", "uh", "um",
}


def _looks_hallucinated(text: str, seconds: float) -> bool:
    t = text.strip().lower().strip(".!?,")
    if not t:
        return True
    # A long clip returning two words is a hallucination; a short clip
    # returning two words is somebody saying two words.
    return t in _HALLUCINATIONS and seconds > 1.2


class GroqSTT:
    name = "groq"

    def __init__(self, model: Optional[str] = None):
        from config import settings
        self.key = settings.GROQ_API_KEY
        self.model = model or settings.GROQ_STT_MODEL

    @property
    def available(self) -> bool:
        return bool(self.key)

    def transcribe(self, pcm: bytes, hint: Optional[Language] = None) -> Transcript:
        from groq import Groq

        client = Groq(api_key=self.key, timeout=25)
        kwargs = {
            "file": ("speech.wav", pcm_to_wav(pcm)),
            "model": self.model,
            "response_format": "verbose_json",
        }
        # A hint is only passed when the user has PINNED a language. Detection
        # stays on otherwise, which is the entire point.
        if hint is not None:
            kwargs["language"] = hint.code

        resp = client.audio.transcriptions.create(**kwargs)
        return Transcript(
            text=(getattr(resp, "text", "") or "").strip(),
            language=by_name(getattr(resp, "language", "") or "") or hint,
            engine=self.name,
        )


class LocalWhisperSTT:
    name = "whisper-local"
    _model = None

    def __init__(self, size: Optional[str] = None):
        from config import settings
        self.size = size or settings.WHISPER_MODEL_SIZE

    @property
    def available(self) -> bool:
        try:
            import whisper  # noqa: F401
            return True
        except ImportError:
            return False

    def transcribe(self, pcm: bytes, hint: Optional[Language] = None) -> Transcript:
        import whisper

        if LocalWhisperSTT._model is None:
            LocalWhisperSTT._model = whisper.load_model(self.size)

        # whisper.load_audio shells out to ffmpeg, which needs a real path.
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as fh:
            fh.write(pcm_to_wav(pcm))
            tmp = fh.name
        try:
            kw = {"fp16": False}
            if hint is not None:
                kw["language"] = hint.code
            out = LocalWhisperSTT._model.transcribe(tmp, **kw)
            return Transcript(
                text=(out.get("text") or "").strip(),
                language=by_name(out.get("language") or "") or hint,
                engine=self.name,
            )
        finally:
            try:
                os.unlink(tmp)
            except OSError:
                pass


class SpeechToText:
    """Tries each engine in order, returns the first real result."""

    def __init__(self, engines=None):
        self.engines = engines or [GroqSTT(), LocalWhisperSTT()]

    def transcribe(self, pcm: bytes, *, hint: Optional[Language] = None) -> Transcript:
        seconds = duration_of(pcm)

        # Below ~250ms there is not enough signal to transcribe; whatever
        # comes back is invented.
        if seconds < 0.25:
            return Transcript("", None, "skipped", seconds)

        errors = []
        for engine in self.engines:
            if not engine.available:
                continue
            try:
                result = engine.transcribe(pcm, hint)
            except Exception as exc:
                errors.append(f"{engine.name}: {str(exc)[:120]}")
                continue

            result.seconds = seconds
            if not result.text:
                continue
            if _looks_hallucinated(result.text, seconds):
                return Transcript("", result.language, engine.name, seconds)
            return result

        return Transcript("", None, "failed:" + "|".join(errors), seconds)
