# Generated by Claudian.
"""Voice activity detection, and the segmenter built on it.

Two detectors, same interface:

  WebRTC VAD   Google's, via `webrtcvad`. Trained on speech, so it rejects
               keyboard clatter and fan noise that trip a plain energy gate.
               Fixed contract: 16-bit mono PCM, 8/16/32/48 kHz, and frames of
               exactly 10, 20 or 30 ms.

  Energy VAD   RMS with hysteresis. Used when webrtcvad is unavailable.
               Cruder, but no build dependency.

The segmenter turns a frame-by-frame yes/no into whole utterances, which is
the part that actually matters:

  PRE-ROLL    Speech is only confirmed after several voiced frames, by which
              point the first syllable has already been spoken. A ring buffer
              of preceding frames is prepended so "open chrome" does not
              arrive as "pen chrome".

  HANGOVER    A single unvoiced frame is a stop consonant, not the end of a
              sentence. Silence must persist before the utterance closes.
"""

from __future__ import annotations

import collections
from typing import Iterator, Optional

import numpy as np

SAMPLE_RATE = 16000
FRAME_MS = 30
FRAME_SAMPLES = SAMPLE_RATE * FRAME_MS // 1000    # 480
FRAME_BYTES = FRAME_SAMPLES * 2                   # int16


class EnergyVAD:
    """RMS gate with hysteresis. No dependencies."""

    def __init__(self, start: float = 0.022, stop: float = 0.012):
        self.start = start
        self.stop = stop
        self._open = False

    def is_speech(self, frame: bytes, sample_rate: int = SAMPLE_RATE) -> bool:
        pcm = np.frombuffer(frame, dtype=np.int16).astype(np.float32) / 32768.0
        if pcm.size == 0:
            return False
        rms = float(np.sqrt(np.mean(pcm * pcm)))
        # Two thresholds, not one: a single level chatters on and off through
        # the natural dips inside a word.
        self._open = rms > (self.stop if self._open else self.start)
        return self._open


class WebRTCVAD:
    """Google's VAD. Aggressiveness 0 (permissive) to 3 (strict)."""

    def __init__(self, aggressiveness: int = 2):
        import webrtcvad
        self._vad = webrtcvad.Vad(aggressiveness)

    def is_speech(self, frame: bytes, sample_rate: int = SAMPLE_RATE) -> bool:
        # webrtcvad raises on any unexpected frame length rather than coping,
        # so a truncated final frame must not reach it.
        if len(frame) != FRAME_BYTES:
            return False
        try:
            return self._vad.is_speech(frame, sample_rate)
        except Exception:
            return False


def make_vad(aggressiveness: int = 2):
    """Best available detector, silently degrading to energy."""
    try:
        return WebRTCVAD(aggressiveness)
    except Exception:
        return EnergyVAD()


class Segmenter:
    """Frame-level speech/silence to complete utterances.

    Feed frames in; get back PCM for each finished utterance.
    """

    def __init__(
        self,
        vad=None,
        *,
        start_frames: int = 3,        # ~90ms of speech confirms an utterance
        end_frames: int = 25,         # ~750ms of silence ends it
        preroll_frames: int = 10,     # ~300ms kept before the trigger
        max_frames: int = 500,        # ~15s hard cap
    ):
        self.vad = vad or make_vad()
        self.start_frames = start_frames
        self.end_frames = end_frames
        self.max_frames = max_frames

        self._ring: collections.deque[bytes] = collections.deque(maxlen=preroll_frames)
        self._voiced: list[bytes] = []
        self._triggered = False
        self._speech_run = 0
        self._silence_run = 0

    def reset(self) -> None:
        self._ring.clear()
        self._voiced.clear()
        self._triggered = False
        self._speech_run = self._silence_run = 0

    @property
    def in_speech(self) -> bool:
        return self._triggered

    def feed(self, frame: bytes) -> Optional[bytes]:
        """Returns complete utterance PCM, or None if still listening."""
        speech = self.vad.is_speech(frame)

        if not self._triggered:
            self._ring.append(frame)
            self._speech_run = self._speech_run + 1 if speech else 0
            if self._speech_run >= self.start_frames:
                self._triggered = True
                # Prepend the ring buffer — without it the leading consonant
                # of the first word is already gone.
                self._voiced = list(self._ring)
                self._ring.clear()
                self._silence_run = 0
            return None

        self._voiced.append(frame)

        if speech:
            self._silence_run = 0
        else:
            self._silence_run += 1
            if self._silence_run >= self.end_frames:
                return self._finish()

        if len(self._voiced) >= self.max_frames:
            return self._finish()
        return None

    def _finish(self) -> bytes:
        pcm = b"".join(self._voiced)
        self.reset()
        return pcm

    def flush(self) -> Optional[bytes]:
        """Close out whatever is buffered — used on shutdown."""
        if self._triggered and self._voiced:
            return self._finish()
        self.reset()
        return None


def frames_from(pcm: bytes, frame_bytes: int = FRAME_BYTES) -> Iterator[bytes]:
    """Split a PCM buffer into fixed frames, dropping any short tail."""
    for i in range(0, len(pcm) - frame_bytes + 1, frame_bytes):
        yield pcm[i:i + frame_bytes]


def rms_of(pcm: bytes) -> float:
    a = np.frombuffer(pcm, dtype=np.int16).astype(np.float32) / 32768.0
    return float(np.sqrt(np.mean(a * a))) if a.size else 0.0
