# Generated by Claudian.
"""Read delivered WhatsApp notifications from macOS Notification Center.

WHY THIS AND NOT A WHATSAPP CLIENT
-----------------------------------
Reading messages properly means whatsapp-web.js driving a logged-in session,
which is unofficial automation of a personal account and gets numbers banned.
Ruthish's number has his family and his girlfriend on it, so that risk is not
worth taking for a convenience feature.

macOS already receives every WhatsApp message as a notification and stores it
locally. Reading that database is read-only, touches no WhatsApp service, and
cannot get an account banned. It is strictly less capable — see LIMITS — but
the failure mode is "misses a message", not "loses the account".

LIMITS — real, and worth stating plainly
----------------------------------------
* Only what Notification Center was told. If message previews are off, the
  body is "Message" and the text is simply not there to read.
* Muted chats deliver no notification at all.
* Notifications are pruned by macOS, so this is a recent window, not history.
* Reading a message on the phone can clear it here before JARVIS sees it.

PERMISSION
----------
Needs **Full Disk Access** for whatever runs JARVIS (Terminal, or Neutron).
Without it sqlite reports "unable to open database file" and every function
here returns empty rather than raising — a missing optional feature must not
take the assistant down with it.
"""

from __future__ import annotations

import plistlib
import sqlite3
import time
from dataclasses import dataclass
from pathlib import Path

from utils.logger import get_logger

logger = get_logger(__name__)

DB_PATH = (Path.home() / "Library" / "Group Containers"
           / "group.com.apple.usernoted" / "db2" / "db")

# Lowercase in the database, despite the app bundle being "net.whatsapp.WhatsApp".
# Matched case-insensitively rather than hard-coding either spelling: an exact
# match against the wrong case returned zero rows and looked exactly like
# "you have no messages", which is the worst possible way to be wrong.
WHATSAPP_BUNDLE = "net.whatsapp.whatsapp"

# Cocoa timestamps count seconds from 2001-01-01, not 1970-01-01.
APPLE_EPOCH_OFFSET = 978307200.0

# Bodies macOS substitutes when previews are hidden. Reporting these as the
# message text would be worse than saying a message arrived without the text.
_PLACEHOLDER_BODIES = {"message", "new message", "messages", ""}


@dataclass
class Notification:
    sender: str
    body: str
    when: float          # unix epoch
    group: str = ""      # set when the message came from a group chat

    @property
    def has_text(self) -> bool:
        return self.body.strip().lower() not in _PLACEHOLDER_BODIES

    # Spoken aloud, so a 400-character bank alert has to be cut short. Reading
    # one in full costs ~40 seconds and buries every message after it.
    SPOKEN_CHARS = 140

    def _short(self) -> str:
        b = self.body
        return b if len(b) <= self.SPOKEN_CHARS else b[: self.SPOKEN_CHARS - 1].rstrip() + "…"

    def spoken(self) -> str:
        who = f"{self.sender} in {self.group}" if self.group else self.sender
        if not self.has_text:
            return f"{who} sent you a message"
        return f"{who} said: {self._short()}"


def available() -> tuple[bool, str]:
    """(usable, reason). Checked before use so the UI can explain itself."""
    if not DB_PATH.exists():
        return False, "Notification Center database not found"
    try:
        con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
        con.execute("select 1 from record limit 1")
        con.close()
        return True, ""
    except sqlite3.OperationalError as e:
        if "unable to open" in str(e).lower():
            return False, ("Full Disk Access not granted — enable it for the "
                           "app that runs JARVIS in System Settings > Privacy "
                           "& Security > Full Disk Access")
        return False, str(e)[:120]
    except Exception as e:  # noqa: BLE001
        return False, str(e)[:120]


# WhatsApp prefixes names with U+200E (left-to-right mark) so mixed-script
# names render correctly. It is invisible on screen and meaningless aloud, but
# it survives into the string and into the TTS input.
_INVISIBLE = dict.fromkeys(map(ord, "\u200e\u200f\u202a\u202b\u202c\u2066\u2067\u2068\u2069"))


def _clean(v) -> str:
    """Strip bidi marks and collapse newlines — this text gets spoken aloud."""
    return " ".join(str(v or "").translate(_INVISIBLE).split())


def _extract(blob: bytes) -> tuple[str, str, str]:
    """(title, subtitle, body) from a notification's binary plist payload."""
    try:
        data = plistlib.loads(blob)
    except Exception:
        return "", "", ""
    # The user-visible fields live under "req"; older records inline them.
    req = data.get("req") if isinstance(data, dict) else None
    src = req if isinstance(req, dict) else (data if isinstance(data, dict) else {})
    return (_clean(src.get("titl", "")),
            _clean(src.get("subt", "")),
            _clean(src.get("body", "")))


def recent(since: float = 0.0, limit: int = 50) -> list[Notification]:
    """WhatsApp notifications delivered after `since` (unix epoch), newest last.

    Returns [] on any problem — no permission, no database, unreadable rows.
    """
    ok, why = available()
    if not ok:
        logger.debug(f"notification read unavailable: {why}")
        return []

    try:
        con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
        rows = con.execute(
            """
            SELECT r.data, r.delivered_date
            FROM record r JOIN app a ON a.app_id = r.app_id
            WHERE lower(a.identifier) = ? AND r.delivered_date IS NOT NULL
            ORDER BY r.delivered_date DESC
            LIMIT ?
            """,
            (WHATSAPP_BUNDLE, limit),
        ).fetchall()
        con.close()
    except Exception as e:  # noqa: BLE001
        logger.debug(f"notification query failed: {e}")
        return []

    out: list[Notification] = []
    for blob, delivered in rows:
        when = (delivered or 0.0) + APPLE_EPOCH_OFFSET
        if when <= since:
            continue
        titl, subt, body = _extract(blob)
        if not titl and not body:
            continue
        # WhatsApp puts the PERSON in the title and the GROUP in the subtitle.
        # Reading it the other way round announced "SRMIST-CSE DEPT STUDENTS in
        # Kanaga Suba Raja HOD SRM" — the group described as the sender.
        # Direct chats leave the subtitle empty.
        out.append(Notification(sender=titl, body=body, when=when, group=subt))

    out.reverse()          # oldest first reads naturally when spoken
    return out


def summarise(notes: list[Notification]) -> str:
    """One spoken sentence for a batch of messages."""
    if not notes:
        return "No new WhatsApp messages."

    # Collapse per sender: "Aki sent 3 messages" beats reading all three when
    # someone is mid-conversation.
    by_sender: dict[str, list[Notification]] = {}
    for n in notes:
        by_sender.setdefault(n.group or n.sender, []).append(n)

    parts = []
    for who, items in by_sender.items():
        last = items[-1]
        if len(items) == 1:
            parts.append(last.spoken())
        else:
            tail = f", the last one: {last._short()}" if last.has_text else ""
            parts.append(f"{who} sent {len(items)} messages{tail}")
    return ". ".join(parts) + "."


def latest_timestamp() -> float:
    """Newest delivered WhatsApp notification, or 0.0. Used to seed a watcher
    so it reports what arrives *next* rather than replaying the backlog."""
    notes = recent(limit=1)
    return notes[-1].when if notes else time.time()
