# Generated by Claudian.
"""Server-side speech-to-text for the desktop apps.

WHY THIS EXISTS
---------------
`webkitSpeechRecognition` works in Chrome but always fails in Electron with
`network`. The browser API is a thin client for Google's speech service, and
it authenticates with a key compiled into official Chrome builds. Electron
does not ship that key, so the request is rejected before it leaves the
machine. No amount of retrying fixes it.

That is fine, because JARVIS already had better STT than the browser API:
Groq's whisper-large-v3-turbo, measured at 229ms against local Whisper's
1118ms at identical accuracy.

ORDER
-----
  1. Groq whisper-large-v3-turbo  — fast, accurate, needs network + key
  2. Local Whisper                — slower, fully offline, needs ffmpeg

Both accept the browser's WebM/Opus directly; no transcoding on our side.
"""

from __future__ import annotations

import io
import os
import tempfile
from pathlib import Path
from typing import Optional

# Whisper wants a language hint as ISO-639-1, not BCP-47.
def iso639(tag: str) -> str:
    return (tag or "en").split("-")[0].lower()


# Whisper reports the language as an English NAME ("Tamil"), not a code.
# TTS voice selection needs a BCP-47 tag, so map between them.
NAME_TO_TAG = {
    "english": "en-US", "tamil": "ta-IN", "hindi": "hi-IN",
    "kannada": "kn-IN", "malayalam": "ml-IN", "japanese": "ja-JP",
    "chinese": "zh-CN", "mandarin": "zh-CN", "spanish": "es-ES",
    "arabic": "ar-SA", "french": "fr-FR", "portuguese": "pt-BR",
    "russian": "ru-RU", "german": "de-DE", "korean": "ko-KR",
    "italian": "it-IT", "indonesian": "id-ID", "turkish": "tr-TR",
    "vietnamese": "vi-VN", "thai": "th-TH", "dutch": "nl-NL",
    "polish": "pl-PL", "telugu": "te-IN", "bengali": "bn-IN",
    "marathi": "mr-IN", "gujarati": "gu-IN", "punjabi": "pa-IN",
    "urdu": "ur-PK", "nepali": "ne-NP", "sinhala": "si-LK",
}


def tag_for(name: str) -> str:
    return NAME_TO_TAG.get((name or "").strip().lower(), "")


def _groq_transcribe(data: bytes, filename: str, lang: str) -> Optional[str]:
    from config import settings
    if not settings.GROQ_API_KEY:
        return None
    try:
        from groq import Groq
        client = Groq(api_key=settings.GROQ_API_KEY, timeout=25)
        # The SDK takes a (name, bytes) tuple — no temp file needed.
        # No `language` argument on purpose. Pinning it forces Whisper to
        # decode everything as that language — Tamil speech fed to an English
        # decoder comes back as phonetic nonsense. Letting it detect means you
        # can simply start speaking Tamil and be understood.
        kwargs = {
            "file": (filename or "audio.webm", data),
            "model": settings.GROQ_STT_MODEL,
            "response_format": "verbose_json",
        }
        if lang and lang.lower() not in ("auto", "", "detect"):
            kwargs["language"] = iso639(lang)

        resp = client.audio.transcriptions.create(**kwargs)
        text = (getattr(resp, "text", "") or "").strip()
        detected = getattr(resp, "language", "") or ""
        if text:
            return {"text": text, "language": detected,
                    "tag": tag_for(detected) or (lang or "en-US")}
        return None
    except Exception as exc:  # noqa: BLE001 — fall through to the local engine
        raise RuntimeError(f"groq: {exc}") from exc


_local_model = None


def _local_transcribe(data: bytes, lang: str) -> Optional[str]:
    """Offline fallback. Loads the model once and keeps it resident."""
    global _local_model
    try:
        import whisper
    except ImportError:
        return None

    from config import settings
    if _local_model is None:
        _local_model = whisper.load_model(settings.WHISPER_MODEL_SIZE)

    # whisper.load_audio shells out to ffmpeg, which needs a real path.
    with tempfile.NamedTemporaryFile(suffix=".webm", delete=False) as fh:
        fh.write(data)
        tmp = fh.name
    try:
        # Same rule as the Groq path: omitting `language` lets Whisper
        # detect. Passing the literal string "auto" is rejected outright.
        kw = {"fp16": False}
        if lang and lang.lower() not in ("auto", "", "detect"):
            kw["language"] = iso639(lang)
        result = _local_model.transcribe(tmp, **kw)
        return (result.get("text") or "").strip() or None
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def transcribe(data: bytes, filename: str = "audio.webm",
               lang: str = "en-US") -> dict:
    """Transcribe an audio blob. Never raises — reports which engine won."""
    if not data:
        return {"ok": False, "text": "", "engine": None, "error": "empty audio"}

    # Opus frames for a fraction of a second are noise, not speech.
    if len(data) < 1200:
        return {"ok": True, "text": "", "engine": "skipped",
                "note": "clip too short"}

    errors = []

    try:
        got = _groq_transcribe(data, filename, lang)
        if got:
            return {"ok": True, "engine": "groq", **got}
        errors.append("groq: empty")
    except Exception as exc:  # noqa: BLE001
        errors.append(str(exc)[:160])

    try:
        text = _local_transcribe(data, lang)
        if text:
            return {"ok": True, "text": text, "engine": "whisper-local",
                    "language": "", "tag": lang or "en-US"}
        errors.append("local: empty")
    except Exception as exc:  # noqa: BLE001
        errors.append(f"local: {exc}"[:160])

    return {"ok": False, "text": "", "engine": None, "error": " | ".join(errors)}
